const $=id=>document.getElementById(id),API='https://api.spotify.com/v1';
const SCOPES=['streaming','user-read-private','user-read-email','user-top-read','user-read-recently-played','user-read-currently-playing','user-read-playback-state','user-modify-playback-state','user-library-read','playlist-read-private'].join(' ');
let token=null,refreshToken=null,expiresAt=0,tokenRefreshPromise=null,tokenRefreshCount=0,playback=null,lastTrackId=null,queue=[],tracksSinceTalk=0,nextTalkAt=4,djBusy=false,skipNextTalk=false,poll=null,session=[],weatherCache=null,spotifyClientId=localStorage.getItem('jfm_client_id')||'';
let settings=JSON.parse(localStorage.getItem('jfm_settings')||'{}');
const MODES={normal:{label:'Normaal',intro:'lekker gevarieerd en natuurlijk'},morning:{label:'Ochtend',intro:'fris en positief, als een moderne ochtendshow'},chill:{label:'Chill',intro:'rustig, warm en ontspannen'},party:{label:'Party',intro:'energieker, kort en enthousiast'},throwback:{label:'Throwback',intro:'nostalgisch, met aandacht voor oudere tracks',year:2016},late:{label:'Late night',intro:'rustig, droog en late-night radioachtig'}};
function redirectUri(){return location.origin+location.pathname}
$('redirect').value=redirectUri();$('clientId').value=spotifyClientId;
async function timedFetch(input,opt={},timeoutMs=12000){const controller=new AbortController(),upstream=opt.signal;let detach=()=>{};if(upstream){if(upstream.aborted)controller.abort(upstream.reason);else{const abort=()=>controller.abort(upstream.reason);upstream.addEventListener('abort',abort,{once:true});detach=()=>upstream.removeEventListener('abort',abort)}}const timer=setTimeout(()=>controller.abort('timeout'),timeoutMs);try{return await fetch(input,{...opt,signal:controller.signal})}catch(e){if(controller.signal.aborted&&!upstream?.aborted)throw Error('Netwerkverzoek duurde te lang. Controleer je verbinding en probeer opnieuw.');throw e}finally{clearTimeout(timer);detach()}}
async function loadPublicConfig(){try{const r=await timedFetch('/api/config',{},8000);if(r.ok){const d=await r.json();if(d.spotifyClientId){spotifyClientId=d.spotifyClientId;localStorage.setItem('jfm_client_id',spotifyClientId);$('clientId').value=spotifyClientId;const label=$('clientId').closest('label');if(label)label.classList.add('hidden')}}}catch{}return spotifyClientId}
function saveSettings(){settings={mode:settings.mode||'normal',talk:Number($('talk').value),facts:$('facts').checked,time:$('timeMention').checked,weather:$('weatherMention').checked,jingles:$('jingles').checked,voiceMode:$('voiceMode').value,source:$('source').value};localStorage.setItem('jfm_settings',JSON.stringify(settings))}
function loadSettings(){settings={mode:'normal',talk:1,facts:true,time:true,weather:false,jingles:true,voiceMode:'auto',source:'top',...settings};$('talk').value=settings.talk;$('facts').checked=settings.facts;$('timeMention').checked=settings.time;$('weatherMention').checked=settings.weather;$('jingles').checked=settings.jingles;$('voiceMode').value=settings.voiceMode;$('source').value=settings.source;$('playlist').classList.toggle('hidden',settings.source!=='playlist');setMode(settings.mode,false);updateTalkLabel()}
function b64url(b){return btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function sha256(s){return crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))}
function rand(n=64){const c='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~',a=new Uint32Array(n);crypto.getRandomValues(a);return [...a].map(x=>c[x%c.length]).join('')}
async function connect(){const id=spotifyClientId||$('clientId').value.trim();if(!id)return alert('Spotify Client ID ontbreekt. Voeg SPOTIFY_CLIENT_ID toe in Vercel.');spotifyClientId=id;localStorage.setItem('jfm_client_id',id);const verifier=rand(),state=rand(20);sessionStorage.setItem('jfm_verifier',verifier);sessionStorage.setItem('jfm_state',state);const challenge=b64url(await sha256(verifier));const p=new URLSearchParams({response_type:'code',client_id:id,scope:SCOPES,redirect_uri:redirectUri(),state,code_challenge_method:'S256',code_challenge:challenge});location.href='https://accounts.spotify.com/authorize?'+p}
async function callback(){const q=new URLSearchParams(location.search),code=q.get('code');if(!code){restore();return}if(q.get('state')!==sessionStorage.getItem('jfm_state'))throw Error('Spotify-beveiligingscontrole mislukt.');const id=spotifyClientId||localStorage.getItem('jfm_client_id');const body=new URLSearchParams({client_id:id,grant_type:'authorization_code',code,redirect_uri:redirectUri(),code_verifier:sessionStorage.getItem('jfm_verifier')});const r=await timedFetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw Error('Spotify koppelen mislukt.');saveToken(await r.json());history.replaceState({},'',location.pathname)}
function saveToken(d){token=d.access_token;refreshToken=d.refresh_token||refreshToken;expiresAt=Date.now()+(d.expires_in||3600)*1000-30000;localStorage.setItem('jfm_token',token);if(refreshToken)localStorage.setItem('jfm_refresh',refreshToken);localStorage.setItem('jfm_exp',String(expiresAt))}
function restore(){token=localStorage.getItem('jfm_token');refreshToken=localStorage.getItem('jfm_refresh');expiresAt=Number(localStorage.getItem('jfm_exp')||0)}
function invalidateAccessToken(){token=null;expiresAt=0;localStorage.removeItem('jfm_token');localStorage.setItem('jfm_exp','0')}
function clearSpotifySession(){invalidateAccessToken();refreshToken=null;localStorage.removeItem('jfm_refresh')}
async function ensure(){if(token&&Date.now()<expiresAt)return token;if(!refreshToken)return null;if(tokenRefreshPromise)return tokenRefreshPromise;const id=spotifyClientId||localStorage.getItem('jfm_client_id');if(!id)return null;tokenRefreshCount++;tokenRefreshPromise=(async()=>{const body=new URLSearchParams({grant_type:'refresh_token',refresh_token:refreshToken,client_id:id}),r=await timedFetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok){let code='';try{code=(await r.json())?.error||''}catch{}if(r.status===400||r.status===401)clearSpotifySession();throw Error(code==='invalid_grant'?'Spotify-sessie is verlopen. Koppel Spotify opnieuw.':`Spotify-token vernieuwen mislukt (${r.status}).`)}saveToken(await r.json());return token})().finally(()=>{tokenRefreshPromise=null});return tokenRefreshPromise}
async function api(path,opt={},retry401=true){const t=await ensure();if(!t)throw Error('Spotify is niet gekoppeld.');const headers={...(opt.headers||{}),Authorization:`Bearer ${t}`},body=opt.body&&typeof opt.body!=='string'?JSON.stringify(opt.body):opt.body;if(opt.body&&typeof opt.body!=='string')headers['Content-Type']='application/json';const r=await timedFetch(API+path,{...opt,body,headers});if(r.status===401&&retry401&&refreshToken){invalidateAccessToken();await ensure();return api(path,opt,false)}if(r.status===204)return null;if(r.status===429){const wait=Math.max(1,Number(r.headers?.get?.('Retry-After'))||1);throw Error(`Spotify vraagt ons even rustiger aan te doen. Probeer over ${wait} sec opnieuw.`)}if(!r.ok){let m=`Spotify fout ${r.status}`;try{m=(await r.json())?.error?.message||m}catch{}throw Error(m)}return r.json()}
window.JFMAuth={version:'auth-v2-single-flight-timeout',ensure,invalidateAccessToken,clearSpotifySession,get state(){return{hasAccessToken:!!token,hasRefreshToken:!!refreshToken,expiresAt,refreshing:!!tokenRefreshPromise,refreshCount:tokenRefreshCount}}};
function talkPlan(){return[{label:'Weinig',min:6,max:9},{label:'Normaal',min:3,max:5},{label:'Radio',min:2,max:4},{label:'Veel',min:1,max:3}][Number($('talk').value)]}
function scheduleTalk(){const x=talkPlan();nextTalkAt=Math.floor(Math.random()*(x.max-x.min+1))+x.min;tracksSinceTalk=0}
function updateTalkLabel(){$('talkValue').textContent=talkPlan().label}
function setMode(mode,save=true){settings.mode=MODES[mode]?mode:'normal';document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===settings.mode));$('modeLabel').textContent=MODES[settings.mode].label;$('modeMini').textContent=MODES[settings.mode].label;if(save)saveSettings()}
function trackObj(t){return{id:t.id,uri:t.uri,name:t.name,artists:(t.artists||[]).map(a=>a.name),album:t.album?.name||'',release:t.album?.release_date||'',image:t.album?.images?.[1]?.url||t.album?.images?.[0]?.url||'',url:t.external_urls?.spotify||'',duration:t.duration_ms||0}}
function parsePlaylist(v){v=(v||'').trim();const m=v.match(/playlist[/:]([A-Za-z0-9]+)/);return m?m[1]:(/^[A-Za-z0-9]+$/.test(v)?v:null)}
function skipMap(){return JSON.parse(localStorage.getItem('jfm_skips')||'{}')}
function recordSkip(id){const m=skipMap();m[id]=(m[id]||0)+1;localStorage.setItem('jfm_skips',JSON.stringify(m))}
async function buildSet(){saveSettings();$('queueInfo').textContent='Radioset wordt gemaakt…';const src=$('source').value;let tracks=[];if(src==='top'){for(const range of ['short_term','medium_term','long_term']){const d=await api(`/me/top/tracks?limit=40&time_range=${range}`);tracks.push(...(d.items||[]))}}else if(src==='recent'){const d=await api('/me/player/recently-played?limit=50');tracks=(d.items||[]).map(x=>x.track)}else if(src==='saved'){let off=0;while(off<150){const d=await api(`/me/tracks?limit=50&offset=${off}`);tracks.push(...(d.items||[]).map(x=>x.track));if(!d.next)break;off+=50}}else{const id=parsePlaylist($('playlist').value);if(!id)throw Error('Plak een geldige Spotify playlist-link of ID.');let off=0;while(off<150){const d=await api(`/playlists/${id}/items?limit=50&offset=${off}`);tracks.push(...(d.items||[]).map(x=>x.item).filter(Boolean));if(!d.next)break;off+=50}}tracks=[...new Map(tracks.filter(Boolean).map(t=>[t.id,t])).values()];if(settings.mode==='throwback'){const old=tracks.filter(t=>Number((t.album?.release_date||'9999').slice(0,4))<=2016);if(old.length>=8)tracks=old}const skips=skipMap();tracks.sort((a,b)=>(skips[a.id]||0)-(skips[b.id]||0)+(Math.random()-.5)*2);queue=tracks.slice(0,50).map(trackObj);$('queueInfo').textContent=`${queue.length} tracks klaar · ${MODES[settings.mode].label}.`;return queue}
async function startRadio(){if(!queue.length)await buildSet();if(!queue.length)throw Error('Ik kon geen tracks voor de radioset vinden.');try{await api('/me/player/play',{method:'PUT',body:{uris:queue.slice(0,30).map(x=>x.uri)}})}catch(e){if(/device/i.test(e.message)){alert('Open Spotify kort, speel één nummer af en kom daarna terug naar Josh FM.');return}throw e}session=[];renderHistory();scheduleTalk();if($('jingles').checked)await speakText('Josh FM. Jouw muziek, jouw radioshow.',true).catch(()=>{});await refresh();startPolling()}
async function control(k){if(k==='next'){if(playback?.item?.id)recordSkip(playback.item.id);await api('/me/player/next',{method:'POST'})}if(k==='prev')await api('/me/player/previous',{method:'POST'});if(k==='play')await api(playback?.is_playing?'/me/player/pause':'/me/player/play',{method:'PUT'});setTimeout(()=>refresh().catch(()=>{}),500)}
async function refresh(){const d=await api('/me/player');if(!d?.item)return;playback=d;renderPlayback(d);const id=d.item.id;if(lastTrackId&&id!==lastTrackId){const ended=session.find(x=>x.id===lastTrackId)||null;if(!session.some(x=>x.id===id)){session.unshift(trackObj(d.item));session=session.slice(0,12);renderHistory()}tracksSinceTalk++;if(tracksSinceTalk>=nextTalkAt&&!djBusy){if(skipNextTalk){skipNextTalk=false;scheduleTalk()}else{await djBreak(ended);scheduleTalk()}}}else if(!lastTrackId&&!session.some(x=>x.id===id)){session.unshift(trackObj(d.item));renderHistory()}lastTrackId=id}
function renderPlayback(d){const t=d.item;$('title').textContent=t.name;$('artist').textContent=(t.artists||[]).map(a=>a.name).join(', ');$('barFill').style.width=Math.min(100,(d.progress_ms||0)/(t.duration_ms||1)*100)+'%';$('elapsed').textContent=fmt(d.progress_ms||0);$('duration').textContent=fmt(t.duration_ms||0);$('play').textContent=d.is_playing?'❚❚':'▶';const img=t.album?.images?.[0]?.url;$('artImg').classList.toggle('hidden',!img);$('artFallback').classList.toggle('hidden',!!img);if(img)$('artImg').src=img;$('spotifyLink').href=t.external_urls?.spotify||'#'}
function fmt(ms){const s=Math.floor(ms/1000),m=Math.floor(s/60);return`${m}:${String(s%60).padStart(2,'0')}`}
function startPolling(){clearInterval(poll);poll=setInterval(()=>refresh().catch(console.warn),5000)}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))}
function renderHistory(){$('sessionCount').textContent=`${session.length} track${session.length===1?'':'s'}`;$('history').innerHTML=session.length?session.slice(0,6).map(t=>`<div class="hist">${t.image?`<img src="${esc(t.image)}">`:''}<div><b>${esc(t.name)}</b><span>${esc(t.artists.join(', '))}</span></div></div>`).join(''):'<p class="muted">Nog geen tracks in deze sessie.</p>'}
async function getFact(track){if(!$('facts').checked||!track)return null;try{const r=await timedFetch('/api/fact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({track})},7000);if(r.ok){const d=await r.json();if(d?.text)return{text:d.text,source:d.source||'muziekdata',url:d.url||''}}}catch{}if(track.album&&track.release){const year=track.release.slice(0,4);return{text:`Het nummer staat op ${track.album}${year?`, uit ${year}`:''}.`,source:'Spotify metadata',url:track.url||''}}return null}
async function getWeather(){if(!$('weatherMention').checked)return null;if(weatherCache&&Date.now()-weatherCache.at<20*60*1000)return weatherCache.data;return new Promise(resolve=>{if(!navigator.geolocation)return resolve(null);navigator.geolocation.getCurrentPosition(async p=>{try{const{latitude,longitude}=p.coords,r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current=temperature_2m,weather_code&timezone=auto`),d=await r.json(),temp=Math.round(d.current?.temperature_2m),data=Number.isFinite(temp)?{temperature:temp,code:d.current?.weather_code}:null;weatherCache={at:Date.now(),data};resolve(data)}catch{resolve(null)}},()=>resolve(null),{timeout:5000,maximumAge:900000})})}
function weatherText(w){if(!w)return'';const c=w.code;let x='';if(c===0)x='helder';else if(c<=3)x='bewolkt';else if(c<=48)x='mistig';else if(c<=67)x='regenachtig';else if(c<=77)x='winters';else if(c<=82)x='met buien';else if(c>=95)x='onweersachtig';return`${w.temperature} graden${x?' en '+x:''}`}
async function djBreak(track=null,manual=false){if(djBusy)return;djBusy=true;try{const wasPlaying=!!playback?.is_playing;if(wasPlaying)await api('/me/player/pause',{method:'PUT'}).catch(()=>{});const target=track||(playback?.item?trackObj(playback.item):null),[fact,weather]=await Promise.all([getFact(target),getWeather()]),text=await makeDJScript(target,fact,weather,manual);$('djText').textContent=text;if(fact){$('factSource').classList.remove('hidden');$('factSource').innerHTML=`Feitenbron: ${fact.url?`<a href="${esc(fact.url)}" target="_blank">${esc(fact.source)}</a>`:esc(fact.source)}`}else $('factSource').classList.add('hidden');if($('jingles').checked&&Math.random()<.25&&!manual)await speakText('Josh FM.',true);await speakText(text,false);if(wasPlaying)await api('/me/player/play',{method:'PUT'}).catch(()=>{})}finally{djBusy=false}}
async function makeDJScript(track,fact,weather,manual){const payload={track,fact:fact?.text||'',factSource:fact?.source||'',time:$('timeMention').checked?new Date().toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'}):'',weather:weatherText(weather),mode:MODES[settings.mode],manual,session:session.slice(0,5).map(x=>({name:x.name,artists:x.artists,release:x.release}))};try{const r=await timedFetch('/api/dj',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)},14000);if(r.ok){const d=await r.json();if(d.text)return d.text}}catch{}return fallbackScript(payload)}
function fallbackScript(p){const b=[];if(p.track)b.push(`Dat was ${p.track.name} van ${p.track.artists.join(' en ')}.`);else b.push('Je luistert naar Josh FM.');if(p.fact&&Math.random()<.85)b.push('Klein feitje: '+p.fact.replace(/\s+/g,' ').slice(0,220));if(p.time&&Math.random()<.45)b.push(`Het is ${p.time}.`);if(p.weather&&Math.random()<.35)b.push(`Buiten is het ongeveer ${p.weather}.`);const tails={normal:['We gaan door.','Tijd voor de volgende.','Nog eentje voor je.'],morning:['Zo komen we de ochtend wel door.','We houden de vaart erin.'],chill:['We houden het rustig.','We blijven nog even in deze sfeer.'],party:['Genoeg gepraat. Door.','Oké, volume omhoog.'],throwback:['En we blijven nog even terug in de tijd.','Nog eentje uit de archieven.'],late:['Geen haast. We gaan rustig verder.','Nog eentje voor dit uur.']};b.push(tails[settings.mode][Math.floor(Math.random()*tails[settings.mode].length)]);return b.join(' ')}
async function searchSpotify(){const q=$('searchInput').value.trim();if(!q)return;const d=await api('/search?type=track&limit=8&q='+encodeURIComponent(q));const items=d.tracks?.items||[];$('searchResults').innerHTML=items.length?items.map(t=>`<button class="result" data-uri="${esc(t.uri)}"><img src="${esc(t.album?.images?.[2]?.url||t.album?.images?.[0]?.url||'')}"><span><b>${esc(t.name)}</b><small>${esc(t.artists.map(a=>a.name).join(', '))}</small></span><em>+</em></button>`).join(''):'<p class="muted">Geen resultaten.</p>';document.querySelectorAll('.result').forEach(b=>b.onclick=async()=>{await api('/me/player/queue?uri='+encodeURIComponent(b.dataset.uri),{method:'POST'});b.querySelector('em').textContent='✓'})}
function setConnected(ok){$('status').textContent=ok?'Spotify gekoppeld':'offline';$('status').classList.toggle('on',ok);$('status').classList.toggle('off',!ok);['prev','play','next','start','djNow','skipTalk','searchBtn','rebuild'].forEach(id=>$(id).disabled=!ok);$('setup').classList.toggle('hidden',ok);$('logout').classList.toggle('hidden',!ok)}
function logout(){['jfm_token','jfm_refresh','jfm_exp'].forEach(k=>localStorage.removeItem(k));token=refreshToken=null;expiresAt=0;clearInterval(poll);setConnected(false)}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.tabpane').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('tab-'+b.dataset.tab).classList.add('active')});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('talk').oninput=()=>{updateTalkLabel();saveSettings();scheduleTalk()};['facts','timeMention','weatherMention','jingles'].forEach(id=>$(id).onchange=saveSettings);$('voiceMode').onchange=saveSettings;$('source').onchange=()=>{$('playlist').classList.toggle('hidden',$('source').value!=='playlist');queue=[];saveSettings()};$('connect').onclick=()=>connect().catch(e=>alert(e.message));$('start').onclick=()=>startRadio().catch(e=>alert(e.message));$('rebuild').onclick=()=>buildSet().catch(e=>alert(e.message));$('prev').onclick=()=>control('prev').catch(e=>alert(e.message));$('play').onclick=()=>control('play').catch(e=>alert(e.message));$('next').onclick=()=>control('next').catch(e=>alert(e.message));$('djNow').onclick=()=>djBreak(null,true).catch(e=>alert(e.message));$('skipTalk').onclick=()=>{skipNextTalk=true;$('skipTalk').querySelector('span').textContent='Volgende DJ-break wordt overgeslagen'};$('searchBtn').onclick=()=>searchSpotify().catch(e=>alert(e.message));$('searchInput').onkeydown=e=>{if(e.key==='Enter')searchSpotify().catch(x=>alert(x.message))};$('testVoice').onclick=()=>speakText('Dit is Josh FM. Je luistert naar jouw persoonlijke Nederlandse radioshow.');$('logout').onclick=logout;$('clearHistory').onclick=()=>{localStorage.removeItem('jfm_skips');session=[];renderHistory();alert('Lokale Josh FM-historie is gewist.')};
async function boot(){loadSettings();await loadPublicConfig();const tick=()=>$('clock').textContent=new Date().toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'});tick();setInterval(tick,1000);try{await callback()}catch(e){alert(e.message)}const ok=!!(await ensure());setConnected(ok);if(ok){refresh().catch(()=>{});startPolling()}if('speechSynthesis'in window){speechSynthesis.getVoices();speechSynthesis.onvoiceschanged=()=>speechSynthesis.getVoices()}}
boot();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
