(()=>{
'use strict';
const $=id=>document.getElementById(id),KEY='mair_build7',ANN='mair_request_announcements_v1';
const defaults={dj:'mix',rotation:60,liveContext:true,personal:true,requestPriority:'balanced'};
let prefs={...defaults,...read()},pendingRequest=null,previewToken=0;
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}}
function sync(){if(window.MAIR_PUBLIC_DJ_ENABLED===false)return;const live=window.MAIRLiveContext,profiles=window.MAIRDJProfiles;if(prefs.dj==='mix'){live?.setRotationMinutes?.(prefs.rotation);live?.setMode?.('show')}else{profiles?.select?.(prefs.dj);live?.setMode?.('fixed')}const w=$('weatherMention'),t=$('timeMention');if(w)w.checked=!!prefs.liveContext;if(t)t.checked=!!prefs.liveContext}
function save(){try{localStorage.setItem(KEY,JSON.stringify(prefs))}catch{};sync();document.dispatchEvent(new CustomEvent('mair:prefs',{detail:{...prefs}}))}
function scriptLoaded(src){const wanted=new URL(src,location.href).pathname;return[...document.scripts].some(s=>{try{return new URL(s.src,location.href).pathname===wanted}catch{return false}})}
function loadScript(id,src){if(document.getElementById(id)||scriptLoaded(src))return;const s=document.createElement('script');s.id=id;s.src=src;s.async=false;document.body.appendChild(s)}
function loadMairRuntime(){loadScript('mair-location-js','./mair-location.js');loadScript('mair-dj-memory-js','./mair-dj-memory.js');loadScript('mair-imaging-js','./mair-imaging.js');loadScript('mair-live-news-js','./mair-live-news.js');loadScript('mair-voice-lab-js','./mair-voice-lab.js');loadScript('mair-soak-monitor-js','./mair-soak-monitor.js');loadScript('mair-station-director-js','./mair-station-director.js');loadScript('mair-dj-persona-js','./mair-dj-persona.js');loadScript('mair-pwa-polish-js','./mair-pwa-polish.js');loadScript('mair-stations-v2-js','./mair-stations-v2.js?v='+(window.JFM_ASSET_VERSION||'81'));loadScript('mair-profile-js','./mair-profile.js?v='+(window.JFM_ASSET_VERSION||'81'));loadScript('mair-background-guard-js','./mair-background-guard.js?v='+(window.JFM_ASSET_VERSION||'81'))}
function ensureCompat(){let box=$('mairLegacyCompat');if(!box){box=document.createElement('div');box.id='mairLegacyCompat';box.className='hidden';box.setAttribute('aria-hidden','true');document.body.appendChild(box)}const specs=[['sessionCount','span'],['history','div'],['nextUp','span'],['directorQueue','div'],['installHint','p'],['discoveryValue','span']];for(const[id,tag]of specs)if(!$(id)){const e=document.createElement(tag);e.id=id;box.appendChild(e)}}
function ensureRequestSheet(){if($('b7RequestSheet'))return;const req=document.createElement('div');req.className='mair-request-sheet hidden';req.id='b7RequestSheet';req.innerHTML='<div class="mair-sheet-card"><div class="row between"><div><div class="kicker">VERZOEK</div><h3 id="b7ReqTitle">Toevoegen aan MAIR?</h3></div><button id="b7ReqClose" class="circle">×</button></div><p class="muted">Je verzoek krijgt voorrang in de programmering.</p><button id="b7ReqConfirm" class="cta">Zet in de uitzending</button></div>';document.body.appendChild(req);$('b7ReqClose').onclick=()=>closeRequest();$('b7ReqConfirm').onclick=confirmRequest;req.onclick=e=>{if(e.target===req)closeRequest()}}
function rollbackPreview(detail,token){setTimeout(()=>{if(token!==previewToken)return;try{const s=window.JFMRadioSuite?.state?.();if(s&&Number(s.requests)>0){s.requests--;window.JFMRadioSuite.save?.(s);if($('statRequests'))$('statRequests').textContent=String(s.requests)}}catch{}try{const id=String(detail?.uri||'').split(':').pop(),m=JSON.parse(localStorage.getItem('jfm_director_memory_v1')||'{}');if(id&&m?.requests?.[id]>0){m.requests[id]--;if(m.requests[id]<=0)delete m.requests[id];localStorage.setItem('jfm_director_memory_v1',JSON.stringify(m))}}catch{}},260)}
function openRequest(detail={}){ensureRequestSheet();const s=$('b7RequestSheet');if(!s)return;pendingRequest=detail;const token=++previewToken;$('b7ReqTitle').textContent=detail.name?`${detail.name} aanvragen?`:'Nummer aanvragen?';s.classList.remove('hidden');rollbackPreview(detail,token)}
function closeRequest(){pendingRequest=null;$('b7RequestSheet')?.classList.add('hidden')}
function rememberRequest(uri){if(!uri)return;try{let a=JSON.parse(localStorage.getItem(ANN)||'[]');if(!Array.isArray(a))a=[];a=a.filter(x=>x&&Date.now()-Number(x.at||0)<6*60*60*1000&&x.uri!==uri);a.unshift({uri,at:Date.now()});localStorage.setItem(ANN,JSON.stringify(a.slice(0,12)))}catch{}}
async function confirmRequest(){const d=pendingRequest,b=d?.button;if(!b)return closeRequest();rememberRequest(d.uri);closeRequest();if(window.JFMRequests?.add){try{const added=await window.JFMRequests.add(d.uri,b);if(added){try{window.dispatchEvent(new CustomEvent('mair:request-confirmed',{detail:{uri:d.uri,track:added.track||null}}))}catch{};toast('Verzoek staat in de MAIR-planning')}}catch(e){const q=$('queueInfo');if(q){q.textContent='Request toevoegen mislukt: '+String(e?.message||e);q.style.color='#ffb4b4'}}return}b.dataset.mairConfirmed='1';b.click();setTimeout(()=>{delete b.dataset.mairConfirmed},0);toast('Verzoek staat in de MAIR-planning')}
function requestCapture(e){const b=e.target.closest?.('.result');if(!b?.dataset?.uri||b.dataset.mairConfirmed==='1')return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openRequest({uri:b.dataset.uri,name:b.querySelector('b')?.textContent?.trim()||'Dit nummer',artists:b.querySelector('small')?.textContent?.trim()||'',button:b})}
function requestConfirmCapture(e){if(!e.target.closest?.('#b7ReqConfirm'))return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();confirmRequest()}
function toast(text){let t=$('b7Toast');if(!t){t=document.createElement('div');t.id='b7Toast';t.className='mair-toast';document.body.appendChild(t)}t.textContent=text;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),1800)}
function install(){const djOn=window.MAIR_DJ_ENABLED===true;window.MAIR_PUBLIC_DJ_ENABLED=djOn;document.documentElement.dataset.mairPublicDj=djOn?'on':'off';ensureCompat();ensureRequestSheet();loadMairRuntime();setTimeout(sync,50)}
document.addEventListener('click',requestCapture,true);document.addEventListener('click',requestConfirmCapture,true);document.addEventListener('mair:request-preview',e=>openRequest(e.detail));document.addEventListener('mair:prefs',sync);window.MAIRRuntimePrefs={version:'mair-runtime-prefs-v5-profile',get:()=>({...prefs}),set(next={}){prefs={...prefs,...next};save();return{...prefs}},setRequest:openRequest,sync};window.MAIR_BUILD7=window.MAIRRuntimePrefs;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
