const voiceSelect=document.getElementById('voiceMode');
if(voiceSelect){const previous=voiceSelect.value||'auto';voiceSelect.innerHTML=`<option value="auto">Automatisch — beste gratis stem</option><option value="elevenlabs">ElevenLabs — radio DJ</option><option value="openai">OpenAI — AI-stem</option><option value="device">iPhone-stem</option>`;voiceSelect.value=['auto','elevenlabs','openai','device'].includes(previous)?previous:'auto'}
let selectedElevenVoice=localStorage.getItem('jfm_eleven_voice')||'',elevenVoiceSelect=null;
async function loadBestFreeVoices(){const info=document.getElementById('voiceInfo');if(!voiceSelect)return;try{const r=await fetch('/api/elevenlabs-voices');if(!r.ok)return;const d=await r.json(),voices=d.voices||[];if(!voices.length)return;elevenVoiceSelect=document.createElement('select');elevenVoiceSelect.id='elevenVoice';elevenVoiceSelect.style.marginTop='10px';elevenVoiceSelect.innerHTML=voices.map((v,i)=>`<option value="${v.voice_id}">${i===0?'★ ':''}${v.name}${[v.gender,v.age,v.accent,v.use_case].filter(Boolean).length?' — '+[v.gender,v.age,v.accent,v.use_case].filter(Boolean).join(' · '):''}</option>`).join('');if(selectedElevenVoice&&voices.some(v=>v.voice_id===selectedElevenVoice))elevenVoiceSelect.value=selectedElevenVoice;else{selectedElevenVoice=voices[0].voice_id;localStorage.setItem('jfm_eleven_voice',selectedElevenVoice)}elevenVoiceSelect.onchange=()=>{selectedElevenVoice=elevenVoiceSelect.value;localStorage.setItem('jfm_eleven_voice',selectedElevenVoice);const chosen=voices.find(v=>v.voice_id===selectedElevenVoice);if(info)info.textContent=`Gekozen gratis ElevenLabs-stem: ${chosen?.name||'stem'}`};voiceSelect.insertAdjacentElement('afterend',elevenVoiceSelect);const chosen=voices.find(v=>v.voice_id===selectedElevenVoice)||voices[0];if(info)info.textContent=`Josh FM toont alleen de ${voices.length} best passende gratis ElevenLabs-stemmen. Standaard: ${chosen.name}.`}catch{}}loadBestFreeVoices();

// iOS can suspend a freshly created Audio element while Spotify/app focus changes.
// Reuse one unlocked player and never report success until sound really started.
const djAudio=new Audio();djAudio.preload='auto';djAudio.playsInline=true;let audioUnlocked=false;
function unlockAudio(){if(audioUnlocked)return;audioUnlocked=true;try{djAudio.muted=true;const p=djAudio.play();if(p?.catch)p.catch(()=>{}).finally(()=>{djAudio.pause();djAudio.currentTime=0;djAudio.muted=false})}catch{djAudio.muted=false}}
document.addEventListener('pointerdown',unlockAudio,{capture:true,once:true});document.addEventListener('touchstart',unlockAudio,{capture:true,once:true});
async function playAudioResponse(response,label,info){const contentType=response.headers.get('content-type')||'';if(!response.ok||!contentType.includes('audio'))return false;const blob=await response.blob();if(!blob.size)return false;const url=URL.createObjectURL(blob);try{djAudio.pause();djAudio.src=url;djAudio.load();const started=new Promise((resolve,reject)=>{const ok=()=>{cleanup();resolve()};const bad=()=>{cleanup();reject(Error('audio kon niet starten'))};const cleanup=()=>{djAudio.removeEventListener('playing',ok);djAudio.removeEventListener('error',bad)};djAudio.addEventListener('playing',ok,{once:true});djAudio.addEventListener('error',bad,{once:true});setTimeout(bad,5000)});const playPromise=djAudio.play();if(playPromise)await playPromise;await started;if(info)info.textContent=`${label} actief ✓`;await new Promise(resolve=>{const done=()=>{djAudio.removeEventListener('ended',done);djAudio.removeEventListener('error',done);resolve()};djAudio.addEventListener('ended',done,{once:true});djAudio.addEventListener('error',done,{once:true})});return true}catch(e){if(info)info.textContent=`${label} kon niet afspelen`;return false}finally{djAudio.removeAttribute('src');djAudio.load();URL.revokeObjectURL(url)}}
async function providerError(response){let message=`HTTP ${response.status}`;try{const d=await response.clone().json();let detail=d.detail||'';if(typeof detail==='string'&&detail.length>220)detail=detail.slice(0,220)+'…';message=[d.error,detail,d.code].filter(Boolean).join(' · ')||message}catch{}return message}
async function tryElevenLabs(text,jingle,info){if(info)info.textContent='ElevenLabs-stem wordt geladen…';try{const r=await fetch('/api/tts-elevenlabs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,jingle,voiceId:selectedElevenVoice||undefined})});if(await playAudioResponse(r,'ElevenLabs',info))return{ok:true};return{ok:false,error:await providerError(r)}}catch(e){return{ok:false,error:String(e?.message||e)}}}
async function tryOpenAI(text,jingle,info){if(info)info.textContent='OpenAI-stem wordt geladen…';try{const r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,jingle})});if(await playAudioResponse(r,'OpenAI',info))return{ok:true};return{ok:false,error:await providerError(r)}}catch(e){return{ok:false,error:String(e?.message||e)}}}
async function speakDevice(text,jingle,info){if(info)info.textContent='Nederlandse iPhone-stem actief';return new Promise(resolve=>{if(!('speechSynthesis'in window))return resolve(false);speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='nl-NL';u.rate=jingle?1.03:.96;u.pitch=jingle?1.02:.94;const voices=speechSynthesis.getVoices(),v=voices.find(x=>x.lang?.toLowerCase()==='nl-nl')||voices.find(x=>x.lang?.toLowerCase().startsWith('nl'))||null;if(v)u.voice=v;let done=false;const finish=ok=>{if(done)return;done=true;resolve(ok)};u.onstart=()=>{};u.onend=()=>finish(true);u.onerror=()=>finish(false);speechSynthesis.speak(u);setTimeout(()=>finish(false),30000)})}
window.speakText=async function(text,jingle=false){const mode=document.getElementById('voiceMode')?.value||'auto',info=document.getElementById('voiceInfo'),errors=[];if(mode==='auto'||mode==='elevenlabs'){const result=await tryElevenLabs(text,jingle,info);if(result.ok)return true;errors.push('ElevenLabs: '+result.error);if(mode==='elevenlabs'){if(info)info.textContent='ElevenLabs niet hoorbaar — iPhone fallback';return speakDevice(text,jingle,info)}}if(mode==='auto'||mode==='openai'){const result=await tryOpenAI(text,jingle,info);if(result.ok)return true;errors.push('OpenAI: '+result.error);if(mode==='openai'){if(info)info.textContent='OpenAI niet hoorbaar — iPhone fallback';return speakDevice(text,jingle,info)}}if(mode==='device')return speakDevice(text,jingle,info);if(info)info.textContent='AI-stem niet hoorbaar; iPhone-fallback.';return speakDevice(text,jingle,info)};
const testButton=document.getElementById('testVoice');if(testButton)testButton.onclick=()=>window.speakText('Dit is Josh FM. Je luistert naar jouw persoonlijke Nederlandse radioshow.');
