const voiceSelect=document.getElementById('voiceMode');
const info=document.getElementById('voiceInfo');
const KOKORO_MODEL='onnx-community/Kokoro-82M-v1.0-ONNX';
const KOKORO_VERSION='kokoro-en-v1-20260811';
let selectedMode=localStorage.getItem('jfm_voice_mode')||'kokoro';
if(voiceSelect){
  voiceSelect.innerHTML='<option value="kokoro">Kokoro — natural English AI DJ (free)</option><option value="device">iPhone English voice — fallback</option>';
  if(!['kokoro','device'].includes(selectedMode))selectedMode='kokoro';
  voiceSelect.value=selectedMode;localStorage.setItem('jfm_voice_mode',selectedMode);
  voiceSelect.onchange=()=>{selectedMode=voiceSelect.value;localStorage.setItem('jfm_voice_mode',selectedMode);if(info)info.textContent=selectedMode==='kokoro'?'Kokoro selected — free and local.':'iPhone English voice selected.'};
}
const AC=window.AudioContext||window.webkitAudioContext;let djContext=AC?new AC():null,djGain=null,audioUnlocked=false;if(djContext){djGain=djContext.createGain();djGain.gain.value=1;djGain.connect(djContext.destination)}
async function unlockAudio(){if(audioUnlocked)return;audioUnlocked=true;try{if(djContext?.state==='suspended')await djContext.resume();const b=djContext?.createBuffer(1,1,24000),s=djContext?.createBufferSource();if(s&&b){s.buffer=b;s.connect(djGain);s.start(0)}}catch{}}
document.addEventListener('pointerdown',unlockAudio,{capture:true,once:true});document.addEventListener('touchstart',unlockAudio,{capture:true,once:true});
function bestEnglishVoice(){const voices=speechSynthesis.getVoices();const preferred=['Samantha','Daniel','Karen','Moira','Tessa','Alex'];for(const name of preferred){const v=voices.find(x=>x.name===name&&x.lang?.toLowerCase().startsWith('en'));if(v)return v}return voices.find(x=>x.lang?.toLowerCase()==='en-us')||voices.find(x=>x.lang?.toLowerCase()==='en-gb')||voices.find(x=>x.lang?.toLowerCase().startsWith('en'))||null}
async function speakDevice(text,jingle=false){if(!('speechSynthesis'in window))return false;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=jingle?1.03:.97;u.pitch=jingle?1:.94;u.volume=1;const v=bestEnglishVoice();if(v)u.voice=v;if(info)info.textContent=`iPhone fallback — ${v?.name||'English voice'} ✓`;return await new Promise(resolve=>{let done=false;const finish=ok=>{if(done)return;done=true;resolve(ok)};u.onend=()=>finish(true);u.onerror=()=>finish(false);speechSynthesis.speak(u);setTimeout(()=>finish(false),30000)})}catch{return false}}
let kokoro=null,kokoroLoading=null,kokoroFailed='';
async function loadKokoro(){if(kokoro)return kokoro;if(kokoroLoading)return kokoroLoading;kokoroLoading=(async()=>{try{if(info)info.textContent='Loading natural English DJ voice… first time can take a while.';const mod=await import('https://cdn.jsdelivr.net/npm/kokoro-js@1.2.1/+esm');const opts={dtype:'q8',device:'wasm'};kokoro=await mod.KokoroTTS.from_pretrained(KOKORO_MODEL,opts);if(info)info.textContent='Kokoro English AI DJ ready ✓';return kokoro}catch(e){kokoroFailed=String(e?.message||e).slice(0,180);kokoroLoading=null;throw e}})();return kokoroLoading}
function audioToBuffer(audio){const raw=audio?.audio??audio?.data??audio;if(raw instanceof Float32Array)return raw;if(ArrayBuffer.isView(raw))return new Float32Array(raw.buffer,raw.byteOffset,Math.floor(raw.byteLength/4));if(Array.isArray(raw))return Float32Array.from(raw);return null}
async function playPCM(samples,sampleRate=24000){if(!samples?.length||!djContext)return false;try{if(djContext.state==='suspended')await djContext.resume();const b=djContext.createBuffer(1,samples.length,sampleRate);b.copyToChannel(samples,0);const s=djContext.createBufferSource();s.buffer=b;s.connect(djGain);await new Promise((resolve,reject)=>{s.onended=resolve;try{s.start(0)}catch(e){reject(e)}});return true}catch{return false}}
async function speakKokoro(text,jingle=false){try{const tts=await loadKokoro();const voices=tts.list_voices?.()||{};const names=Array.isArray(voices)?voices.map(v=>v.id||v.name||v):Object.keys(voices);const preferred=['am_michael','am_adam','bm_george','bf_emma','af_heart'];const voice=preferred.find(v=>names.includes(v))||names[0]||'af_heart';if(info)info.textContent=`Kokoro generating ${voice}…`;const audio=await tts.generate(text,{voice,speed:jingle?1.04:1.0});const samples=audioToBuffer(audio);const rate=audio?.sampling_rate||audio?.sample_rate||24000;if(!samples?.length)throw new Error('Kokoro returned no PCM audio');const ok=await playPCM(samples,rate);if(!ok)throw new Error('Kokoro audio could not play');if(info)info.textContent=`Kokoro English AI DJ — ${voice} ✓`;return true}catch(e){kokoroFailed=String(e?.message||e).slice(0,180);if(info)info.textContent=`Kokoro unavailable (${kokoroFailed}). Using iPhone fallback.`;return false}}
window.prepareSpeech=async function(text,jingle=false){if((voiceSelect?.value||selectedMode)!=='kokoro')return false;try{await loadKokoro();return true}catch{return false}};
window.speakText=async function(text,jingle=false){await unlockAudio();const mode=voiceSelect?.value||selectedMode;if(mode==='kokoro'&&await speakKokoro(text,jingle))return true;return speakDevice(text,jingle)};
window.JFMDJAudio={context:djContext,unlock:unlockAudio,getErrors:()=>kokoroFailed?[kokoroFailed]:[],version:KOKORO_VERSION};
const testButton=document.getElementById('testVoice');if(testButton)testButton.onclick=()=>window.speakText("This is Josh FM. You're listening to your personal radio station. More music is coming up next.");