const voiceSelect=document.getElementById('voiceMode');
const info=document.getElementById('voiceInfo');
if(voiceSelect){
  let previous=localStorage.getItem('jfm_voice_mode')||voiceSelect.value||'local';
  if(previous==='device'&&localStorage.getItem('jfm_device_voice_explicit_v2')!=='1')previous='local';
  if(previous==='auto')previous='local';
  voiceSelect.innerHTML=`<option value="local">Lokaal op iPhone — gratis/onbeperkt (test)</option><option value="piper">Piper — gratis Nederlandse DJ</option><option value="elevenlabs">ElevenLabs — radio DJ</option><option value="openai">OpenAI — AI-radiostem</option><option value="device">iPhone-stem (basis)</option>`;
  voiceSelect.value=['local','piper','elevenlabs','openai','device'].includes(previous)?previous:'local';
  localStorage.setItem('jfm_voice_mode',voiceSelect.value);
  voiceSelect.addEventListener('change',async()=>{localStorage.setItem('jfm_voice_mode',voiceSelect.value);if(voiceSelect.value==='device')localStorage.setItem('jfm_device_voice_explicit_v2','1');else localStorage.removeItem('jfm_device_voice_explicit_v2');if(info)info.textContent=`${voiceSelect.options[voiceSelect.selectedIndex].text} geselecteerd.`;if(voiceSelect.value==='local')showLocalStatus()});
}
let selectedElevenVoice=localStorage.getItem('jfm_eleven_voice')||'',elevenVoiceSelect=null,lastErrors=[];
function reason(name,status,detail){const s=status?`HTTP ${status}`:'verbindingsfout';return `${name}: ${s}${detail?` — ${detail}`:''}`}
function setErrors(errors){lastErrors=errors.filter(Boolean);if(info&&lastErrors.length)info.textContent=lastErrors.join(' | ')}
async function readError(r){try{const raw=await r.text();try{const d=JSON.parse(raw);return String(d.detail||d.error||d.message||raw).slice(0,220)}catch{return raw.slice(0,220)}}catch{return''}}
async function showLocalStatus(){if(!info||!window.JFMLocalVoice)return;try{const r=await window.JFMLocalVoice.capabilities();const v=r.voice?`${r.voice.name}${r.voice.local?' · lokaal':''}`:'geen Nederlandse stem';info.textContent=`Lokale test: ${v} · WASM ${r.wasm?'✓':'✕'} · WebGPU ${r.webgpu?'✓':'✕'} · modelcache ${r.cache?'✓':'✕'}.`;}catch(e){info.textContent='Lokale stemtest kon niet worden gecontroleerd: '+String(e?.message||e)}}
async function loadBestFreeVoices(){if(!voiceSelect)return;try{const r=await fetch('/api/elevenlabs-voices');if(!r.ok)return;const d=await r.json(),voices=d.voices||[];if(!voices.length)return;elevenVoiceSelect=document.createElement('select');elevenVoiceSelect.id='elevenVoice';elevenVoiceSelect.style.marginTop='10px';elevenVoiceSelect.innerHTML=voices.map((v,i)=>`<option value="${v.voice_id}">${i===0?'★ ':''}${v.name}${[v.gender,v.age,v.accent,v.use_case].filter(Boolean).length?' — '+[v.gender,v.age,v.accent,v.use_case].filter(Boolean).join(' · '):''}</option>`).join('');if(selectedElevenVoice&&voices.some(v=>v.voice_id===selectedElevenVoice))elevenVoiceSelect.value=selectedElevenVoice;else{selectedElevenVoice=voices[0].voice_id;localStorage.setItem('jfm_eleven_voice',selectedElevenVoice)}elevenVoiceSelect.onchange=()=>{selectedElevenVoice=elevenVoiceSelect.value;localStorage.setItem('jfm_eleven_voice',selectedElevenVoice)};voiceSelect.insertAdjacentElement('afterend',elevenVoiceSelect)}catch{}}
loadBestFreeVoices();
const AC=window.AudioContext||window.webkitAudioContext;let djContext=AC?new AC():null,djGain=null,audioUnlocked=false;const preparedSpeech=new Map();if(djContext){djGain=djContext.createGain();djGain.gain.value=1;djGain.connect(djContext.destination)}
async function unlockAudio(){if(audioUnlocked)return;audioUnlocked=true;try{if(djContext?.state==='suspended')await djContext.resume();const b=djContext?.createBuffer(1,1,22050),s=djContext?.createBufferSource();if(s&&b){s.buffer=b;s.connect(djGain);s.start(0)}}catch{}}
document.addEventListener('pointerdown',unlockAudio,{capture:true,once:true});document.addEventListener('touchstart',unlockAudio,{capture:true,once:true});
async function playBlob(blob,label){if(!blob?.size||!djContext)return false;try{if(djContext.state==='suspended')await djContext.resume();const arr=await blob.arrayBuffer(),buffer=await djContext.decodeAudioData(arr.slice(0)),source=djContext.createBufferSource();source.buffer=buffer;source.connect(djGain);if(info)info.textContent=`${label} actief ✓`;await new Promise((resolve,reject)=>{source.onended=resolve;try{source.start(0)}catch(e){reject(e)}});return true}catch(e){setErrors([reason(label,0,'audio kon niet worden afgespeeld: '+String(e?.message||e).slice(0,150))]);return false}}
async function speakLocal(text,jingle=false){if(!window.JFMLocalVoice){if(info)info.textContent='Lokale stemmodule is niet geladen.';return false}try{const r=await window.JFMLocalVoice.speak(text,{jingle});if(r.ok){if(info)info.textContent=`Lokaal op iPhone actief ✓ · ${r.voice}`;return true}if(info)info.textContent='Lokale iPhone-stem: '+(r.error||'onbekende fout');return false}catch(e){if(info)info.textContent='Lokale iPhone-stem: '+String(e?.message||e);return false}}
async function fetchPiper(text,jingle=false){try{const r=await fetch('/api/tts-piper',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,jingle})});if(!r.ok)return{error:reason('Piper',r.status,await readError(r))};const type=r.headers.get('content-type')||'';if(!type.includes('audio'))return{error:reason('Piper',r.status,'antwoord bevatte geen audio')};const blob=await r.blob();if(!blob.size)return{error:'Piper: leeg audiobestand'};return{blob,label:'Piper'}}catch(e){return{error:reason('Piper',0,String(e?.message||e).slice(0,180))}}}
async function fetchEleven(text,jingle=false){try{const r=await fetch('/api/tts-elevenlabs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,jingle,voiceId:selectedElevenVoice||undefined})});if(!r.ok)return{error:reason('ElevenLabs',r.status,await readError(r))};const type=r.headers.get('content-type')||'';if(!type.includes('audio'))return{error:reason('ElevenLabs',r.status,'antwoord bevatte geen audio')};const blob=await r.blob();if(!blob.size)return{error:'ElevenLabs: leeg audiobestand'};return{blob,label:'ElevenLabs'}}catch(e){return{error:reason('ElevenLabs',0,String(e?.message||e).slice(0,180))}}}
async function fetchOpenAI(text,jingle=false){try{const r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,jingle})});if(!r.ok)return{error:reason('OpenAI stem',r.status,await readError(r))};const type=r.headers.get('content-type')||'';if(!type.includes('audio'))return{error:reason('OpenAI stem',r.status,'antwoord bevatte geen audio')};const blob=await r.blob();if(!blob.size)return{error:'OpenAI stem: leeg audiobestand'};return{blob,label:'OpenAI'}}catch(e){return{error:reason('OpenAI stem',0,String(e?.message||e).slice(0,180))}}}
async function selectedVoice(text,jingle,mode){lastErrors=[];let a;if(mode==='piper'){a=await fetchPiper(text,jingle);if(a.blob)return a;setErrors([a.error]);return null}if(mode==='elevenlabs'){a=await fetchEleven(text,jingle);if(a.blob)return a;setErrors([a.error]);return null}if(mode==='openai'){a=await fetchOpenAI(text,jingle);if(a.blob)return a;setErrors([a.error]);return null}return null}
window.prepareSpeech=async function(text,jingle=false){const key=(jingle?'j:':'s:')+text;if(preparedSpeech.has(key))return true;const mode=document.getElementById('voiceMode')?.value||'local';if(mode==='device')return false;if(mode==='local'){await showLocalStatus();return !!window.JFMLocalVoice?.voice}const pack=await selectedVoice(text,jingle,mode);if(pack?.blob){preparedSpeech.set(key,pack);if(preparedSpeech.size>5)preparedSpeech.delete(preparedSpeech.keys().next().value);return true}return false};
async function speakDevice(text,jingle){if(info)info.textContent='iPhone-basisstem actief — handmatig geselecteerd';return new Promise(resolve=>{if(!('speechSynthesis'in window))return resolve(false);speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='nl-NL';u.rate=jingle?1.03:.96;u.pitch=jingle?1.02:.94;const voices=speechSynthesis.getVoices(),v=voices.find(x=>x.lang?.toLowerCase()==='nl-nl')||voices.find(x=>x.lang?.toLowerCase().startsWith('nl'))||null;if(v)u.voice=v;let done=false;const finish=ok=>{if(done)return;done=true;resolve(ok)};u.onend=()=>finish(true);u.onerror=()=>finish(false);speechSynthesis.speak(u);setTimeout(()=>finish(false),30000)})}
window.speakText=async function(text,jingle=false){const mode=document.getElementById('voiceMode')?.value||'local',key=(jingle?'j:':'s:')+text;try{if(djContext?.state==='suspended')await djContext.resume()}catch{}if(preparedSpeech.has(key)){const pack=preparedSpeech.get(key);preparedSpeech.delete(key);if(await playBlob(pack.blob,pack.label))return true}if(mode==='local')return speakLocal(text,jingle);if(mode==='device')return speakDevice(text,jingle);const pack=await selectedVoice(text,jingle,mode);if(pack?.blob&&await playBlob(pack.blob,pack.label))return true;if(info&&!lastErrors.length)info.textContent='Geselecteerde stem kon niet worden gestart.';return false};
window.JFMDJAudio={context:djContext,unlock:unlockAudio,getErrors:()=>[...lastErrors]};const testButton=document.getElementById('testVoice');if(testButton)testButton.onclick=()=>window.speakText('Dit is Josh FM. Je luistert naar jouw persoonlijke Nederlandse radioshow.');if(voiceSelect?.value==='local')setTimeout(showLocalStatus,900);