// Josh FM Program Director — adaptive programming with Spotify-authoritative upcoming queue
(()=>{
const $=id=>document.getElementById(id),memoryKey='jfm_director_memory';
const memory=()=>{try{return JSON.parse(localStorage.getItem(memoryKey)||'{"plays":{},"likes":{},"requests":{},"discoveryWins":{},"discoveryLosses":{}}')}catch{return{plays:{},likes:{},requests:{},discoveryWins:{},discoveryLosses:{}}}};
const save=m=>localStorage.setItem(memoryKey,JSON.stringify(m));
const artistKey=t=>(t?.artists?.[0]||'').toLowerCase().trim(),yr=t=>Number(String(t?.release||'').slice(0,4))||0;
const isRequest=t=>{if(!t)return false;try{if(window.JFMRequests?.isRequest?.(t))return true}catch{}const m=memory();return!!(m.requests[t.id]||m.requests[t.uri])};
window.jfmDirectorMemory=memory;window.jfmIsRequest=isRequest;
function baseScore(t){const m=memory(),skips=(typeof skipMap==='function'?skipMap():{});let s=Math.random()*2.4-(skips[t.id]||0)*3.4-(m.plays[t.id]||0)*.3+(m.likes[t.id]||0)*4.6+(m.requests[t.id]||m.requests[t.uri]||0)*6.4+(m.discoveryWins[t.id]||0)*3.2-(m.discoveryLosses[t.id]||0)*4.2;try{s+=window.JFMRotation?.score?.(t,[])||0}catch{}return s}
function fitScore(t,out){let s=baseScore(t);const a=artistKey(t),recent=out.slice(-6),last=recent[recent.length-1];try{s+=window.JFMRotation?.score?.(t,out)||0}catch{}if(!last)return s;for(let back=1;back<=recent.length;back++){const prev=recent[recent.length-back];if(a&&a===artistKey(prev))s-=[0,14,10,7,5,3,2][back]||2}const y=yr(t),ly=yr(last);if(y&&ly){const gap=Math.abs(y-ly);if(gap<=6)s+=1.1;else if(gap>25)s-=1.2}const recentDiscovery=recent.slice(-2).some(x=>x?._discovery);if(t._discovery)s+=recentDiscovery?-7:1.6;else if(last?._discovery)s+=2.2;const recentRequests=recent.slice(-3).filter(isRequest).length;if(isRequest(t))s+=recentRequests?-(6+recentRequests*3):2.5;else if(isRequest(last))s+=1.4;return s}
function directWithContext(list,context=[]){let pool=[...list];try{const filtered=pool.filter(t=>!window.JFMRotation?.isHardBlocked?.(t));if(filtered.length>=Math.min(8,pool.length))pool=filtered}catch{}const prefix=(context||[]).filter(Boolean).slice(-8),out=[];while(pool.length){let best=0,bestS=-Infinity,scoring=[...prefix,...out];for(let i=0;i<pool.length;i++){const s=fitScore(pool[i],scoring);if(s>bestS){bestS=s;best=i}}const chosen=pool.splice(best,1)[0];try{window.JFMRotation?.annotate?.(chosen)}catch{}out.push(chosen)}return out}
const direct=list=>directWithContext(list,[]);
function kind(t){try{return window.JFMRotation?.category?.(t)||'Voor jou'}catch{}if(isRequest(t))return'Verzoek';if(t?._discovery)return'Ontdekking';return'Voor jou'}
function why(t){try{return window.JFMRotation?.reason?.(t)||''}catch{return''}}
function baseUpcoming(){const current=playback?.item?.id,idx=(queue||[]).findIndex(t=>t.id===current);if(idx>=0)return(queue||[]).slice(idx+1,idx+7);return(queue||[]).filter(t=>t.id!==current).slice(0,6)}
let upcomingCache=[],upcomingForTrack='',actualQueue=false,syncing=false,lastSync=0,upcomingRevision=0,lastRequestSig='';
function requestSig(){try{return(window.JFMRequests?.list?.()||[]).filter(r=>['planned','armed'].includes(r.status)).map(r=>`${r.track?.uri||r.track?.id||r.uri||''}:${r.status}:${Number(r.remaining||0)}`).join('|')}catch{return''}}
function mapSpotifyTrack(t){if(!t?.id)return null;try{return trackObj(t)}catch{return{id:t.id,uri:t.uri||'',name:t.name||'',artists:(t.artists||[]).map(a=>a?.name||a).filter(Boolean),album:t.album?.name||'',release:t.album?.release_date||'',image:t.album?.images?.[1]?.url||t.album?.images?.[0]?.url||'',url:t.external_urls?.spotify||'',duration:Number(t.duration_ms||0)}}}
function fallbackUpcoming(){const items=baseUpcoming();try{const armed=window.JFMRequests?.list?.().find(r=>r.status==='armed');if(armed?.track?.uri){const t={...armed.track,_request:true},rest=items.filter(x=>x.uri!==t.uri&&x.id!==t.id);return[t,...rest].slice(0,6)}}catch{}return items}
function invalidateUpcoming(reason='manual'){upcomingRevision++;upcomingCache=[];upcomingForTrack='';actualQueue=false;try{window.dispatchEvent(new CustomEvent('jfm:upcoming-invalidated',{detail:{reason,revision:upcomingRevision}}))}catch{}}
function upcoming(){if(window.JFMSpotifyUpcomingTruth)return window.JFMSpotifyUpcomingTruth.items;const current=playback?.item?.id||'';if(actualQueue&&upcomingForTrack===current)return[...upcomingCache];return fallbackUpcoming()}
window.jfmUpcoming=upcoming;
function renderWhy(){const current=playback?.item?trackObj(playback.item):null;if(!current)return;const q=(queue||[]).find(t=>t.id===current.id)||current;let e=$('whyTrack');if(!e){const card=$('title')?.closest('.card');if(!card)return;e=document.createElement('p');e.id='whyTrack';e.className='muted';e.style.marginTop='10px';const next=$('nextUp')?.closest('.nextup');if(next)next.insertAdjacentElement('afterend',e);else card.appendChild(e)}const r=why(q);e.textContent=r?`Waarom deze track? ${r}`:''}
function paintNext(){const box=$('directorQueue');if(!box)return;const items=upcoming();if(!items.length){box.innerHTML='<p class="muted">Start Josh FM om de programmering te zien.</p>';if($('nextUp'))$('nextUp').textContent='—';renderWhy();return}box.innerHTML=items.map((t,i)=>`<div class="director-track"><span class="director-num">${i+1}</span>${t.image?`<img src="${esc(t.image)}" alt="">`:''}<div class="director-meta"><b>${esc(t.name)}</b><span>${esc((t.artists||[]).join(', '))}</span></div><em>${actualQueue?'Spotify':esc(kind(t))}</em></div>`).join('');const n=items[0];if($('nextUp'))$('nextUp').textContent=n?`${n.name} · ${(n.artists||[]).join(', ')}`:'—';renderWhy()}
async function syncSpotifyUpcoming(force=false){if(window.JFMSpotifyUpcomingTruth){const ok=await window.JFMSpotifyUpcomingTruth.sync(force);actualQueue=!!window.JFMSpotifyUpcomingTruth.lastOk;paintNext();return ok}if(syncing||!navigator.onLine)return false;const now=Date.now();if(!force&&now-lastSync<2200)return actualQueue;syncing=true;lastSync=now;try{const d=await api('/me/player/queue'),live=playback?.item?.id||'',remote=d?.currently_playing?.id||live;if(live&&remote&&live!==remote)return false;const seen=new Set([remote]),items=[];for(const raw of d?.queue||[]){const t=mapSpotifyTrack(raw);if(!t?.id||seen.has(t.id))continue;seen.add(t.id);items.push(t);if(items.length>=6)break}upcomingCache=items;upcomingForTrack=remote||live;actualQueue=true;paintNext();return true}catch{actualQueue=false;return false}finally{syncing=false}}
function renderNext(){paintNext();if(!window.JFMSpotifyUpcomingTruth)syncSpotifyUpcoming(false).catch(()=>{})}
window.jfmRenderNext=renderNext;
const oldBuild=buildSet;buildSet=window.buildSet=async function(){const list=await oldBuild();try{window.JFMRotation?.annotateAll?.(queue||list||[])}catch{}queue=direct(queue||list||[]);invalidateUpcoming('radioset-rebuild');renderNext();return queue};
function hideLegacyRadioMode(){const modeTitle=[...document.querySelectorAll('#tab-radio h3')].find(x=>x.textContent.trim()==='Radiomodus');const card=modeTitle?.closest('.card');if(card)card.style.display='none';const mini=$('modeMini');if(mini)mini.style.display='none'}
let seen='';setInterval(()=>{const item=playback?.item,id=item?.id;if(id&&id!==seen){seen=id;const m=memory();m.plays[id]=(m.plays[id]||0)+1;if(item?.uri&&m.requests[item.uri])m.requests[id]=Math.max(m.requests[id]||0,m.requests[item.uri]);save(m);invalidateUpcoming('trackchange')}hideLegacyRadioMode();renderNext()},3000);
window.addEventListener('jfm:trackchange',()=>{invalidateUpcoming('trackchange-event');paintNext();if(!window.JFMSpotifyUpcomingTruth)syncSpotifyUpcoming(true).catch(()=>{})});
window.addEventListener('jfm:requests-change',()=>{const sig=requestSig();if(sig!==lastRequestSig){lastRequestSig=sig;invalidateUpcoming('request-change');if(!window.JFMSpotifyUpcomingTruth)syncSpotifyUpcoming(true).catch(()=>{})}});
window.addEventListener('pageshow',()=>{hideLegacyRadioMode();if(!window.JFMSpotifyUpcomingTruth)syncSpotifyUpcoming(true).catch(()=>{})});
function tasteFeedback(id,label){const b=$(id);if(!b)return;b.textContent='✓ Onthouden';b.classList.add('pending');b.setAttribute('aria-busy','true');setTimeout(()=>{const x=$(id);if(x){x.textContent=label;x.classList.remove('pending');x.setAttribute('aria-busy','false')}},900)}
$('loveTrack')?.addEventListener('click',()=>{const id=playback?.item?.id;if(!id)return;const m=memory();m.likes[id]=(m.likes[id]||0)+1;const q=(queue||[]).find(t=>t.id===id);if(q?._discovery)m.discoveryWins[id]=(m.discoveryWins[id]||0)+1;save(m);tasteFeedback('loveTrack','♥ Meer van dit');try{window.dispatchEvent(new CustomEvent('mair:taste-feedback',{detail:{type:'more',trackId:id,at:Date.now()}}))}catch{};renderWhy()});
$('banTrack')?.addEventListener('click',async()=>{const id=playback?.item?.id;if(!id)return;const m=memory();m.likes[id]=(m.likes[id]||0)-3;const q=(queue||[]).find(t=>t.id===id);if(q?._discovery)m.discoveryLosses[id]=(m.discoveryLosses[id]||0)+1;save(m);tasteFeedback('banTrack','− Minder van dit');try{window.dispatchEvent(new CustomEvent('mair:taste-feedback',{detail:{type:'less',trackId:id,at:Date.now()}}))}catch{};try{if(window.JFMPlayback?.next)await window.JFMPlayback.next();else await control('next')}catch{}});
hideLegacyRadioMode();window.JFMProgramDirector={version:'director-v9-delegated-upcoming',direct,directWithContext,score:fitScore,upcoming,kind,why,isRequest,invalidateUpcoming,syncSpotifyUpcoming,render:renderNext};
setTimeout(()=>{renderNext();if(!window.JFMSpotifyUpcomingTruth)syncSpotifyUpcoming(true).catch(()=>{})},800);
})();
