// Josh FM Program Director — local/free adaptive programming
(()=>{
const $=id=>document.getElementById(id),memoryKey='jfm_director_memory';const memory=()=>{try{return JSON.parse(localStorage.getItem(memoryKey)||'{"plays":{},"likes":{},"requests":{},"discoveryWins":{},"discoveryLosses":{}}')}catch{return{plays:{},likes:{},requests:{},discoveryWins:{},discoveryLosses:{}}}};const save=m=>localStorage.setItem(memoryKey,JSON.stringify(m));const artistKey=t=>(t?.artists?.[0]||'').toLowerCase();const yr=t=>Number(String(t?.release||'').slice(0,4))||0;
window.jfmDirectorMemory=memory;window.jfmIsRequest=t=>{const m=memory();return!!(t&&(m.requests[t.id]||m.requests[t.uri]))};
function baseScore(t){const m=memory(),skips=(typeof skipMap==='function'?skipMap():{});return Math.random()*3-(skips[t.id]||0)*3.2-(m.plays[t.id]||0)*.28+(m.likes[t.id]||0)*4.5+(m.requests[t.id]||m.requests[t.uri]||0)*6+(m.discoveryWins[t.id]||0)*3-(m.discoveryLosses[t.id]||0)*4}
function fitScore(t,out){let s=baseScore(t),last=out[out.length-1],last2=out[out.length-2];if(!last)return s;if(artistKey(t)&&artistKey(t)===artistKey(last))s-=8;if(last2&&artistKey(t)===artistKey(last2))s-=4;const y=yr(t),ly=yr(last);if(y&&ly){const gap=Math.abs(y-ly);if(gap<=8)s+=1.2;else if(gap>22)s-=1.1}if(t._discovery){if(last?._discovery)s-=7;else s+=1.5}else if(last?._discovery)s+=2.5;return s}
function direct(list){const pool=[...list],out=[];while(pool.length){let best=0,bestS=-Infinity;for(let i=0;i<pool.length;i++){const s=fitScore(pool[i],out);if(s>bestS){bestS=s;best=i}}out.push(pool.splice(best,1)[0])}return out}
function kind(t){const m=memory();if(m.requests[t.id]||m.requests[t.uri])return'Verzoek';if(t._discovery)return'Ontdekking';return'Voor jou'}
function upcoming(){const current=playback?.item?.id,idx=(queue||[]).findIndex(t=>t.id===current);if(idx>=0)return(queue||[]).slice(idx+1,idx+7);return(queue||[]).filter(t=>t.id!==current).slice(0,6)}window.jfmUpcoming=upcoming;
function renderNext(){const box=$('directorQueue');if(!box)return;const items=upcoming();if(!items.length){box.innerHTML='<p class="muted">Start Josh FM om de programmering te zien.</p>';if($('nextUp'))$('nextUp').textContent='—';return}box.innerHTML=items.map((t,i)=>`<div class="director-track"><span class="director-num">${i+1}</span>${t.image?`<img src="${esc(t.image)}" alt="">`:''}<div class="director-meta"><b>${esc(t.name)}</b><span>${esc((t.artists||[]).join(', '))}</span></div><em>${kind(t)}</em></div>`).join('');const n=items[0];if($('nextUp'))$('nextUp').textContent=n?`${n.name} · ${(n.artists||[]).join(', ')}`:'—'}window.jfmRenderNext=renderNext;
const oldBuild=buildSet;buildSet=window.buildSet=async function(){const list=await oldBuild();queue=direct(queue||list||[]);renderNext();return queue};
$('searchResults')?.addEventListener('click',e=>{const btn=e.target.closest?.('.result');if(!btn)return;const uri=btn.dataset.uri;if(!uri)return;const m=memory();m.requests[uri]=(m.requests[uri]||0)+1;save(m);const em=btn.querySelector('em');if(em)em.textContent='✓ verzoek'},true);
let seen='';setInterval(()=>{const item=playback?.item,id=item?.id;if(!id||id===seen)return;seen=id;const m=memory();m.plays[id]=(m.plays[id]||0)+1;if(item?.uri&&m.requests[item.uri])m.requests[id]=Math.max(m.requests[id]||0,m.requests[item.uri]);save(m);renderNext()},5000);
$('loveTrack')?.addEventListener('click',()=>{const id=playback?.item?.id;if(!id)return;const m=memory();m.likes[id]=(m.likes[id]||0)+1;const q=(queue||[]).find(t=>t.id===id);if(q?._discovery)m.discoveryWins[id]=(m.discoveryWins[id]||0)+1;save(m);$('loveTrack').textContent='♥ Onthouden';setTimeout(()=>$('loveTrack').textContent='♥ Meer zoals dit',1000)});
$('banTrack')?.addEventListener('click',async()=>{const id=playback?.item?.id;if(!id)return;const m=memory();m.likes[id]=(m.likes[id]||0)-3;const q=(queue||[]).find(t=>t.id===id);if(q?._discovery)m.discoveryLosses[id]=(m.discoveryLosses[id]||0)+1;save(m);try{await control('next')}catch{}});
setInterval(renderNext,5000);setTimeout(renderNext,1200);
})();