// Josh FM discovery layer — resilient AI + Spotify discovery with diagnostics.
(()=>{
const slider=document.getElementById('discovery'),label=document.getElementById('discoveryValue');if(!slider||!label)return;
const stored=Number(localStorage.getItem('jfm_discovery'));slider.value=Number.isFinite(stored)?Math.max(0,Math.min(100,stored)):30;const paint=()=>label.textContent=`${slider.value}%`;paint();slider.addEventListener('input',()=>{paint();localStorage.setItem('jfm_discovery',slider.value)});slider.addEventListener('change',()=>{localStorage.setItem('jfm_discovery',slider.value);if(typeof queue!=='undefined')queue=[]});
const originalBuild=window.buildSet||buildSet;
const DIAG='jfm_discovery_diag_v2';
function mem(){try{return JSON.parse(localStorage.getItem('jfm_director_memory')||'{"plays":{},"likes":{},"requests":{}}')}catch{return{plays:{},likes:{},requests:{}}}}
function skips(){try{return typeof skipMap==='function'?skipMap():JSON.parse(localStorage.getItem('jfm_skips')||'{}')}catch{return{}}}
function seedScore(t,m,sm){return (m.likes?.[t.id]||0)*5-(sm[t.id]||0)*4-(m.plays?.[t.id]||0)*.12+Math.random()*2}
function interleave(familiar,discoveries,max=50){const out=[],f=[...familiar],d=[...discoveries];let sinceDiscovery=2;while(out.length<max&&(f.length||d.length)){const canDiscovery=d.length&&sinceDiscovery>=2,wantDiscovery=canDiscovery&&(Math.random()<.34||!f.length);if(wantDiscovery){out.push(d.shift());sinceDiscovery=0}else if(f.length){out.push(f.shift());sinceDiscovery++}else if(d.length){out.push(d.shift());sinceDiscovery=0}}return out}
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const sig=t=>`${norm(t?.name)}|${norm((t?.artists||[]).map?.(a=>a?.name||a)?.join?.(',')||'')}`;
function diag(state){try{localStorage.setItem(DIAG,JSON.stringify({...state,at:Date.now(),version:'resilient-discovery-v2'}))}catch{}window.JFMDiscoveryDiagnostic=state}
function acceptable(t,base,found,sm){if(!t?.id)return false;if((sm[t.id]||0)>=2)return false;const k=sig(t),id=t.id;if(base.some(b=>b.id===id||sig(b)===k))return false;if(found.some(f=>f.id===id||sig(f)===k))return false;return true}
async function searchTracks(q,limit=20,offset=0,stats){if(!q?.trim())return[];try{stats.searches++;const s=await api(`/search?type=track&limit=${limit}&offset=${offset}&q=`+encodeURIComponent(q));const items=s?.tracks?.items||[];stats.results+=items.length;return items}catch(e){stats.errors++;stats.lastError=String(e?.message||e);return[]}}
async function searchArtists(q,stats){try{stats.searches++;const s=await api('/search?type=artist&limit=5&q='+encodeURIComponent(q));const items=s?.artists?.items||[];stats.results+=items.length;return items}catch(e){stats.errors++;stats.lastError=String(e?.message||e);return[]}}
function pushFound(t,reason,base,found,sm){if(!acceptable(t,base,found,sm))return false;const x=trackObj(t);x._discovery=true;x._discoveryReason=reason||'Past bij je luisterprofiel.';found.push(x);return true}
async function searchIdea(idea,base,found,sm,stats){const title=String(idea?.title||'').trim(),artist=String(idea?.artist||'').trim();const queries=[title&&artist?`track:${title} artist:${artist}`:'',[title,artist].filter(Boolean).join(' '),[artist,title].filter(Boolean).join(' '),title,artist].filter(Boolean);for(const q of [...new Set(queries)]){for(const offset of [0,10]){const items=await searchTracks(q,15,offset,stats);const candidate=items.find(t=>acceptable(t,base,found,sm));if(candidate)return candidate}}return null}
async function artistCatalogFallback(seeds,base,found,sm,wanted,stats,genres){const artistNames=[...new Set(seeds.flatMap(s=>s.artists||[]).filter(Boolean))].slice(0,12);for(const name of artistNames){if(found.length>=wanted)break;const artists=await searchArtists(`artist:${name}`,stats);const artist=artists[0]||null;(artist?.genres||[]).slice(0,4).forEach(g=>{if(g&&!genres.includes(g))genres.push(g)});for(const q of [`artist:${name}`,name]){for(const offset of [0,20,40]){if(found.length>=wanted)break;const items=await searchTracks(q,20,offset,stats);for(const t of items){if(found.length>=wanted)break;pushFound(t,'Nieuwe match uit een artiest die al bij je smaak past.',base,found,sm)}}}}
}
async function genreFallback(genres,base,found,sm,wanted,stats){for(const genre of genres.slice(0,12)){if(found.length>=wanted)break;for(const q of [`genre:"${genre}"`,genre]){for(const offset of [0,20]){if(found.length>=wanted)break;const items=await searchTracks(q,25,offset,stats);for(const t of items){if(found.length>=wanted)break;pushFound(t,`Past bij je smaak binnen ${genre}.`,base,found,sm)}}}}
}
async function titleWordFallback(seeds,base,found,sm,wanted,stats){const stop=new Set(['feat','with','from','remix','edit','live','official','version','radio','the','and','you','your','this','that','voor','van','met','een','het','de']);const words=[];for(const seed of seeds.slice(0,16)){for(const w of String(seed.name||'').split(/\s+/)){const n=norm(w);if(n.length>=4&&!stop.has(n)&&!words.includes(n))words.push(n)}}for(const word of words.slice(0,16)){if(found.length>=wanted)break;for(const offset of [0,15]){const items=await searchTracks(word,20,offset,stats);for(const t of items){if(found.length>=wanted)break;pushFound(t,'Ontdekt via overeenkomsten met je recente muziek.',base,found,sm)}}}
}
async function broadFallback(seeds,base,found,sm,wanted,stats){const broadTerms=['pop','dance','indie','electronic','rock','r&b','soul','hip hop'];const seedArtistTerms=[...new Set(seeds.flatMap(s=>s.artists||[]).filter(Boolean))].slice(0,6);for(const q of [...seedArtistTerms,...broadTerms]){if(found.length>=wanted)break;const offset=Math.floor(Math.random()*3)*20;const items=await searchTracks(q,20,offset,stats);for(const t of items){if(found.length>=wanted)break;pushFound(t,'Extra ontdekking om de radioset gevarieerd te houden.',base,found,sm)}}}
async function spotifyFallback(seeds,base,found,sm,wanted,stats){const genres=[];await artistCatalogFallback(seeds,base,found,sm,wanted,stats,genres);if(found.length<wanted)await genreFallback(genres,base,found,sm,wanted,stats);if(found.length<wanted)await titleWordFallback(seeds,base,found,sm,wanted,stats);if(found.length<wanted)await broadFallback(seeds,base,found,sm,wanted,stats);return found}
window.buildSet=buildSet=async function(){const base=await originalBuild();const pct=Number(slider.value)||0;if(!pct||!base?.length)return base;const wanted=Math.max(1,Math.round(Math.min(50,base.length)*pct/100));const info=document.getElementById('queueInfo');if(info)info.textContent=`Josh FM zoekt ${wanted} nieuwe tracks die bij je smaak passen…`;
const m=mem(),sm=skips(),ranked=[...base].sort((a,b)=>seedScore(b,m,sm)-seedScore(a,m,sm)),seeds=ranked.slice(0,28).map(t=>({name:t.name,artists:t.artists,release:t.release,liked:m.likes?.[t.id]||0,skipped:sm[t.id]||0})),found=[];const stats={wanted,aiIdeas:0,aiMatches:0,searches:0,results:0,errors:0,lastError:''};
let aiWorked=false;
try{const r=await fetch('/api/discover',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({seeds,count:Math.min(24,Math.max(wanted+8,wanted*2)),mode:settings?.mode||'normal'})});let d={};try{d=await r.json()}catch{}if(r.ok){const ideas=(Array.isArray(d.tracks)?d.tracks:[]).slice(0,Math.min(48,wanted*4));stats.aiIdeas=ideas.length;for(const idea of ideas){if(found.length>=wanted)break;const candidate=await searchIdea(idea,base,found,sm,stats);if(candidate){const x=trackObj(candidate);x._discovery=true;x._discoveryReason=idea.reason||'AI-match op basis van je luisterprofiel.';found.push(x);stats.aiMatches++}}aiWorked=found.length>0}else{stats.lastError=`discover_api_${r.status}`}}
catch(e){stats.lastError=String(e?.message||e);console.warn('AI discovery unavailable, using Spotify fallback:',e)}
if(found.length<wanted)await spotifyFallback(seeds,base,found,sm,wanted,stats);
stats.found=found.length;diag(stats);
if(found.length){const familiar=ranked.slice(0,Math.max(0,50-found.length));queue=interleave(familiar,found,50);if(info)info.textContent=`${queue.length} tracks klaar · ${found.length} ontdekking${found.length===1?'':'en'} toegevoegd · ${pct}% ontdekking${aiWorked?'':' · Spotify fallback'}.`;return queue}
if(info){const hint=stats.errors?` Spotify gaf ${stats.errors} zoekfout${stats.errors===1?'':'en'}.`:` ${stats.searches} zoekopdrachten leverden geen bruikbare nieuwe match op.`;info.textContent=`${base.length} tracks klaar · geen geschikte nieuwe tracks gevonden.${hint}`}
return base;
}
window.JFMDiscovery={version:'resilient-discovery-v2',diagnostic:()=>{try{return JSON.parse(localStorage.getItem(DIAG)||'null')}catch{return null}}};
})();