// Josh FM AI discovery layer — taste-aware, spaced discoveries, no back-to-back surprises.
(()=>{
const slider=document.getElementById('discovery'),label=document.getElementById('discoveryValue');if(!slider||!label)return;
const stored=Number(localStorage.getItem('jfm_discovery'));slider.value=Number.isFinite(stored)?Math.max(0,Math.min(100,stored)):30;const paint=()=>label.textContent=`${slider.value}%`;paint();slider.addEventListener('input',()=>{paint();localStorage.setItem('jfm_discovery',slider.value)});slider.addEventListener('change',()=>{localStorage.setItem('jfm_discovery',slider.value);if(typeof queue!=='undefined')queue=[]});
const originalBuild=window.buildSet||buildSet;
function mem(){try{return JSON.parse(localStorage.getItem('jfm_director_memory')||'{"plays":{},"likes":{},"requests":{}}')}catch{return{plays:{},likes:{},requests:{}}}}
function skips(){try{return typeof skipMap==='function'?skipMap():JSON.parse(localStorage.getItem('jfm_skips')||'{}')}catch{return{}}}
function seedScore(t,m,sm){return (m.likes?.[t.id]||0)*5-(sm[t.id]||0)*4-(m.plays?.[t.id]||0)*.12+Math.random()*2}
function interleave(familiar,discoveries,max=50){const out=[],f=[...familiar],d=[...discoveries];let sinceDiscovery=2;while(out.length<max&&(f.length||d.length)){const canDiscovery=d.length&&sinceDiscovery>=2,wantDiscovery=canDiscovery&&(Math.random()<.34||!f.length);if(wantDiscovery){out.push(d.shift());sinceDiscovery=0}else if(f.length){out.push(f.shift());sinceDiscovery++}else if(d.length){out.push(d.shift());sinceDiscovery=0}}return out}
async function searchIdea(idea,base,found,sm){const exact=[idea.title,idea.artist].filter(Boolean).join(' ');const queries=[`track:${idea.title} artist:${idea.artist}`,exact,`${idea.artist} ${idea.title}`];for(const q of queries){if(!q.trim())continue;try{const s=await api('/search?type=track&limit=10&q='+encodeURIComponent(q)),items=s.tracks?.items||[];const candidate=items.find(t=>!base.some(b=>b.id===t.id)&&!found.some(f=>f.id===t.id)&&(sm[t.id]||0)<2);if(candidate)return candidate}catch{}}return null}
window.buildSet=buildSet=async function(){const base=await originalBuild();const pct=Number(slider.value)||0;if(!pct||!base?.length)return base;const wanted=Math.round(Math.min(50,base.length)*pct/100);if(!wanted)return base;const info=document.getElementById('queueInfo');if(info)info.textContent=`AI zoekt ${wanted} nieuwe tracks die bij je smaak passen…`;
try{const m=mem(),sm=skips(),ranked=[...base].sort((a,b)=>seedScore(b,m,sm)-seedScore(a,m,sm));const seeds=ranked.slice(0,24).map(t=>({name:t.name,artists:t.artists,release:t.release,liked:m.likes?.[t.id]||0,skipped:sm[t.id]||0}));const r=await fetch('/api/discover',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({seeds,count:Math.min(24,wanted+6),mode:settings?.mode||'normal'})});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d?.detail||d?.error||`discover ${r.status}`);const ideas=Array.isArray(d.tracks)?d.tracks:[],found=[];for(const idea of ideas.slice(0,Math.min(30,wanted*3))){if(found.length>=wanted)break;const candidate=await searchIdea(idea,base,found,sm);if(candidate){const x=trackObj(candidate);x._discovery=true;x._discoveryReason=idea.reason||'';found.push(x)}}
if(found.length){const familiar=ranked.slice(0,Math.max(0,50-found.length));queue=interleave(familiar,found,50);if(info)info.textContent=`${queue.length} tracks klaar · ${found.length} slimme ontdekking${found.length===1?'':'en'} · ${pct}% ontdekking.`;return queue}
if(info)info.textContent=`${base.length} tracks klaar · geen passende nieuwe tracks gevonden.`;return base}catch(e){console.warn('AI discovery:',e);if(info)info.textContent=`${base.length} tracks klaar · ontdekking kon deze keer niet worden aangevuld.`;return base}}
})();