(()=>{
'use strict';
const STORAGE_KEY='mair_dj_memory_v1',VERSION='1.0.0',EXACT_LIMIT=10,HISTORY_LIMIT=50,TRACK_LIMIT=80;
const clean=(v,n=240)=>String(v??'').replace(/\s+/g,' ').trim().slice(0,n);
const words=v=>clean(v,2000).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
const uniq=a=>[...new Set((a||[]).map(x=>clean(x,120)).filter(Boolean))];
function openingPattern(text){const x=words(text),first=x.split(' ').slice(0,7).join(' ');if(/^(dat was|je hoorde|dit was)/.test(first))return'THAT_WAS';if(/^(straks|hierna|zo meteen|dadelijk|de volgende|nu hoor je)/.test(first))return'COMING_UP';if(/^(het is|de tijd|bijna|net na)/.test(first))return'TIME_FIRST';if(/^(mair|je luistert naar mair)/.test(first))return'STATION_FIRST';if(/^(wat een|lekker|mooi|heerlijk|sterk|rustig)/.test(first))return'REACTION_FIRST';if(/^(wie|wat|waarom|hoe|ken je|wist je)/.test(first))return'QUESTION_FIRST';if(/^[a-z0-9'’-]+(?: [a-z0-9'’-]+){0,3} (?:met|van|en)/.test(first))return'ARTIST_NAME_FIRST';return'OTHER'}
function base(now){return{version:VERSION,revision:0,sessionStartedAt:now,recentBreaks:[],history:[],observedTracks:[],usedFactIds:[],skipTimes:[],rapidSkipTracksRemaining:0,metrics:{breaksScheduled:0,breaksAired:0,breaksNoTalk:0,qualityRegenerations:0,qualityFallbacks:0,qualitySkips:0,totalWords:0},lastBreakAt:0,lastTrackAt:0}}
function normalize(raw,now){const x=raw&&typeof raw==='object'?raw:{};return{...base(now),...x,version:VERSION,revision:Number(x.revision)||0,sessionStartedAt:Number(x.sessionStartedAt)||now,recentBreaks:Array.isArray(x.recentBreaks)?x.recentBreaks.slice(0,EXACT_LIMIT):[],history:Array.isArray(x.history)?x.history.slice(0,HISTORY_LIMIT):[],observedTracks:Array.isArray(x.observedTracks)?x.observedTracks.slice(0,TRACK_LIMIT):[],usedFactIds:uniq(x.usedFactIds),skipTimes:(Array.isArray(x.skipTimes)?x.skipTimes:[]).map(Number).filter(Number.isFinite),metrics:{...base(now).metrics,...(x.metrics||{})},lastBreakAt:Number(x.lastBreakAt)||0,lastTrackAt:Number(x.lastTrackAt)||0}}
function createDJMemory(options={}){
  const storage=Object.hasOwn(options,'storage')?options.storage:(typeof sessionStorage!=='undefined'?sessionStorage:null),nowFn=typeof options.now==='function'?options.now:()=>Date.now();let state;
  try{state=normalize(JSON.parse(storage?.getItem?.(STORAGE_KEY)||'null'),nowFn())}catch{state=base(nowFn())}
  function persist(){try{storage?.setItem?.(STORAGE_KEY,JSON.stringify(state))}catch{}}
  function bump(){state.revision++;persist()}
  function snapshot(){const now=nowFn(),hourAgo=now-3600000,recentHour=state.history.filter(x=>Number(x.timestamp)>=hourAgo);return{version:VERSION,revision:state.revision,sessionStartedAt:state.sessionStartedAt,sessionDurationMs:Math.max(0,now-state.sessionStartedAt),recentBreaks:state.recentBreaks.map(x=>({...x})),history:state.history.map(x=>({...x})),recentHour:recentHour.map(x=>({...x})),observedTracks:state.observedTracks.map(x=>({...x})),usedFactIds:[...state.usedFactIds],skipTimes:state.skipTimes.filter(x=>x>=now-300000),rapidSkipTracksRemaining:Math.max(0,Number(state.rapidSkipTracksRemaining)||0),lastBreakAt:state.lastBreakAt,tracksSinceLastBreak:state.lastBreakAt?state.observedTracks.filter(x=>Number(x.at)>state.lastBreakAt).length:state.observedTracks.length,minutesSinceLastBreak:state.lastBreakAt?Math.max(0,(now-state.lastBreakAt)/60000):Infinity,metrics:{...state.metrics},narrative:narrative()}}
  function narrative(){const tracks=state.observedTracks.slice(0,12),genres={},eras={};let discoveries=0;for(const t of tracks){for(const g of t.genres||[])genres[g]=(genres[g]||0)+1;const y=Number(t.year)||0;if(y)eras[`${Math.floor(y/10)*10}s`]=(eras[`${Math.floor(y/10)*10}s`]||0)+1;if(t.discovery)discoveries++}const top=o=>Object.entries(o).sort((a,b)=>b[1]-a[1])[0]?.[0]||'';return{dominantGenre:top(genres),dominantEra:top(eras),discoveries,recentSkips:state.skipTimes.filter(x=>x>=nowFn()-300000).length,sessionTracks:state.observedTracks.length,sessionMinutes:Math.round((nowFn()-state.sessionStartedAt)/60000)}}
  function observeTrack(track,cause='NATURAL_END'){if(!track?.id)return false;const item={id:clean(track.id,100),name:clean(track.name,180),artists:uniq(track.artists),year:Number(String(track.release||track.year||'').slice(0,4))||0,genres:uniq(track.genres).slice(0,4),discovery:!!track.discovery,at:nowFn(),cause:clean(cause,40)};if(state.observedTracks[0]?.id===item.id&&item.at-Number(state.observedTracks[0].at)<10000){state.observedTracks[0]={...state.observedTracks[0],...item,at:state.observedTracks[0].at};bump();return false}state.observedTracks.unshift(item);state.observedTracks=state.observedTracks.slice(0,TRACK_LIMIT);state.lastTrackAt=item.at;bump();return true}
  function recordSkip(at=nowFn()){state.skipTimes.push(Number(at)||nowFn());state.skipTimes=state.skipTimes.filter(x=>x>=nowFn()-300000);if(state.skipTimes.length>=3)state.rapidSkipTracksRemaining=Math.max(2,Number(state.rapidSkipTracksRemaining)||0);bump()}
  function consumeRapidSkipTrack(){if(Number(state.rapidSkipTracksRemaining)<=0)return false;state.rapidSkipTracksRemaining--;bump();return true}
  function metric(name,amount=1){if(!Object.hasOwn(state.metrics,name))state.metrics[name]=0;state.metrics[name]+=Number(amount)||0;bump()}
  function commit(record={}){if(!['COMPLETED','COMPLETED_RECOVERED'].includes(record.status))return false;const text=clean(record.text,1200);if(!text)return false;const timestamp=Number(record.timestamp)||nowFn(),opening=clean(record.opening||words(text).split(' ').slice(0,6).join(' '),120),item={breakId:clean(record.breakId,120),type:clean(record.breakType||'SESSION_LINK',40),text,opening,openingPattern:clean(record.openingPattern||openingPattern(text),40),artists:uniq(record.artists),tracks:uniq(record.tracks),topics:uniq(record.topics),factIds:uniq(record.factIds),hourKey:clean(record.hourKey,40),timestamp,words:text.split(/\s+/).filter(Boolean).length};state.recentBreaks.unshift(item);state.recentBreaks=state.recentBreaks.slice(0,EXACT_LIMIT);state.history.unshift({...item,text:undefined});state.history=state.history.slice(0,HISTORY_LIMIT);state.usedFactIds=uniq([...state.usedFactIds,...item.factIds]);state.lastBreakAt=timestamp;state.metrics.breaksAired++;state.metrics.totalWords+=item.words;bump();return true}
  function clear(){state=base(nowFn());persist()}
  return{version:VERSION,snapshot,observeTrack,recordSkip,consumeRapidSkipTrack,metric,commit,clear,openingPattern,canUseFact:id=>!!clean(id)&&!state.usedFactIds.includes(clean(id))}
}
const api={version:VERSION,create:createDJMemory,openingPattern};
if(typeof window!=='undefined'){window.MAIRDJMemoryFactory=api;window.MAIRDJMemory=window.MAIRDJMemory||createDJMemory()}
else globalThis.MAIRDJMemoryFactory=api;
})();
