(()=>{
'use strict';
if(window.MAIRDJ?.version?.startsWith('v2'))return;
const $=id=>document.getElementById(id),wait=ms=>new Promise(r=>setTimeout(r,ms));
const SILENT='data:audio/wav;base64,UklGRigAAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQQAAACA';
const TALK_RANGES=[[6,9],[3,5],[2,4],[1,3]],LABELS=['Weinig','Normaal','Radio','Veel'];
const audio=new Audio();audio.preload='auto';audio.playsInline=true;audio.setAttribute('playsinline','');
let audioUnlocked=false,lastTrackId='',manualFrom='',planTarget=4,count=0,pendingAir=false,busy=false,prepared=null,retryAfter=0;
let state={phase:'IDLE',reason:'boot',error:'',updatedAt:Date.now(),writer:null,voice:null,lastAirAt:0,lastAirText:'',attempts:0};
const recent=[];
const truth=()=>window.JFMPlaybackState?.get?.()||null;
const profile=()=>window.MAIRDJProfiles?.current||window.MAIRCurrentDJ||{id:'josh',name:'Josh',role:'MAIR DJ'};
const mode=()=>Math.max(0,Math.min(3,Number($('talk')?.value??1)||0));
const activeStation=()=>document.getElementById('mairActiveStation')?.textContent||window.MAIRStationController?.active?.()?.label||'MAIR';
const safeErr=e=>String(e?.message||e||'onbekende fout').slice(0,260);
function emit(){state.updatedAt=Date.now();try{window.dispatchEvent(new CustomEvent('mair:dj-v2-state',{detail:diagnostics()}))}catch{}render()}
function setPhase(phase,reason='',error=''){state={...state,phase,reason,error};emit()}
function chooseTarget(){const r=TALK_RANGES[mode()]||TALK_RANGES[1];return Math.floor(Math.random()*(r[1]-r[0]+1))+r[0]}
function resetPlan(reason='complete'){planTarget=chooseTarget();count=0;pendingAir=false;prepared=null;retryAfter=0;state.attempts=0;setPhase('PLANNED',reason)}
function remaining(){return pendingAir?0:Math.max(0,planTarget-count)}
function render(){const el=$('talkValue');if(el){const rem=remaining(),label=LABELS[mode()]||'Normaal';if(state.phase==='READY'||pendingAir)el.textContent=`${label} · DJ klaar voor volgende overgang`;else if(state.phase==='GENERATING'||state.phase==='WRITING')el.textContent=`${label} · DJ wordt voorbereid`;else el.textContent=`${label} · DJ over ${rem} nummer${rem===1?'':'s'}`;el.dataset.djRemaining=String(rem);el.dataset.djPhase=state.phase}try{window.dispatchEvent(new CustomEvent('mair:dj-schedule',{detail:{remaining:remaining(),phase:state.phase,target:planTarget,count,pendingAir}}))}catch{}}
async function unlock(){if(audioUnlocked)return true;try{audio.src=SILENT;audio.currentTime=0;await audio.play();audio.pause();audio.removeAttribute('src');audio.load();audioUnlocked=true;emit();return true}catch(e){state.error=`audio-unlock: ${safeErr(e)}`;emit();return false}}
for(const ev of ['pointerdown','touchstart'])document.addEventListener(ev,()=>{unlock().catch(()=>{})},{capture:true,passive:true});
function fromSpotifyItem(x){if(!x)return null;return{id:x.id||'',uri:x.uri||'',name:x.name||'',artists:(x.artists||[]).map(a=>a?.name||a).filter(Boolean),release:x.album?.release_date||x.release||'',request:typeof window.jfmIsRequest==='function'?!!window.jfmIsRequest(x):false}}
async function snapshot(){const live=await api('/me/player').catch(()=>null);if(!live?.item)return null;let next=null;try{const q=await api('/me/player/queue');next=fromSpotifyItem(q?.queue?.[0])}catch{}return{live,current:fromSpotifyItem(live.item),next}}
async function writeBreak(ctx,manual=false){setPhase('WRITING',manual?'manual':'automatic');const p=profile();const r=await fetch('/api/dj-writer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({dj:p,breakType:manual?'manual-next':'automatic-transition',length:'short',previousTrack:ctx.previous||null,currentTrack:ctx.current||null,nextTrack:ctx.next||null,time:new Date().toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'}),station:activeStation(),recentDJ:recent.slice(0,6)})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.text)throw Error(d?.error||`DJ writer HTTP ${r.status}`);state.writer={provider:d.provider||'groq',model:d.model||'',text:d.text};emit();return d.text}
async function renderVoice(text){setPhase('GENERATING','fish-audio');const p=profile();const r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:String(text).slice(0,1000),djProfile:p.id||'josh',jingle:false})});if(!r.ok){let d={};try{d=await r.json()}catch{}throw Error(d?.detail||d?.error||`Fish HTTP ${r.status}`)}const blob=await r.blob();if(!blob.size)throw Error('Fish Audio gaf geen audio terug');state.voice={provider:'fish',voiceId:r.headers.get('X-JoshFM-Voice')||'',model:r.headers.get('X-JoshFM-Fish-Model')||'',bytes:blob.size};emit();return blob}
async function prepare({manual=false,previous=null}={}){if(busy||['WRITING','GENERATING','READY','ON_AIR'].includes(state.phase)&&prepared)return prepared;busy=true;state.attempts++;try{const s=await snapshot();if(!s?.current)throw Error('Geen actieve Spotify-track voor DJ-context');const text=await writeBreak({previous,current:s.current,next:s.next},manual);const blob=await renderVoice(text);prepared={text,blob,manual,createdAt:Date.now(),forTrackId:s.current.id,nextId:s.next?.id||''};setPhase('READY',manual?'manual-ready':'auto-ready');return prepared}catch(e){prepared=null;setPhase('FAILED','prepare',safeErr(e));retryAfter=Date.now()+5000;return null}finally{busy=false}}
async function pause(uri){try{await api('/me/player/pause',{method:'PUT'})}catch(e){throw Error(`Spotify pause: ${safeErr(e)}`)}for(let i=0;i<5;i++){await wait(150+i*100);const s=await api('/me/player').catch(()=>null);if(s?.item?.uri===uri&&!s?.is_playing)return true}throw Error('Spotify pauze kon niet worden bevestigd')}
async function seekStart(uri){try{await api('/me/player/seek?position_ms=0',{method:'PUT'})}catch(e){throw Error(`Spotify rewind: ${safeErr(e)}`)}for(let i=0;i<4;i++){await wait(120+i*90);const s=await api('/me/player').catch(()=>null);if(s?.item?.uri===uri&&Number(s?.progress_ms||0)<1800)return true}throw Error('Spotify rewind kon niet worden bevestigd')}
async function resume(uri){try{await api('/me/player/play',{method:'PUT'})}catch(e){throw Error(`Spotify resume: ${safeErr(e)}`)}for(let i=0;i<5;i++){await wait(140+i*100);const s=await api('/me/player').catch(()=>null);if(s?.item?.uri===uri&&s?.is_playing)return true}throw Error('Spotify hervatten kon niet worden bevestigd')}
async function playPrepared(pack){await unlock();if(!audioUnlocked)throw Error('Browseraudio is niet ontgrendeld');const url=URL.createObjectURL(pack.blob);try{audio.src=url;audio.currentTime=0;audio.volume=1;try{window.dispatchEvent(new CustomEvent('mair:dj-speaking',{detail:{speaking:true,dj:profile()}}))}catch{}await audio.play();await new Promise((resolve,reject)=>{let done=false;const finish=e=>{if(done)return;done=true;clearTimeout(timer);audio.onended=null;audio.onerror=null;e?reject(e):resolve()};const timer=setTimeout(()=>finish(Error('DJ-audio timeout')),45000);audio.onended=()=>finish();audio.onerror=()=>finish(Error('Browser kon DJ-audio niet afspelen'))});return true}finally{try{window.dispatchEvent(new CustomEvent('mair:dj-speaking',{detail:{speaking:false,dj:profile()}}))}catch{}audio.pause();audio.removeAttribute('src');audio.load();URL.revokeObjectURL(url)}}
async function air(){if(busy||!prepared)return false;busy=true;const pack=prepared;let paused=false,uri='';setPhase('ON_AIR',pack.manual?'manual':'automatic');try{const s=await snapshot();uri=s?.live?.item?.uri||'';if(!s?.live?.is_playing||!uri)throw Error('Spotify speelt niet bij DJ-overgang');await pause(uri);paused=true;await playPrepared(pack);await seekStart(uri);await resume(uri);paused=false;state.lastAirAt=Date.now();state.lastAirText=pack.text;recent.unshift(pack.text);recent.splice(8);const bt=$('djBreakTime');if(bt)bt.textContent=new Date().toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'});const dt=$('djText');if(dt)dt.textContent=pack.text;prepared=null;manualFrom='';resetPlan('break-complete');return true}catch(e){setPhase('FAILED','air',safeErr(e));pendingAir=true;retryAfter=Date.now()+5000;return false}finally{if(paused&&uri){try{await seekStart(uri)}catch{}try{await resume(uri)}catch{}}busy=false;emit()}}
async function onTrackChange(id){id=String(id||truth()?.trackId||'');if(!id||id===lastTrackId)return;const previousId=lastTrackId;lastTrackId=id;if(!previousId){render();return}
  if(manualFrom&&id!==manualFrom){pendingAir=true;if(prepared){await wait(160);await air()}else if(Date.now()>retryAfter)prepare({manual:true}).then(()=>{if(prepared&&pendingAir)air().catch(()=>{})});return}
  if(pendingAir){if(prepared){await wait(160);await air()}else if(Date.now()>retryAfter)prepare({manual:false}).then(()=>{if(prepared&&pendingAir)air().catch(()=>{})});return}
  count++;render();const rem=remaining();if(rem===1&&!prepared&&Date.now()>retryAfter)prepare({manual:false}).catch(()=>{});if(rem<=0){pendingAir=true;if(prepared){await wait(160);await air()}else if(Date.now()>retryAfter)prepare({manual:false}).catch(()=>{})}}
function armManual(){const id=String(truth()?.trackId||'');if(!id)return false;manualFrom=manualFrom===id?'':id;pendingAir=false;prepared=null;const b=$('djNow');if(b){b.dataset.queued=manualFrom?'1':'0';const strong=b.querySelector('b'),small=b.querySelector('span');if(strong)strong.textContent=manualFrom?'🎙️ DJ staat klaar':'🎙️ DJ nu';if(small)small.textContent=manualFrom?'Praat bij het volgende nummer':'Laat de DJ iets vertellen'}if(manualFrom)prepare({manual:true}).catch(()=>{});else resetPlan('manual-cancel');return !!manualFrom}
function ownButton(){const old=$('djNow');if(!old||old.dataset.mairDjOwner==='v2')return;const b=old.cloneNode(true);old.replaceWith(b);b.dataset.mairDjOwner='v2';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();armManual()},true)}
async function writerCheck(){const r=await fetch('/api/dj-writer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({dj:profile(),breakType:'diagnostic',length:'short',currentTrack:{name:'Voice Check',artists:['MAIR']},station:'MAIR',time:new Date().toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'})})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.text)throw Error(d?.error||`Groq HTTP ${r.status}`);return d}
async function fishCheck(text){const r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,djProfile:profile()?.id||'josh',jingle:false})});if(!r.ok){const d=await r.json().catch(()=>({}));throw Error(d?.detail||d?.error||`Fish HTTP ${r.status}`)}const blob=await r.blob();if(!blob.size)throw Error('Fish Audio gaf 0 bytes terug');return{blob,bytes:blob.size,model:r.headers.get('X-JoshFM-Fish-Model')||'',voiceId:r.headers.get('X-JoshFM-Voice')||''}}
async function runVoiceCheck(onStep=()=>{}){const steps=[];const step=(name,status,detail='')=>{const x={name,status,detail,at:Date.now()};steps.push(x);try{onStep(x,[...steps])}catch{};return x};step('DJ runtime','pass',version);let w;try{w=await writerCheck();step('Groq DJ Writer','pass',`${w.model||'model'} · ${String(w.text).slice(0,90)}`)}catch(e){step('Groq DJ Writer','fail',safeErr(e));return steps}let f;try{f=await fishCheck('Dit is de MAIR Voice Check. Als je dit hoort, werkt Fish Audio en de afspeelroute.');step('Fish Audio generatie','pass',`${f.bytes} bytes${f.model?' · '+f.model:''}`)}catch(e){step('Fish Audio generatie','fail',safeErr(e));return steps}try{await unlock();if(!audioUnlocked)throw Error('audio niet ontgrendeld');step('Browser audio unlock','pass','HTML Audio ontgrendeld')}catch(e){step('Browser audio unlock','fail',safeErr(e));return steps}try{await playPrepared({blob:f.blob,text:'Voice Check',manual:true});step('DJ audio playback','pass','start + ended ontvangen')}catch(e){step('DJ audio playback','fail',safeErr(e));return steps}const s=await snapshot().catch(()=>null);if(!s?.live?.item?.uri||!s.live.is_playing){step('Spotify pause/resume','skip','Geen actieve Spotify-playback om veilig te testen');return steps}const uri=s.live.item.uri;try{await pause(uri);step('Spotify pause','pass','pauze bevestigd');await resume(uri);step('Spotify resume','pass','hervatten bevestigd')}catch(e){try{await resume(uri)}catch{}step('Spotify pause/resume','fail',safeErr(e))}return steps}
function diagnostics(){return{version,phase:state.phase,reason:state.reason,error:state.error,remaining:remaining(),target:planTarget,count,pendingAir,busy,prepared:prepared?{text:prepared.text,bytes:prepared.blob?.size||0,manual:prepared.manual,createdAt:prepared.createdAt}:null,audioUnlocked,writer:state.writer,voice:state.voice,lastAirAt:state.lastAirAt,lastAirText:state.lastAirText,attempts:state.attempts,dj:profile()}}
const version='v2.0-zero-rebuild-groq-prebuffer';
window.MAIRDJ={version,prepare,air,armManual,runVoiceCheck,diagnostics,unlock,plan:resetPlan,state:diagnostics};
window.JFMDJAuthoritative=window.MAIRDJ;window.djBreak=()=>{pendingAir=true;return prepared?air():prepare({manual:true}).then(()=>prepared?air():false)};
function bindFrequency(){const t=$('talk');if(!t||t.dataset.mairDjV2Bound)return;t.dataset.mairDjV2Bound='1';t.addEventListener('change',()=>resetPlan('frequency-change'));t.addEventListener('input',render)}
function boot(){ownButton();bindFrequency();lastTrackId=String(truth()?.trackId||'');resetPlan('boot');render()}
window.addEventListener('jfm:trackchange',e=>setTimeout(()=>onTrackChange(e.detail?.trackId).catch(err=>{state.error=safeErr(err);emit()}),90));
window.addEventListener('jfm:natural-next-ready',e=>setTimeout(()=>onTrackChange(e.detail?.newTrackId).catch(()=>{}),90));
window.addEventListener('pageshow',()=>setTimeout(()=>{ownButton();bindFrequency();render()},150));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
