// MAIR Modes — one policy/analytics owner; playback remains owned by JFMPlayback/JFMQueue.
(()=>{
'use strict';
if(window.MAIRModeManager)return;
const STATE_KEY='mair_mode_state_v1',DATA_KEY='mair_mode_analytics_v1',VALID=new Set(['normal','roadtrip']),DAY=86400000;
const read=(key,fallback)=>{try{const x=JSON.parse(localStorage.getItem(key)||'null');return x&&typeof x==='object'?x:fallback}catch{return fallback}},write=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{}},clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),yearValue=value=>{const y=Number(String(value||'').slice(0,4));return y>=1900&&y<=new Date().getFullYear()+1?y:0},year=t=>yearValue(t?.release||t?.album?.release_date)||yearValue(t?.year),artist=t=>String(t?.artists?.[0]?.name||t?.artists?.[0]||'').trim(),trackId=t=>String(t?.id||t?.uri||'');
const labels={normal:'MAIRFM',roadtrip:'ROADTRIP'};
let state={mode:'normal',options:{},startedAt:0,activeMs:0,lastActiveAt:0,endsAfterMs:0,sessionId:'',...read(STATE_KEY,{})},lastTrack='',starting=false,pendingRecap=null,lastTickAt=0,listenCarryMs=0;
if(!VALID.has(state.mode))state={mode:'normal',options:{},startedAt:0,activeMs:0,lastActiveAt:0,endsAfterMs:0,sessionId:''};
function persist(){write(STATE_KEY,state)}
function data(){const d=read(DATA_KEY,{events:[],sessions:[]});return{events:Array.isArray(d.events)?d.events:[],sessions:Array.isArray(d.sessions)?d.sessions:[]}}
function saveData(d){const cutoff=Date.now()-400*DAY;d.events=d.events.filter(x=>Number(x.at)>=cutoff).slice(-12000);d.sessions=d.sessions.filter(x=>Number(x.startedAt)>=cutoff).slice(-1000);write(DATA_KEY,d)}
function record(type,detail={}){const d=data();d.events.push({at:Date.now(),type,mode:state.mode,...detail});saveData(d);try{window.dispatchEvent(new CustomEvent('mair:mode-analytics',{detail:{type,mode:state.mode}}))}catch{}}
function emit(reason='update'){if(document.body)document.body.dataset.mairMode=state.mode;try{window.dispatchEvent(new CustomEvent('mair:mode-change',{detail:{...snapshot(),reason}}))}catch{}}
function snapshot(){return{...state,options:{...state.options},label:labels[state.mode]||'MAIRFM',active:state.mode!=='normal',progress:state.endsAfterMs?clamp(state.activeMs/state.endsAfterMs,0,1):0,remainingMs:state.endsAfterMs?Math.max(0,state.endsAfterMs-state.activeMs):null,phase:roadtripPhase()}}
function playing(){try{return !!(window.JFMPlaybackState?.get?.()?.isPlaying??playback?.is_playing)}catch{return false}}
function roadtripPhase(){if(state.mode!=='roadtrip')return'';const p=state.endsAfterMs?state.activeMs/state.endsAfterMs:0;return p<.17?'Start':p<.52?'Cruise':p<.78?'Peak':'Final Stretch'}
function momentum(t){if(Number.isFinite(Number(t?._momentum)))return Number(t._momentum);return clamp(Number(t?.popularity||55)/100*.72+.18,0,1)}
function modeScore(t,out=[]){if(state.mode==='normal')return 0;const y=year(t),m=momentum(t),requested=!!window.JFMRequests?.isRequest?.(t),last=out.at(-1),lastY=year(last),lastM=momentum(last);let score=0;
  if(state.mode==='roadtrip'){const p=state.endsAfterMs?state.activeMs/state.endsAfterMs:0,style=state.options.style||'normal',adjust=style==='relaxed'?-.13:style==='energy'?.11:style==='night'?-.08:style==='surprise'?(p<.5?.08:-.05):0,target=clamp((p<.17?.5:p<.52?.66:p<.78?.84:p<.92?.62:.82)+adjust,.3,.95);score-=Math.abs(m-target)*18;score+=requested?8:0}
  return score
}
function reason(){if(state.mode==='roadtrip')return`Past bij de ${roadtripPhase()}-fase van je roadtrip.`;return''}
function djContext(){const recap=pendingRecap?{period:pendingRecap.period,minutes:pendingRecap.minutes,tracks:pendingRecap.tracks,topArtist:pendingRecap.topArtist,topTrack:pendingRecap.topTrack,decade:pendingRecap.decade,skips:pendingRecap.skips,requests:pendingRecap.requests,discoveries:pendingRecap.discoveries,insight:pendingRecap.insight}:null;if(state.mode==='normal')return{mode:'normal',label:recap?'MAIR recap':'',recap};return{mode:state.mode,label:`Roadtrip · ${roadtripPhase()}`,recap}}
function toTrack(x){return{id:x.id,uri:x.uri,name:x.name,artists:(x.artists||[]).map(a=>a?.name||a).filter(Boolean),album:x.album?.name||'',release:x.album?.release_date||x.release||'',image:x.album?.images?.[0]?.url||x.image||'',duration:x.duration_ms||x.duration||0,popularity:Number(x.popularity)||0}}
async function search(q){try{const d=await window.api?.('/search?type=track&limit=50&q='+encodeURIComponent(q));return(d?.tracks?.items||[]).map(toTrack).filter(t=>t.id&&t.uri)}catch{return[]}}
function unique(list){const seen=new Set();return(list||[]).filter(t=>{const id=trackId(t);if(!id||seen.has(id))return false;seen.add(id);return true})}
async function poolFor(mode,options){let base=[];try{base=await window.JFMQueue?.buildActive?.('mode-'+mode)||window.JFMQueue?.current?.()||[]}catch{base=window.JFMQueue?.current?.()||[]}
  let extra=[];if(mode==='roadtrip'){const built=await Promise.allSettled([window.MAIRStationController?.buildPool?.('hits'),window.MAIRStationController?.buildPool?.('throwback'),window.MAIRStationController?.buildPool?.('new')]);extra=built.flatMap(x=>x.status==='fulfilled'?(x.value?.tracks||[]):[])}
  const pool=unique([...extra,...base]);return pool.length?pool:base
}
async function activatePool(mode,options){const pool=await poolFor(mode,options);if(!pool.length)return false;const planned=window.JFMRotation?.plan?.(pool,[])||pool.sort((a,b)=>modeScore(b,[])-modeScore(a,[])),prepared=unique(planned).slice(0,60);if(!prepared.length)return false;window.JFMQueue?.commit?.(prepared,{source:'mair-mode',station:localStorage.getItem('jfm_music_channel_v1')||'mix',reason:'mode-'+mode});try{window.__jfmStationQueueSig='';window.jfmRenderNext?.()}catch{};if(prepared[0]?.uri&&window.JFMPlayback?.playUri)await window.JFMPlayback.playUri(prepared[0].uri).catch(()=>false);return true}
function durationMs(mode,options){if(mode==='roadtrip')return clamp(Number(options.minutes)||60,15,300)*60000;return Number(options.minutes)>0?Number(options.minutes)*60000:0}
async function start(mode,options={},force=false){if(!VALID.has(mode)||mode==='normal')return stop('normal-request');if(starting)return{ok:false,busy:true};if(state.mode!=='normal'&&state.mode!==mode&&!force)return{ok:false,requiresConfirmation:true,current:state.mode,next:mode};starting=true;try{if(state.mode!=='normal')finishSession('replaced');state={mode,options:{...options},startedAt:Date.now(),activeMs:0,lastActiveAt:0,endsAfterMs:durationMs(mode,options),sessionId:`mode-${Date.now()}-${Math.random().toString(36).slice(2,7)}`};persist();record('mode_start',{sessionId:state.sessionId,options:state.options});emit('start');const loaded=await activatePool(mode,state.options).catch(()=>false);emit(loaded?'ready':'fallback');return{ok:true,fallback:!loaded,state:snapshot()}}finally{starting=false}}
function finishSession(reason){if(state.mode==='normal'||!state.sessionId)return;const d=data();d.sessions.push({id:state.sessionId,mode:state.mode,options:state.options,startedAt:state.startedAt,endedAt:Date.now(),activeMs:state.activeMs,completed:reason==='completed',reason});saveData(d);record('mode_stop',{sessionId:state.sessionId,reason,activeMs:state.activeMs})}
async function stop(reason='user'){const was=state.mode;if(was!=='normal')finishSession(reason);state={mode:'normal',options:{},startedAt:0,activeMs:0,lastActiveAt:0,endsAfterMs:0,sessionId:''};persist();emit('stop');try{const pool=await window.JFMQueue?.buildActive?.('mode-return-normal');if(pool?.length){const planned=window.JFMRotation?.plan?.(pool,[])||pool;window.JFMQueue?.commit?.(planned,{source:'station',station:localStorage.getItem('jfm_music_channel_v1')||'mix',reason:'mode-return-normal'});if(planned[0]?.uri&&window.JFMPlayback?.playUri)await window.JFMPlayback.playUri(planned[0].uri).catch(()=>false)}}catch{}return{ok:true,previous:was}}
function periodStart(period,now=Date.now()){const d=new Date(now);if(period==='weekly'){const day=(d.getDay()+6)%7;d.setHours(0,0,0,0);d.setDate(d.getDate()-day)}else if(period==='monthly'){d.setDate(1);d.setHours(0,0,0,0)}else{d.setMonth(0,1);d.setHours(0,0,0,0)}return d.getTime()}
function recap(period='weekly',now=Date.now()){const d=data(),events=d.events.filter(x=>x.at>=periodStart(period,now)&&x.at<=now),sessions=d.sessions.filter(x=>x.startedAt>=periodStart(period,now)&&x.startedAt<=now),tracks=events.filter(x=>x.type==='track'),count=key=>{const m=new Map();for(const x of tracks){const v=x[key];if(v)m.set(v,(m.get(v)||0)+1)}return[...m].sort((a,b)=>b[1]-a[1])[0]?.[0]||'Nog in opbouw'},modes=new Map(),stations=new Map(),djs=new Map(),years=[];for(const x of events){if(x.mode&&x.mode!=='normal')modes.set(x.mode,(modes.get(x.mode)||0)+1);if(x.station)stations.set(x.station,(stations.get(x.station)||0)+1);if(x.dj)djs.set(x.dj,(djs.get(x.dj)||0)+1);if(x.year)years.push(x.year)}const top=m=>[...m].sort((a,b)=>b[1]-a[1])[0]?.[0]||'Nog in opbouw',minutes=events.filter(x=>x.type==='listen_minute').length;const decade=years.length?`${Math.round(years.reduce((a,b)=>a+b,0)/years.length/10)*10}s`:'Nog in opbouw',skips=events.filter(x=>x.type==='skip').length,requests=events.filter(x=>x.type==='request').length,likes=events.filter(x=>x.type==='like'&&x.value==='more').length,discoveries=tracks.filter(x=>x.discovery).length,uniqueArtists=new Set(tracks.map(x=>x.artist).filter(Boolean)).size;let insight=tracks.length<5?'Luister nog even door voor een betrouwbare recap.':decade!=='Nog in opbouw'?`Je zat deze periode duidelijk in je ${decade}-era.`:'Je persoonlijke luisterpatroon wordt steeds duidelijker.';if(skips>tracks.length*.35&&tracks.length>5)insight='Je was selectief: relatief veel nummers kregen een snelle skip.';else if(discoveries>=5)insight='Je gaf nieuwe muziek opvallend veel ruimte.';return{period,minutes,tracks:tracks.length,topArtist:count('artist'),topTrack:count('track'),topStation:top(stations),skips,requests,decade,discoveries,uniqueArtists,likes,topMode:top(modes),topDJ:top(djs),insight,sessions:sessions.length}}
function onTrack(e){const t=e.detail?.track||e.detail?.item||(()=>{try{return playback?.item}catch{return null}})();const id=trackId(t)||String(e.detail?.trackId||'');if(!id||id===lastTrack)return;lastTrack=id;record('track',{trackId:id,track:t?.name||'',artist:artist(t),year:year(t),station:localStorage.getItem('jfm_music_channel_v1')||'mix',dj:window.MAIRCurrentDJ?.id||'',discovery:!!t?._discovery,sessionId:state.sessionId})}
function requestRecap(period='weekly'){const recapData=recap(period);if(!recapData.tracks)return{ok:false,reason:'insufficient-data'};pendingRecap={...recapData,requestedAt:Date.now()};const armed=window.MAIRDJ?.armManual?.();if(armed!==true){pendingRecap=null;return{ok:false,reason:'dj-unavailable'}}setTimeout(()=>{if(pendingRecap&&Date.now()-pendingRecap.requestedAt>=119000)pendingRecap=null},120000);return{ok:true,recap:recapData}}
window.addEventListener('jfm:trackchange',onTrack);window.addEventListener('mair:track-transition',e=>{if(['USER_NEXT','USER_PREVIOUS'].includes(String(e.detail?.cause||'')))record('skip',{cause:e.detail.cause})});window.addEventListener('mair:request-confirmed',()=>record('request'));window.addEventListener('mair:taste-feedback',e=>{let current=null;try{current=window.JFMPlaybackState?.get?.()?.item}catch{}record('like',{value:e.detail?.type||'',category:e.detail?.category||current?._rotationCategory||''})});window.addEventListener('mair:station-selected',e=>record('station',{station:e.detail?.id||''}));window.addEventListener('mair:djchange',e=>record('dj',{dj:e.detail?.id||''}));
window.addEventListener('mair:dj-v2-state',e=>{if(pendingRecap&&['SPEAKING','COUNTING'].includes(String(e.detail?.phase||''))&&Date.now()-pendingRecap.requestedAt>500)pendingRecap=null});
setInterval(()=>{const now=Date.now(),isPlaying=playing(),delta=lastTickAt?Math.min(3000,Math.max(0,now-lastTickAt)):0;lastTickAt=now;if(isPlaying){listenCarryMs+=delta;while(listenCarryMs>=60000){listenCarryMs-=60000;record('listen_minute',{sessionId:state.sessionId})}}if(state.mode==='normal')return;if(isPlaying){state.activeMs+=delta;state.lastActiveAt=now}else state.lastActiveAt=0;persist();emit('tick');if(state.endsAfterMs&&state.activeMs>=state.endsAfterMs)stop('completed')},1000);
function clear(){try{localStorage.removeItem(DATA_KEY);localStorage.removeItem(STATE_KEY)}catch{};state={mode:'normal',options:{},startedAt:0,activeMs:0,lastActiveAt:0,endsAfterMs:0,sessionId:''};emit('clear')}
document.addEventListener('click',e=>{if(e.target.closest?.('#clearHistory'))setTimeout(clear,0)},true);
window.MAIRModeManager={version:'mair-modes-v3-roadtrip-only',start,stop,clear,state:snapshot,rotationScore:modeScore,rotationReason:reason,djContext,recap,requestRecap,periodStart,record,analytics:()=>data(),poolFor};persist();emit('boot');if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>emit('dom-ready'),{once:true});window.MAIRRuntime?.register?.('mair-modes',{version:'mair-modes-v3-roadtrip-only',owner:'mode-policy-analytics'});
})();
