// MAIRFM 1.0 authoritative presentation owner. Reuses existing functional controls.
(()=>{
'use strict';
if(window.MAIRUX?.version)return;
const $=id=>document.getElementById(id),SEEN='mairfm_welcome_seen_v1';let lastState=null,noticeTimer=0,installed=false;
const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function setText(el,text){if(el&&el.textContent!==text)el.textContent=text}
function markButton(id,label){const b=$(id);if(!b)return;b.type='button';b.setAttribute('aria-label',label);b.title=label}
function brand(){document.title='MAIRFM';document.querySelectorAll('.brandwrap h1').forEach(x=>setText(x,'MAIRFM'));document.querySelectorAll('.brandwrap .kicker').forEach(x=>setText(x,'JOUW MUZIEK. ALS ECHTE RADIO.'));document.querySelectorAll('.mair-radio-heading').forEach(x=>x.setAttribute('aria-label','MAIRFM Radio'))}
function setupNavigation(){const nav=document.querySelector('.mair-bottom-nav');if(!nav)return;nav.querySelector('[data-mair-tab="requests"]')?.remove();const labels={radio:['▣','Radio'],stations:['⌘','Stations'],settings:['⚙','Instellingen']};nav.querySelectorAll('.mair-nav-btn').forEach(b=>{const x=labels[b.dataset.mairTab];if(x)b.innerHTML=`<span class="ico" aria-hidden="true">${x[0]}</span><span>${x[1]}</span>`});nav.style.gridTemplateColumns='repeat(3,1fr)';document.querySelector('.tabs')?.setAttribute('aria-hidden','true')}
function buildRadio(){const pane=$('tab-radio'),now=pane?.querySelector('.now');if(!pane||!now)return false;pane.classList.add('mairfm-radio');let header=$('mairfmRadioHeader');if(!header){header=document.createElement('header');header.id='mairfmRadioHeader';header.className='mairfm-radio-header';header.innerHTML='<div><strong>MAIRFM</strong><span id="mairfmStationLive">Your Mix • LIVE</span></div><button id="mairfmSettingsShortcut" type="button" aria-label="Instellingen openen">⚙</button>';pane.insertBefore(header,pane.firstChild)}
  now.setAttribute('aria-label','Nu op MAIRFM');now.classList.add('mairfm-now');const title=$('title'),artist=$('artist');title?.setAttribute('aria-live','polite');artist?.setAttribute('aria-live','polite');markButton('prev','Vorige nummer');markButton('play','Afspelen of pauzeren');markButton('next','Volgende nummer');
  let playback=$('mairfmPlaybackStatus');if(!playback){playback=document.createElement('div');playback.id='mairfmPlaybackStatus';playback.className='mairfm-playback-status';playback.setAttribute('aria-live','polite');now.querySelector('.transport')?.insertAdjacentElement('afterend',playback)}
  let notice=$('mairfmNotice');if(!notice){notice=document.createElement('section');notice.id='mairfmNotice';notice.className='mairfm-notice hidden';notice.setAttribute('aria-live','assertive');notice.innerHTML='<div><b id="mairfmNoticeTitle"></b><p id="mairfmNoticeMessage"></p></div><div id="mairfmNoticeActions"></div>';now.insertAdjacentElement('beforebegin',notice)}
  let dj=$('mairfmDjPublic');if(!dj){dj=document.createElement('section');dj.id='mairfmDjPublic';dj.className='mairfm-dj-public';dj.innerHTML='<span id="mairfmOnAirDot" aria-hidden="true"></span><div><b id="mairfmDjLabel">DJ · Luistert mee</b><small id="mairfmDjDetail">De DJ kiest zelf de juiste radiomomenten.</small></div>';now.insertAdjacentElement('afterend',dj)}
  const oldDj=$('djText')?.closest('article.card');if(oldDj)oldDj.classList.add('mairfm-diagnostic-only');
  let actions=$('mairfmSecondaryActions');if(!actions){actions=document.createElement('div');actions.id='mairfmSecondaryActions';actions.className='mairfm-secondary-actions';actions.innerHTML='<button id="mairfmRequest" type="button">Nummer aanvragen</button>';dj.insertAdjacentElement('afterend',actions);const grid=$('djNow')?.closest('.grid2');if(grid){grid.classList.add('mairfm-existing-actions');actions.append(...grid.children)}const request=$('mairfmRequest');request?.addEventListener('click',()=>window.MAIRFoundation?.activate?.('requests'))}
  const djNow=$('djNow');if(djNow){djNow.innerHTML='<b>DJ bij volgende overgang</b><span>Plan één extra radiomoment</span>';djNow.setAttribute('aria-label','DJ bij volgende overgang')}const quiet=$('skipTalk');if(quiet){quiet.innerHTML='<b>Even stil</b><span>Volgende radiomoment overslaan</span>';quiet.setAttribute('aria-label','Volgende radiomoment overslaan')}
  const up=$('mair-up-next');if(up){up.classList.add('mairfm-up-next');const h=up.querySelector('h3');if(h)setText(h,'Hierna op MAIRFM')}
  return true
}
function buildOnboarding(){const setup=$('setup'),radio=$('tab-radio');if(!setup||!radio)return;setup.classList.add('mairfm-connect');const client=$('clientId'),redirect=$('redirect'),connect=$('connect'),labels=[client?.closest('label'),redirect?.closest('label')].filter(Boolean);let internals=setup.querySelector('.mairfm-auth-internals');if(!internals){internals=document.createElement('div');internals.className='mairfm-auth-internals';internals.hidden=true;for(const label of labels)internals.appendChild(label);setup.insertBefore(internals,setup.firstChild)}let copy=setup.querySelector('.mairfm-connect-copy');if(!copy){copy=document.createElement('div');copy.className='mairfm-connect-copy';copy.innerHTML='<div class="mairfm-wordmark">MAIRFM</div><h2>Jouw muziek. Als echte radio.</h2><p>MAIRFM maakt van je Spotify-muziek een persoonlijke radio-uitzending met een DJ, slimme muziekflow en echte radiomomenten.</p><ul><li>Muziek via Spotify</li><li>Een DJ op de juiste momenten</li><li>Geen gepraat na ieder nummer</li></ul><small>Spotify Premium is nodig om muziek via MAIRFM af te spelen.</small>';internals.insertAdjacentElement('afterend',copy)}if(connect){setText(connect,'Verbinden met Spotify');connect.classList.add('mairfm-connect-cta');copy.insertAdjacentElement('afterend',connect)}let diag=setup.querySelector('#mairfmConnectDiagnostics');if(!diag){diag=document.createElement('button');diag.id='mairfmConnectDiagnostics';diag.type='button';diag.className='mairfm-text-button';diag.textContent='Diagnostics';diag.addEventListener('click',openDiagnostics);connect?.insertAdjacentElement('afterend',diag)}for(const child of [...setup.children]){if(child!==internals&&child!==copy&&child!==connect&&child!==diag)child.classList.add('mairfm-auth-legacy-copy')}radio.insertBefore(setup,radio.firstChild)
}
function buildWelcome(){const radio=$('tab-radio');if(!radio||$('mairfmWelcome'))return;const card=document.createElement('section');card.id='mairfmWelcome';card.className='mairfm-welcome hidden';card.innerHTML='<div class="kicker">WELKOM BIJ MAIRFM</div><h2>Je kiest de muziek. MAIRFM maakt er radio van.</h2><div><span>Muziek via Spotify</span><span>Een DJ op de juiste momenten</span><span>Geen gepraat na ieder nummer</span></div><button id="mairfmWelcomeStart" class="cta" type="button">Start MAIRFM</button><button id="mairfmWelcomeStations" class="mairfm-text-button" type="button">Kies station</button>';radio.insertBefore(card,$('mairfmRadioHeader')||radio.firstChild);$('mairfmWelcomeStart')?.addEventListener('click',()=>{$('start')?.click()});$('mairfmWelcomeStations')?.addEventListener('click',()=>window.MAIRFoundation?.activate?.('stations'))}
function organizeSecondaryFeatures(){
  const actions=$('mairfmSecondaryActions'),sleep=$('mairSleepOpen');
  if(actions&&sleep&&sleep.parentElement!==actions)actions.appendChild(sleep);
  const stations=$('tab-stations-mair'),top40=$('jfmTop40Card'),guide=$('jfmProgramGuide');
  if(!stations||(!top40&&!guide))return;
  let details=$('mairfmStationDetails');
  if(!details){details=document.createElement('details');details.id='mairfmStationDetails';details.className='mairfm-station-details';details.innerHTML='<summary><span>Jouw stationoverzicht</span><small>Programmagids en persoonlijke hitlijst</small></summary><div id="mairfmStationDetailsBody"></div>';stations.appendChild(details)}
  const body=$('mairfmStationDetailsBody');
  for(const card of [guide,top40].filter(Boolean))if(body&&card.parentElement!==body)body.appendChild(card);
}
function watchSecondaryFeatures(){
  let scheduled=false;const sync=()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;organizeSecondaryFeatures()})};
  const observer=new MutationObserver(sync);observer.observe(document.body,{childList:true,subtree:true});setTimeout(()=>observer.disconnect(),20000);organizeSecondaryFeatures()
}
function cleanSettings(){const pane=$('tab-settings');if(!pane)return;pane.classList.add('mairfm-settings');const pageTitle=pane.querySelector('.mair-page-title h2');if(pageTitle)setText(pageTitle,'Instellingen');let back=$('mairfmDiagnosticsBack');if(!back){back=document.createElement('button');back.id='mairfmDiagnosticsBack';back.type='button';back.className='mairfm-diagnostics-back hidden';back.textContent='\u2190 Terug naar Spotify verbinden';back.addEventListener('click',()=>window.MAIRFoundation?.activate?.('radio'));pane.insertBefore(back,pane.firstChild)}const weather=$('weatherMention')?.closest('label');if(weather)weather.classList.add('mairfm-release-hidden');const voice=$('voiceMode')?.closest('article.card');if(voice)voice.classList.add('mairfm-diagnostic-only');const liveLocation=[...pane.querySelectorAll('article.card')].filter(c=>/DJ CONTEXT|LIVE CONTEXT|weer & radio|plaats\/regio/i.test(c.textContent||''));liveLocation.forEach(c=>c.classList.add('mairfm-release-hidden'));const discovery=$('discovery')?.closest('article.card');if(discovery){const h=discovery.querySelector('h3');if(h)setText(h,'Hoeveel nieuwe muziek?');const row=discovery.querySelector('.row span');if(row)setText(row,'Nieuwe muziek')}
  const auto=$('autoProgram')?.closest('article.card');auto?.setAttribute('data-mairfm-settings-section','Radio');const djCard=$('talk')?.closest('article.card');djCard?.setAttribute('data-mairfm-settings-section','DJ');if(djCard){const h=djCard.querySelector('h3');if(h)setText(h,'Je MAIRFM DJ');const facts=$('facts')?.closest('label')?.querySelector('b');if(facts)setText(facts,'Muziekverhalen en feiten');const time=$('timeMention')?.closest('label')?.querySelector('b');if(time)setText(time,'Tijd en radioklok');$('talk')?.setAttribute('max','2');if(Number($('talk')?.value)>2)$('talk').value='2'}
  const profiles=$('mairDJProfiles');if(profiles){profiles.setAttribute('data-mairfm-settings-section','DJ');const intro=profiles.querySelector('.mair-profile-intro');if(intro)setText(intro,'Kies de stem en stijl die MAIRFM presenteert.')}
  const data=$('clearHistory')?.closest('article.card'),top40=$('jfmTop40Settings'),controls=$('mairUserControlsCard'),rotation=$('mairRotationCard'),myMair=$('mairMyMair');data?.setAttribute('data-mairfm-settings-section','App');top40?.setAttribute('data-mairfm-settings-section','App');controls?.setAttribute('data-mairfm-settings-section','App');myMair?.setAttribute('data-mairfm-settings-section','Mijn MAIR');rotation?.setAttribute('data-mairfm-settings-section','DJ');let toast=$('mairfmSettingsToast');if(!toast){toast=document.createElement('div');toast.id='mairfmSettingsToast';toast.className='mairfm-settings-toast hidden';toast.setAttribute('aria-live','polite');pane.insertBefore(toast,pane.firstChild)}
  pane.querySelectorAll('.mairfm-settings-section-title').forEach(x=>x.remove());const hub=$('mairDiagnosticsHub'),candidate=hub?.parentElement===pane?hub:hub?.closest('article.card'),anchor=candidate?.parentElement===pane?candidate:pane.querySelector('.versionbox');for(const section of ['Radio','DJ','Mijn MAIR','App']){const cards=[...pane.querySelectorAll(`article.card[data-mairfm-settings-section="${section}"]`)];if(!cards.length)continue;const heading=document.createElement('h2');heading.className='mairfm-settings-section-title';heading.dataset.mairfmSection=section;heading.textContent=section;pane.insertBefore(heading,anchor||null);for(const card of cards)pane.insertBefore(card,anchor||null)}
}
function showToast(text){const toast=$('mairfmSettingsToast');if(!toast)return;setText(toast,text);toast.classList.remove('hidden');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>toast.classList.add('hidden'),2600)}
function openDiagnostics(){window.MAIRFoundation?.activate?.('settings');setTimeout(()=>{window.MAIRDiagnosticsHub?.open?.();$('mairDiagnosticsHub')?.scrollIntoView?.({behavior:'smooth',block:'start'})},80)}
function renderNotice(error,recovery){const box=$('mairfmNotice');if(!box)return;if(recovery&&!error){box.className='mairfm-notice success';setText($('mairfmNoticeTitle'),'We zijn weer live.');setText($('mairfmNoticeMessage'),'De muziekverbinding is hersteld.');$('mairfmNoticeActions').replaceChildren();setTimeout(()=>box.classList.add('hidden'),4000);return}if(!error){box.className='mairfm-notice hidden';return}box.className=`mairfm-notice ${error.severity}`;setText($('mairfmNoticeTitle'),error.title);setText($('mairfmNoticeMessage'),error.message);const actions=$('mairfmNoticeActions');actions.replaceChildren();const labels={retry:'Opnieuw proberen',device:'Op dit apparaat afspelen',resume:'Verder luisteren',reconnect:'Opnieuw verbinden','retry-station':'Opnieuw proberen',diagnostics:'Bekijk Diagnostics'};for(const action of [error.primaryAction,error.secondaryAction].filter(Boolean)){const b=document.createElement('button');b.type='button';b.dataset.mairfmErrorAction=action;b.textContent=labels[action]||'Opnieuw proberen';actions.appendChild(b)}}
function render(state){lastState=state;brand();setupNavigation();const station=`${state.station.label} • LIVE`;setText($('mairfmStationLive'),station);document.body.dataset.mairfmAppState=state.appState;const heading=document.querySelector('.mair-eyebrow');if(heading)setText(heading,`MAIRFM · ${station}`);const setup=$('setup');setup?.classList.toggle('hidden',state.spotifyConnection.connected);$('mairfmDiagnosticsBack')?.classList.toggle('hidden',state.spotifyConnection.connected);const welcome=$('mairfmWelcome'),seen=localStorage.getItem(SEEN)==='1';welcome?.classList.toggle('hidden',!state.spotifyConnection.connected||seen||!!state.track);if(state.track&&state.playbackState.isPlaying&&!seen)localStorage.setItem(SEEN,'1');
  const publicDj=state.djPublicState;$('mairfmDjPublic')?.setAttribute('data-state',publicDj.state);setText($('mairfmDjLabel'),publicDj.label);setText($('mairfmDjDetail'),publicDj.state==='QUIET'?'MAIRFM kiest zelf de juiste radiomomenten.':publicDj.detail||'De muziek blijft ondertussen centraal.');
  const status={DISCONNECTED:'Verbind Spotify om te beginnen',CONNECTING:'Spotify verbinden…',STARTING:'Station starten…',RECOVERING:'Muziekverbinding herstellen…',GESTURE_REQUIRED:'Tik om audio te hervatten',OFFLINE:'Wachten op internet…',EMPTY:'Nog niets op de radio',PAUSED:'Gepauzeerd',PLAYING:''}[state.appState]||'';setText($('mairfmPlaybackStatus'),state.station.pending||status);$('mairfmPlaybackStatus')?.classList.toggle('hidden',!state.station.pending&&!status);
  for(const [id,action]of [['next','next'],['prev','previous'],['play',state.playbackState.isPlaying?'pause':'resume']]){const b=$(id),pending=state.playbackPendingAction===action;b?.classList.toggle('pending',pending);b?.setAttribute('aria-busy',pending?'true':'false')}
  const play=$('play');if(play)play.setAttribute('aria-label',state.playbackState.isPlaying?'Muziek pauzeren':'Muziek afspelen');const list=$('mair-up-next-list');if(list&&!state.nextTrack)list.innerHTML='<div class="mair-up-empty">Wordt zo bepaald</div>';renderNotice(state.recoverableError,state.recoveryJustSucceeded)
}
function actions(){document.addEventListener('click',e=>{const action=e.target.closest?.('[data-mairfm-error-action]')?.dataset.mairfmErrorAction;if(action){if(action==='diagnostics')openDiagnostics();else if(action==='resume'){const p=window.JFMPlayback;if(typeof p?.playPause==='function')Promise.resolve(p.playPause()).catch(()=>{});else if(typeof p?.resume==='function')Promise.resolve(p.resume()).catch(()=>{});else $('play')?.click()}else if(action==='reconnect'||action==='retry')$('connect')?.click();else if(action==='device')window.JFMPlayback?.ensureDevice?.().then(()=>window.JFMPlayback?.recover?.('ux-device'));else if(action==='retry-station'){const id=lastState?.station?.id;window.MAIRStationController?.select?.(id)}}const settings=e.target.closest?.('#mairfmSettingsShortcut');if(settings)window.MAIRFoundation?.activate?.('settings')},false);$('talk')?.addEventListener('input',()=>{const labels=['Minder','Normaal','Meer'];setText($('talkValue'),labels[Number($('talk').value)]||'Normaal');showToast(`DJ praat nu ${labels[Number($('talk').value)]?.toLowerCase()||'normaal'}. Wordt vanaf het volgende radiomoment gebruikt.`)});$('facts')?.addEventListener('change',()=>showToast($('facts').checked?'Muziekverhalen en feiten staan aan':'Muziekverhalen en feiten staan uit'));$('timeMention')?.addEventListener('change',()=>showToast($('timeMention').checked?'Tijd en radioklok staan aan':'Tijd en radioklok staan uit'));$('jingles')?.addEventListener('change',()=>showToast($('jingles').checked?'MAIRFM-jingles staan aan':'MAIRFM-jingles staan uit'));document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;if(document.body.classList.contains('mair-request-open'))document.querySelector('.mair-request-close')?.click();else $('mairDJSheet')?.classList.add('hidden')});window.addEventListener('mair:channelchange',e=>{if(e.detail?.loading)showToast('Station wisselen…')});window.addEventListener('mair:station-selected',e=>showToast(`${String(e.detail?.label||'Station').replace(/^MAIR\s+/,'')} speelt`));window.addEventListener('mair:settings-feedback',e=>showToast(String(e.detail?.message||'Instelling bijgewerkt.')));document.addEventListener('click',e=>{if(e.target.closest?.('[data-mair-tab="requests"]')||e.target.closest?.('#mairfmRequest'))setTimeout(()=>$('searchInput')?.focus(),180)},false)}
function removeLegacyReconcilers(){try{window.__mairReconcileObserver?.disconnect?.();window.__mairLegacyQueueObserver?.disconnect?.()}catch{}document.querySelector('[data-tab="personal"]')?.remove();$('tab-personal')?.remove()}
function install(){if(installed)return;installed=true;document.body.classList.add('mairfm-ux-v1');brand();buildOnboarding();buildRadio();buildWelcome();cleanSettings();setupNavigation();removeLegacyReconcilers();watchSecondaryFeatures();actions();window.MAIRUXState?.subscribe?.(render);setTimeout(()=>{cleanSettings();setupNavigation();removeLegacyReconcilers();organizeSecondaryFeatures();render(window.MAIRUXState?.get?.()||{})},1200);window.MAIRUX={version:'mairfm-ux-v1',render,openDiagnostics,get state(){return lastState}};window.MAIRRuntime?.register?.('mair-ux-v1',{version:'mairfm-ux-v1',owner:'app-shell-public-ui'})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,0),{once:true});else setTimeout(install,0);
})();
