// MAIR Sleep — calm full-screen sleep controls without taking playback ownership.
(()=>{
'use strict';
if(window.MAIRSleep)return;
const KEY='jfm_sleep_timer_v1',$=id=>document.getElementById(id);
let state=read(),tickTimer=0,stopBusy=false,lastError='',lastStoppedAt=0,open=false;
function read(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(!x||typeof x!=='object')return null;if(x.mode==='time'&&Number(x.at||0)>Date.now())return x;if(x.mode==='after-track'&&x.trackId)return x}catch{}return null}
function save(v){state=v;try{localStorage.setItem(KEY,JSON.stringify(v))}catch{}emit();render()}
function clear(){state=null;try{localStorage.setItem(KEY,'null')}catch{}emit();render()}
function playback(){return window.JFMPlaybackState?.get?.()||null}
function track(){const p=playback()||{};return{trackId:String(p.trackId||''),uri:String(p.uri||''),title:String($('title')?.textContent||'MAIR'),artist:String($('artist')?.textContent||'')}}
function remainingMs(){return state?.mode==='time'?Math.max(0,Number(state.at||0)-Date.now()):0}
function fmt(ms){const total=Math.max(0,Math.ceil(ms/1000)),m=Math.floor(total/60),s=total%60;return`${m}:${String(s).padStart(2,'0')}`}
function status(){return{version:'mair-sleep-v1.2',active:!!state,mode:state?.mode||'',endsAt:state?.mode==='time'?Number(state.at||0):0,remainingMs:remainingMs(),trackId:state?.trackId||'',open,lastError,lastStoppedAt}}
function emit(){try{window.dispatchEvent(new CustomEvent('mair:sleep',{detail:status()}))}catch{}}
async function stopRadio(reason='sleep-timer'){
  if(stopBusy)return false;stopBusy=true;lastError='';const truth=window.JFMPlaybackState,before=truth?.get?.();let op=0;
  try{
    try{op=truth?.begin?.('pause',{expectedUri:String(before?.uri||''),timeoutMs:10000})||0;truth?.setExpectedLive?.(false,reason)}catch{}
    const pause=window.JFMPlayback?.pause;
    if(typeof pause!=='function')throw Error('MAIR playback-controller is nog niet beschikbaar');
    const ok=await pause();if(!ok)throw Error(window.JFMPlayback?.health?.lastError||'Spotify kon niet worden gepauzeerd');
    lastStoppedAt=Date.now();clear();
    try{window.dispatchEvent(new CustomEvent('mair:sleep-complete',{detail:{reason,at:lastStoppedAt}}))}catch{}
    return true
  }catch(e){if(before?.expectedLive)try{truth?.setExpectedLive?.(true,'sleep-pause-failed')}catch{};lastError=String(e?.message||e||'Sleep timer kon MAIR niet pauzeren');emit();render();return false}
  finally{try{if(op)truth?.end?.(op,{error:lastError})}catch{};stopBusy=false}
}
function scheduleMinutes(minutes){const n=Math.max(1,Math.min(240,Number(minutes)||0));lastError='';save({mode:'time',at:Date.now()+n*60000,minutes:n,createdAt:Date.now()});ensureTick();return status()}
function scheduleAfterTrack(){const t=track();if(!t.trackId){lastError='Start eerst een nummer voordat je “na dit nummer” gebruikt.';emit();render();return false}lastError='';save({mode:'after-track',trackId:t.trackId,createdAt:Date.now(),title:t.title,artist:t.artist});ensureTick();return true}
function cancel(){clear();lastError='';return true}
function ensureTick(){if(tickTimer)return;tickTimer=setInterval(()=>{if(state?.mode==='time'&&Number(state.at||0)<=Date.now())stopRadio('timer').catch(()=>{});if(open)render()},500)}
function nowClock(){return new Date().toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'})}
async function activateSleepStation(){lastError='';const select=window.MAIRStationController?.select||window.JFMMusicChoice?.chooseChannel;if(typeof select!=='function'){lastError='MAIR SLEEP is nog niet klaar. Open het muziekkanaal opnieuw.';render();return false}try{const ok=await select.call(window.MAIRStationController||window.JFMMusicChoice,'sleep');if(ok===false)throw Error('MAIR SLEEP kon niet worden gestart');render();return true}catch(e){lastError=String(e?.message||e);render();return false}}
function ensureStyle(){if($('mairSleepStyle'))return;const s=document.createElement('style');s.id='mairSleepStyle';s.textContent=`
.mair-sleep-launch{width:100%;margin-top:10px;border:1px solid #282d36;background:#11151b;color:#f4f6f8;border-radius:16px;padding:14px 16px;text-align:left;font-weight:800}.mair-sleep-launch span{display:block;color:#8e98a7;font-size:12px;font-weight:600;margin-top:3px}
.mair-sleep-overlay{position:fixed;inset:0;z-index:12000;background:radial-gradient(circle at 50% 12%,#151a25 0,#090b10 44%,#040507 100%);color:#f7f8fa;overflow:auto;padding:calc(env(safe-area-inset-top) + 18px) 18px calc(env(safe-area-inset-bottom) + 26px);transition:filter .5s ease,opacity .5s ease}.mair-sleep-overlay.mair-sleep-dim{filter:brightness(.72)}.mair-sleep-wrap{max-width:620px;margin:0 auto;min-height:calc(100dvh - 60px);display:flex;flex-direction:column}.mair-sleep-head{display:flex;align-items:center;justify-content:space-between}.mair-sleep-close{width:46px;height:46px;border-radius:99px}.mair-sleep-clock{font-size:clamp(64px,22vw,118px);line-height:.95;font-weight:800;letter-spacing:-.06em;margin:44px 0 8px}.mair-sleep-date{color:#8e98a7;margin-bottom:34px}.mair-sleep-now{padding:16px 0;border-top:1px solid #202632;border-bottom:1px solid #202632}.mair-sleep-now small{display:block;color:#778293;letter-spacing:.13em;font-size:10px;font-weight:800}.mair-sleep-now b,.mair-sleep-now span{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.mair-sleep-now b{font-size:21px;margin-top:6px}.mair-sleep-now span{color:#9aa4b3;margin-top:4px}.mair-sleep-status{text-align:center;margin:34px 0 18px}.mair-sleep-status b{display:block;font-size:32px}.mair-sleep-status span{display:block;color:#8e98a7;margin-top:5px}.mair-sleep-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.mair-sleep-grid button,.mair-sleep-after,.mair-sleep-station,.mair-sleep-cancel{border:1px solid #29303b;background:#11151c;color:#f4f6f8;border-radius:16px;padding:14px 9px;font-weight:800}.mair-sleep-after,.mair-sleep-station,.mair-sleep-cancel{width:100%;margin-top:10px}.mair-sleep-station{border-color:#33495e;background:#101922}.mair-sleep-cancel{color:#ffb4b4}.mair-sleep-note{margin-top:auto;padding-top:30px;color:#6f7988;text-align:center;font-size:12px}.mair-sleep-error{color:#ffb4b4;text-align:center;min-height:20px;margin-top:10px}@media(max-width:520px){.mair-sleep-grid{grid-template-columns:repeat(2,1fr)}.mair-sleep-clock{margin-top:30px}}
`;document.head.appendChild(s)}
function ensureUI(){ensureStyle();const radio=$('tab-radio');if(radio&&!$('mairSleepOpen')){const actions=$('djNow')?.closest('.grid2'),b=document.createElement('button');b.id='mairSleepOpen';b.type='button';b.className='mair-sleep-launch';b.innerHTML='🌙 Sleep <span id="mairSleepLaunchStatus">Timer instellen</span>';b.onclick=()=>setOpen(true);if(actions)actions.insertAdjacentElement('afterend',b);else radio.appendChild(b)}if(!$('mairSleepOverlay')){const o=document.createElement('div');o.id='mairSleepOverlay';o.className='mair-sleep-overlay';o.hidden=true;o.innerHTML=`<div class="mair-sleep-wrap"><div class="mair-sleep-head"><div><div class="kicker">MAIR SLEEP</div><b>Sleep timer</b></div><button id="mairSleepClose" class="secondary mair-sleep-close" type="button">×</button></div><div id="mairSleepClock" class="mair-sleep-clock">--:--</div><div id="mairSleepDate" class="mair-sleep-date"></div><div class="mair-sleep-now"><small>NU OP MAIR</small><b id="mairSleepTitle">MAIR</b><span id="mairSleepArtist"></span></div><div class="mair-sleep-status"><b id="mairSleepRemaining">Geen timer</b><span id="mairSleepMode">Kies wanneer MAIR moet stoppen</span></div><div class="mair-sleep-grid"><button type="button" data-sleep-minutes="15">15 min</button><button type="button" data-sleep-minutes="30">30 min</button><button type="button" data-sleep-minutes="45">45 min</button><button type="button" data-sleep-minutes="60">60 min</button></div><button id="mairSleepStation" type="button" class="mair-sleep-station">🌌 Luister naar MAIR SLEEP</button><button id="mairSleepAfterTrack" type="button" class="mair-sleep-after">Stop na dit nummer</button><button id="mairSleepCancel" type="button" class="mair-sleep-cancel">Timer uitzetten</button><div id="mairSleepError" class="mair-sleep-error"></div><div class="mair-sleep-note">MAIR pauzeert via de bestaande playback-controller. Je wachtrij blijft behouden.</div></div>`;document.body.appendChild(o);$('mairSleepClose').onclick=()=>setOpen(false);$('mairSleepStation').onclick=()=>activateSleepStation();$('mairSleepAfterTrack').onclick=()=>scheduleAfterTrack();$('mairSleepCancel').onclick=()=>cancel();o.querySelectorAll('[data-sleep-minutes]').forEach(b=>b.onclick=()=>scheduleMinutes(Number(b.dataset.sleepMinutes)));let dimTimer=0;const wake=()=>{o.classList.remove('mair-sleep-dim');clearTimeout(dimTimer);if(open)dimTimer=setTimeout(()=>o.classList.add('mair-sleep-dim'),8000)};['pointerdown','touchstart','click'].forEach(n=>o.addEventListener(n,wake,{passive:true}));wake()}}
function render(){ensureUI();const t=track(),clock=$('mairSleepClock'),date=$('mairSleepDate'),title=$('mairSleepTitle'),artist=$('mairSleepArtist'),remaining=$('mairSleepRemaining'),mode=$('mairSleepMode'),err=$('mairSleepError'),launch=$('mairSleepLaunchStatus');if(clock)clock.textContent=nowClock();if(date)date.textContent=new Date().toLocaleDateString('nl-NL',{weekday:'long',day:'numeric',month:'long'});if(title)title.textContent=t.title||'MAIR';if(artist)artist.textContent=t.artist||'';if(state?.mode==='time'){const left=remainingMs();if(remaining)remaining.textContent=fmt(left);if(mode)mode.textContent=`MAIR stopt om ${new Date(state.at).toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'})}`;if(launch)launch.textContent=`Nog ${fmt(left)}`}else if(state?.mode==='after-track'){if(remaining)remaining.textContent='Na dit nummer';if(mode)mode.textContent=state.title?`${state.title} is de laatste track`:'MAIR stopt bij het einde van deze track';if(launch)launch.textContent='Stopt na dit nummer'}else{if(remaining)remaining.textContent='Geen timer';if(mode)mode.textContent='Kies wanneer MAIR moet stoppen';if(launch)launch.textContent='Timer instellen'}if(err)err.textContent=lastError||'';$('mairSleepCancel')?.toggleAttribute('hidden',!state)}
function setOpen(v){ensureUI();open=!!v;const o=$('mairSleepOverlay');if(o)o.hidden=!open;if(open){render();document.body.style.overflow='hidden'}else document.body.style.overflow='';emit()}
function onNatural(detail={}){if(state?.mode!=='after-track')return;const ended=String(detail.trackId||detail.endedTrackId||'');if(ended&&ended===String(state.trackId||''))stopRadio('after-track').catch(()=>{})}
function boot(){ensureUI();ensureTick();render();window.addEventListener('jfm:natural-track-end',e=>onNatural(e.detail||{}));window.addEventListener('jfm:natural-next-ready',e=>onNatural(e.detail||{}));window.addEventListener('jfm:trackchange',render);window.addEventListener('mair:channelchange',render);window.addEventListener('pageshow',()=>{state=read();render()});setInterval(()=>{if(open||state)render()},1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.MAIRSleep={version:'mair-sleep-v1.2',open:()=>setOpen(true),close:()=>setOpen(false),scheduleMinutes,scheduleAfterTrack,cancel,status,stop:stopRadio,activateSleepStation};
})();