// Mijn MAIR — evidence-based personal listening summary from local station memory.
(()=>{
'use strict';
if(window.MAIRMyMair)return;
const $=id=>document.getElementById(id),read=(key,fallback)=>{try{const value=JSON.parse(localStorage.getItem(key)||'null');return value&&typeof value==='object'?value:fallback}catch{return fallback}},text=(id,value)=>{const e=$(id);if(e)e.textContent=String(value)};
function suite(){try{return window.JFMRadioSuite?.state?.()||read('jfm_radio_suite',{})}catch{return read('jfm_radio_suite',{})}}
function telemetry(){return read('jfm_top40_telemetry_v1',{})}
function entryScore(e={}){return Number(e.listenMs||0)/60000+Number(e.completed||0)*4+Number(e.starts||0)*1.5+Number(e.likes||0)*5+Number(e.requests||0)*5}
function favorites(){const entries=Object.values(telemetry()).filter(e=>e&&typeof e==='object'),artists=new Map();for(const e of entries){const score=entryScore(e);for(const artist of (e.artists||[]).map(String).filter(Boolean))artists.set(artist,(artists.get(artist)||0)+score)}const artist=[...artists.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]||'Nog in opbouw',track=entries.sort((a,b)=>entryScore(b)-entryScore(a))[0];return{artist,track:track?.name||'Nog in opbouw'}}
function duration(minutes){const total=Math.max(0,Math.round(Number(minutes)||0));if(total<60)return`${total} min`;const hours=Math.floor(total/60),rest=total%60;return rest?`${hours}u ${rest}m`:`${hours} uur`}
function radioDna(s={}){const signals=Number(s.likes||0)+Number(s.dislikes||0);if(Number(s.tracks||0)<5)return{label:'In opbouw',copy:'Blijf luisteren; MAIRFM leert welke muziek jouw station maakt.'};if(Number(s.discoveries||0)>=5)return{label:'Ontdekker',copy:'Je geeft nieuwe muziek opvallend vaak een plek in je station.'};if(signals>=12)return{label:'Muziekregisseur',copy:'Je stuurt actief bij en MAIRFM gebruikt die signalen in de rotatie.'};if(Number(s.minutes||0)>=600)return{label:'Vaste luisteraar',copy:'Je station heeft inmiddels een stevig persoonlijk luisterprofiel.'};if(Number(s.likes||0)>=5)return{label:'Smaakmaker',copy:'Je positieve keuzes geven artiesten en tracks extra prioriteit.'};return{label:'Persoonlijke mix',copy:'Je station wordt met ieder nummer beter afgestemd op jouw smaak.'}}
function ensure(){const pane=$('tab-settings');if(!pane)return null;let card=$('mairMyMair');if(card)return card;card=document.createElement('article');card.id='mairMyMair';card.className='card mair-my-mair';card.dataset.mairfmSettingsSection='Mijn MAIR';card.innerHTML='<div class="kicker">PERSOONLIJK</div><div class="mair-my-head"><div><h3>Jouw station in cijfers</h3><p>Jouw luistergedrag maakt dit station persoonlijk.</p></div><span id="mairMyDna">In opbouw</span></div><div class="mair-my-stats"><div><b id="mairMyTracks">0</b><span>nummers gehoord</span></div><div><b id="mairMyTime">0 min</b><span>luistertijd</span></div><div><b id="mairMyLikes">0</b><span>keer meer hiervan</span></div><div><b id="mairMyDiscoveries">0</b><span>ontdekkingen</span></div></div><div class="mair-my-highlights"><p><span>Meest gedraaide artiest</span><b id="mairMyArtist">Nog in opbouw</b></p><p><span>Jouw nummer</span><b id="mairMyTrack">Nog in opbouw</b></p><p><span>Radio-DNA</span><b id="mairMyDnaCopy">MAIRFM leert je smaak.</b></p><p><span>Aangevraagd</span><b id="mairMyRequests">0 nummers</b></p></div>';const anchor=$('jfmTop40Settings')||$('clearHistory')?.closest('article.card')||pane.querySelector('.versionbox');pane.insertBefore(card,anchor||null);return card}
function render(){if(!ensure())return null;const s=suite(),fav=favorites(),dna=radioDna(s);text('mairMyTracks',Number(s.tracks||0));text('mairMyTime',duration(s.minutes));text('mairMyLikes',Number(s.likes||0));text('mairMyDiscoveries',Number(s.discoveries||0));text('mairMyArtist',fav.artist);text('mairMyTrack',fav.track);text('mairMyDna',dna.label);text('mairMyDnaCopy',dna.copy);const requests=Number(s.requests||0);text('mairMyRequests',`${requests} nummer${requests===1?'':'s'}`);return{...s,favorites:fav,dna}}
function boot(){ensure();render();for(const event of ['jfm:trackchange','mair:request-confirmed','mair:taste-feedback','jfm:top40-cleared','mair:station-selected'])window.addEventListener(event,()=>setTimeout(render,120));document.addEventListener('visibilitychange',()=>{if(!document.hidden)render()});setInterval(render,15000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.MAIRMyMair={version:'my-mair-v1',render,snapshot:()=>render(),radioDna};
})();
