(()=>{
'use strict';
if(window.MAIRDJ?.version?.startsWith('v3.4'))return;
const $=id=>document.getElementById(id),wait=ms=>new Promise(r=>setTimeout(r,ms));
const TALK_RANGES=[[6,9],[3,5],[2,4],[1,3]],LABELS=['Weinig','Normaal','Radio','Veel'];
const recent=[];
let target=4,count=0,prepared=null,preparePromise=null,planGeneration=0,manualArmed=false,skipNextBreak=false,busy=false,lastNaturalSig='',pendingUnexpected=null,handoffOp=0,deferred=0;
let state={phase:'COUNTING',reason:'boot',error:'',updatedAt:Date.now(),writer:null,voice:null,lastAirAt:0,lastAirText:'',lastMissAt:0,lastMissReason:'',played:0,missed:0};
const version='v3.4-deferred-breaks-memory-imaging';
const truth=()=>window.JFMPlaybackState?.get?.()||null;
const truthApi=()=>window.JFMPlaybackState||null;
const profile=()=>window.MAIRDJProfiles?.current||window.MAIRCurrentDJ||{id:'josh',name:'Josh',role:'MAIR DJ'};
const mode=()=>Math.max(0,Math.min(3,Number($('talk')?.value??1)||0));
const activeStation=()=>document.getElementById('mairActiveStation')?.textContent||window.MAIRStationController?.active?.()?.label||'MAIR';
const safeErr=e=>String(e?.message||e||'onbekende fout').slice(0,260);
const cleanLabel=t=>{const name=String(t?.name||'').trim(),artists=(t?.artists||[]).map(x=>String(x||'').trim()).filter(Boolean).join(', ');return name&&artists?`${artists} met ${name}`:name||artists};
const audioStatus=()=>window.JFMDJAudio?.status||{};
const currentTrackId=()=>String(truth()?.trackId||'');
function chooseTarget(){const r=TALK_RANGES[mode()]||TALK_RANGES[1];return Math.floor(Math.random()*(r[1]-r[0]+1))+r[0]}
function remaining(){return manualArmed?0:Math.max(0,target-count)}
function due(){return manualArmed||count>=target}
function transportMode(){const p=window.JFMPlayback;return p?.djPause&&p?.djResume&&p?.djRewind?'sdk-first':'web-api-fallback'}
function diagnostics(){const a=audioStatus();return{version,guard:'writer-memory-imaging-handoff-v4-auto-schedule-preserve',phase:state.phase,reason:state.reason,error:state.error,remaining:remaining(),target,count,pendingAir:due()||state.phase==='ARMED',busy,prepared:prepared?{manual:prepared.manual,createdAt:prepared.createdAt,originTrackId:prepared.originTrackId,nextHintId:prepared.nextHintId,voiceProfileId:prepared.voiceProfileId,showId:prepared.show?.id||''}:null,manualArmed,skipNextBreak,deferred,audioUnlocked:!!a.audioUnlocked,audioRoute:a.playbackMode||'',transport:transportMode(),writer:state.writer,voice:state.voice,lastAirAt:state.lastAirAt,lastAirText:state.lastAirText,lastMissAt:state.lastMissAt,lastMissReason:state.lastMissReason,played:state.played,missed:state.missed,dj:profile(),memory:window.MAIRDJMemory?.context?.(profile()?.id)||null,imaging:window.MAIRImaging?.status?.()||null}}
function emit(){state.updatedAt=Date.now();const detail=diagnostics();try{window.dispatchEvent(new CustomEvent('mair:dj-v2-state',{detail}))}catch{}try{window.dispatchEvent(new CustomEvent('mair:dj-schedule',{detail}))}catch{}render()}
function setPhase(phase,reason='',error=''){state={...state,phase,reason,error};emit()}
function render(){const el=$('talkValue');if(!el)return;const label=LABELS[mode()]||'Normaal',rem=remaining();if(state.phase==='PREPARING')el.textContent=`${label} · DJ wordt voorbereid`;else if(state.phase==='ARMED')el.textContent=`${label} · DJ klaar voor volgende overgang`;else if(state.phase==='HANDOFF'||state.phase==='SPEAKING'||state.phase==='RESTORING')el.textContent=`${label} · DJ live`;else if(due())el.textContent=`${label} · DJ schuift door naar volgende overgang`;else el.textContent=`${label} · DJ over ${rem} nummer${rem===1?'':'s'}`;el.dataset.djRemaining=String(rem);el.dataset.djPhase=state.phase}
function clearPendingUnexpected(){if(pendingUnexpected?.timer)clearTimeout(pendingUnexpected.timer);pendingUnexpected=null}
function resetPlan(reason='complete'){clearPendingUnexpected();planGeneration++;prepared=null;preparePromise=null;manualArmed=false;skipNextBreak=false;target=chooseTarget();count=0;state.error='';setPhase('COUNTING',reason)}
function miss(reason,error=''){state.lastMissAt=Date.now();state.lastMissReason=String(reason||'missed');state.missed++;planGeneration++;prepared=null;preparePromise=null;manualArmed=false;target=chooseTarget();count=0;setPhase('COUNTING',reason,String(error||''))}
async function unlock(){if(typeof window.JFMDJAudio?.unlock!=='function')throw Error('Centrale MAIR audio-engine is niet geladen');return !!(await window.JFMDJAudio.unlock())}
function fromSpotifyItem(x){if(!x)return null;return{id:x.id||'',uri:x.uri||'',name:x.name||'',artists:(x.artists||[]).map(a=>a?.name||a).filter(Boolean),release:x.album?.release_date||x.release||'',request:typeof window.jfmIsRequest==='function'?!!window.jfmIsRequest(x):false}}
async function liveSnapshot(){const live=await api('/me/player').catch(()=>null);if(!live?.item)return null;return{live,current:fromSpotifyItem(live.item)}}
async function snapshot(){const base=await liveSnapshot();if(!base)return null;let next=null;try{const q=await api('/me/player/queue');next=fromSpotifyItem(q?.queue?.[0])}catch{}return{...base,next}}
async function stableCurrent(expectedId='',timeoutMs=2400,playing=true){const until=Date.now()+timeoutMs;let last=null,lastId='',stable=0;while(Date.now()<until){last=await liveSnapshot().catch(()=>null);const id=String(last?.current?.id||''),playOk=playing===null||!!last?.live?.is_playing===!!playing;if(playOk&&last?.live?.item?.uri&&(!expectedId||id===String(expectedId))){stable=id===lastId?stable+1:1;lastId=id;if(stable>=2)return last}else{stable=0;lastId=id}await wait(110)}throw Error(last?.live?.item?.uri?'Spotify overgang is niet stabiel':'Spotify speelt niet bij DJ-overgang')}
async function writerRequest(body,timeoutMs=18000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeoutMs);try{return await fetch('/api/dj-writer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:c.signal})}finally{clearTimeout(timer)}}
function fallbackBreak(ctx){const current=cleanLabel(ctx.current),next=cleanLabel(ctx.next);if(current&&next)return`Dat was ${current}. Nu hoor je ${next}, hier op MAIR.`;if(next)return`Nu hoor je ${next}, hier op MAIR.`;if(current)return`Dat was ${current}. Je luistert naar MAIR.`;return''}
function usableDutch(text){const x=String(text||'').replace(/\s+/g,' ').trim();if(!x||x.length>900||/\b(?:artificial intelligence|language model|api|groq|fish audio|metadata|prompt)\b/i.test(x))return false;return(x.match(/\b(?:de|het|een|je|we|dit|dat|nu|straks|hier|naar|met|van|op|voor|luistert|hoort|hoorde)\b/gi)||[]).length>=2}
async function writeBreak(ctx,manual=false){const p=profile(),clock=window.JFMStationClock?.current?.()||{},memory=window.MAIRDJMemory?.context?.(p.id)||{},persistent=Array.isArray(memory.recentDJ)?memory.recentDJ:[],recentDJ=[...recent,...persistent].filter((x,i,a)=>x&&a.indexOf(x)===i).slice(0,12),news=window.MAIRLiveNews?.take?.()||null,body={dj:p,breakType:manual?'manual-next':'automatic-transition',length:'short',previousTrack:ctx.previous||null,currentTrack:ctx.current||null,nextTrack:ctx.next||null,time:new Date().toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'}),station:activeStation(),show:clock.show||null,clockPhase:clock.phase||'',memory,recentDJ,news};try{const r=await writerRequest(body),d=await r.json().catch(()=>({}));if(!r.ok||!usableDutch(d?.text))throw Error(d?.error||(!d?.text?'DJ writer gaf geen tekst':'DJ writer gaf onveilige of niet-Nederlandse tekst'));state.writer={provider:d.provider||'groq',model:d.model||'',text:d.text,error:'',show:d.show||clock.show?.name||'',news:!!d.newsUsed};emit();return d.text}catch(e){const text=fallbackBreak(ctx);if(!text)throw e;state.writer={provider:'local-fallback',model:'deterministic-nl-v1',text,error:safeErr(e)};emit();return text}}
async function renderVoice(text){if(typeof window.prepareSpeech!=='function')throw Error('Centrale MAIR Voice Engine is niet geladen');const ok=await window.prepareSpeech(String(text).slice(0,1000),false);if(!ok)throw Error(audioStatus().error||'Fish Audio kon de DJ-break niet voorbereiden');const a=audioStatus();state.voice={provider:a.provider||'fish',voiceId:a.voiceId||'',model:a.model||'',route:'central'};emit();return true}
function scheduleDeferredPrepare(manual,originTrackId,reason){const id=String(originTrackId||currentTrackId()||'');if(!id||busy||prepared||preparePromise)return false;setTimeout(()=>{if(busy||prepared||preparePromise||!due()||currentTrackId()!==id)return;prepare({manual:!!manual,originTrackId:id}).catch(()=>{})},40);setPhase('COUNTING',reason);return true}
function deferBreak(manual,originTrackId,reason){deferred++;if(manual)manualArmed=true;else count=Math.max(count,target);state.error='';state.lastMissReason=String(reason||'break-deferred');scheduleDeferredPrepare(manual,originTrackId,reason);emit();return false}
function rearmOwed(manual,originTrackId,reason,error=''){deferred++;state.lastMissAt=Date.now();state.lastMissReason=String(reason||'break-missed');state.missed++;planGeneration++;prepared=null;preparePromise=null;if(manual)manualArmed=true;else count=Math.max(count,target);state.error=String(error||'');setPhase('COUNTING',reason,String(error||''));scheduleDeferredPrepare(!!manual,String(originTrackId||currentTrackId()||''),reason);return false}
async function prepare({manual=false,originTrackId=currentTrackId(),previous=null}={}){
  originTrackId=String(originTrackId||'');if(!originTrackId||busy)return null;
  if(prepared&&prepared.originTrackId===originTrackId&&prepared.manual===!!manual)return prepared;
  if(preparePromise)return preparePromise;
  const generation=planGeneration;setPhase('PREPARING',manual?'manual':'automatic');
  preparePromise=(async()=>{try{const s=await snapshot();if(!s?.current||String(s.current.id)!==originTrackId)throw Error('Track veranderde vóór voorbereiding');const voiceProfileId=String(profile()?.id||'josh'),clock=window.JFMStationClock?.current?.()||{},text=await writeBreak({previous,current:s.current,next:s.next},manual);await renderVoice(text);if(generation!==planGeneration||currentTrackId()!==originTrackId)return null;prepared={text,manual:!!manual,createdAt:Date.now(),originTrackId,nextHintId:s.next?.id||'',voiceProfileId,generation,current:s.current,next:s.next,show:clock.show||null,clockPhase:clock.phase||''};setPhase('ARMED',manual?'manual-ready':'auto-ready');return prepared}catch(e){if(generation===planGeneration){prepared=null;setPhase('COUNTING','prepare-failed',safeErr(e))}return null}finally{preparePromise=null;const liveId=currentTrackId();if(!prepared&&due()&&liveId&&liveId!==originTrackId)scheduleDeferredPrepare(manualArmed,liveId,manualArmed?'manual-break-deferred-reprepare':'automatic-break-deferred-reprepare')}})();return preparePromise
}
function beginHandoff(uri){try{handoffOp=truthApi()?.begin?.('dj-handoff',{expectedUri:uri,timeoutMs:50000})||0}catch{handoffOp=0}}
function endHandoff(error=''){try{if(handoffOp)truthApi()?.end?.(handoffOp,{error})}catch{}handoffOp=0}
async function confirmLive(uri,playing,tries=4){for(let i=0;i<tries;i++){await wait(90+i*55);const s=await liveSnapshot().catch(()=>null);if(s?.live?.item?.uri===uri&&!!s.live.is_playing===!!playing)return true}return false}
async function pauseMusic(uri){const transport=window.JFMPlayback;if(!transport)throw Error('MAIR playback-controller ontbreekt');const fn=typeof transport.djPause==='function'?transport.djPause.bind(transport):transport.pause?.bind(transport);if(typeof fn!=='function')throw Error('MAIR playback-controller kan Spotify niet pauzeren');const ok=await fn(uri);if(!ok)throw Error(`Spotify pause: ${transport?.health?.lastError||'pauzeren mislukt'}`);try{truthApi()?.setExpectedLive?.(true,'dj-handoff')}catch{};if(transport.djPause)return true;if(await confirmLive(uri,false,5))return true;throw Error('Spotify pauze kon niet worden bevestigd')}
async function rewindCurrent(uri){const transport=window.JFMPlayback;if(typeof transport?.djRewind==='function')return !!(await transport.djRewind(uri));const id=String(window.JFMSpotifySDK?.deviceId||localStorage.getItem('jfm_spotify_device_id')||'').trim();if(!id)return false;try{await api('/me/player/seek?position_ms=0&device_id='+encodeURIComponent(id),{method:'PUT'});for(let i=0;i<4;i++){await wait(90+i*60);const s=await liveSnapshot().catch(()=>null);if(s?.live?.item?.uri===uri&&Number(s.live.progress_ms||0)<1800)return true}}catch{}return false}
async function resumeMusic(uri){const transport=window.JFMPlayback;if(!transport)throw Error('MAIR playback-controller ontbreekt');const fn=typeof transport.djResume==='function'?transport.djResume.bind(transport):transport.resume?.bind(transport);if(typeof fn!=='function')throw Error('MAIR playback-controller kan Spotify niet hervatten');const ok=await fn(uri);if(!ok)throw Error(`Spotify resume: ${transport?.health?.lastError||'hervatten mislukt'}`);try{truthApi()?.setExpectedLive?.(true,'radio-live')}catch{};if(transport.djResume)return true;if(await confirmLive(uri,true,6))return true;throw Error('Spotify hervatten kon niet worden bevestigd')}
function assertVoicePrepared(){if(document.visibilityState==='hidden')throw Error('MAIR is op de achtergrond');if(Number(audioStatus().cacheSize||0)<1)throw Error('Voorbereide DJ-audio ontbreekt');return true}
async function ensureVoiceReady(){assertVoicePrepared();if(audioStatus().audioUnlocked)return true;const ok=await unlock().catch(()=>false);if(!ok&&!audioStatus().audioUnlocked)throw Error('DJ-audio is niet ontgrendeld');return true}
async function playPrepared(pack){if(typeof window.speakText!=='function')throw Error('Centrale MAIR Voice Engine is niet geladen');setPhase('SPEAKING',pack.manual?'manual':'automatic');const ok=await window.speakText(pack.text,false);if(!ok)throw Error(audioStatus().error||'DJ-audio werd niet hoorbaar afgespeeld');return true}
async function restoreMusic(uri,{rewind=true}={}){setPhase('RESTORING','music-restore');if(rewind)await rewindCurrent(uri).catch(()=>false);await resumeMusic(uri);return true}
async function air(expectedTrackId='',pack=prepared,{rewind=true}={}){
  if(busy||!pack)return false;busy=true;clearPendingUnexpected();let paused=false,uri='',error='';
  try{
    if(pack.generation!==planGeneration)throw Error('DJ-break is niet meer actueel');
    if(pack.nextHintId&&expectedTrackId&&String(expectedTrackId)!==String(pack.nextHintId))throw Error('De volgende Spotify-track wijzigde na het voorbereiden van de DJ-break');
    if(pack.voiceProfileId&&String(profile()?.id||'josh')!==String(pack.voiceProfileId))throw Error('DJ-profiel wijzigde na het voorbereiden van de stem');
    await ensureVoiceReady();
    const hinted=truth(),hintedId=String(hinted?.trackId||''),hintedUri=String(hinted?.uri||'');
    if(expectedTrackId&&hintedId===String(expectedTrackId)&&hintedUri){uri=hintedUri;beginHandoff(uri);setPhase('HANDOFF',pack.manual?'manual':'automatic');await pauseMusic(uri);paused=true}
    const s=await stableCurrent(expectedTrackId,paused?1600:2400,paused?false:true),currentId=String(s?.current?.id||'');
    if(!currentId||currentId!==String(expectedTrackId||currentId))throw Error('Onverwachte Spotify-track');
    if(pack.nextHintId&&currentId!==String(pack.nextHintId))throw Error('De volgende Spotify-track wijzigde na het voorbereiden van de DJ-break');
    uri=uri||s.live.item.uri||'';if(!uri)throw Error('Spotify-track heeft geen URI');
    if(!paused){beginHandoff(uri);setPhase('HANDOFF',pack.manual?'manual':'automatic');await pauseMusic(uri);paused=true}
    await window.MAIRImaging?.beforeBreak?.({phase:pack.clockPhase,show:pack.show,dj:pack.voiceProfileId}).catch(()=>false);
    await playPrepared(pack);await restoreMusic(uri,{rewind});paused=false;endHandoff();state.lastAirAt=Date.now();state.lastAirText=pack.text;state.played++;state.error='';recent.unshift(pack.text);recent.splice(8);const requestTrack=pack.next?.request?pack.next:pack.current?.request?pack.current:null;if(requestTrack){try{window.JFMRequests?.consumeCurrentRequest?.(requestTrack)}catch{}}try{window.MAIRDJMemory?.record?.({text:pack.text,dj:pack.voiceProfileId,show:pack.show?.id||'',current:pack.current,next:pack.next,kind:pack.manual?'manual':'automatic'})}catch{}try{window.dispatchEvent(new CustomEvent('mair:dj-aired',{detail:{text:pack.text,dj:pack.voiceProfileId,show:pack.show||null,current:pack.current,next:pack.next,at:state.lastAirAt}}))}catch{}const bt=$('djBreakTime');if(bt)bt.textContent=new Date().toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'});const dt=$('djText');if(dt)dt.textContent=pack.text;resetPlan('break-complete');return true
  }catch(e){error=safeErr(e);state.lastMissAt=Date.now();state.lastMissReason='air-failed';state.error=error;return false}finally{if(paused&&uri){try{await restoreMusic(uri,{rewind:false})}catch{}}endHandoff(error);busy=false;if(error)rearmOwed(!!pack.manual,currentTrackId()||expectedTrackId,'break-missed',error);else emit()}
}
async function naturalTransition(detail={}){
  const endedId=String(detail.endedTrackId||''),newId=String(detail.newTrackId||'');if(!endedId||!newId)return false;const sig=`${endedId}>${newId}`;if(sig===lastNaturalSig)return false;lastNaturalSig=sig;setTimeout(()=>{if(lastNaturalSig===sig)lastNaturalSig=''},2500);if(pendingUnexpected&&pendingUnexpected.id===newId)clearPendingUnexpected();if(busy)return false;
  if(manualArmed){const pack=prepared;if(pack&&pack.manual&&pack.originTrackId===endedId)return air(newId,pack,{rewind:true});if(pack&&pack.originTrackId!==endedId)prepared=null;return deferBreak(true,newId,'manual-break-deferred')}
  count++;emit();if(count>=target){if(skipNextBreak){skipNextBreak=false;miss('break-skipped-by-user');return false}const pack=prepared;if(pack&&!pack.manual&&pack.originTrackId===endedId)return air(newId,pack,{rewind:true});if(pack&&pack.originTrackId!==endedId)prepared=null;return deferBreak(false,newId,'automatic-break-deferred')}
  if(remaining()===1&&!prepared&&!preparePromise)prepare({manual:false,originTrackId:newId}).catch(()=>{});return true
}
function unexpectedTransition(detail={}){
  const id=String(detail.trackId||''),previous=String(detail.previousTrackId||'');if(!id||busy)return;clearPendingUnexpected();const record={id,previous,source:String(detail.source||''),timer:0};record.timer=setTimeout(()=>{if(pendingUnexpected!==record||busy)return;pendingUnexpected=null;if(manualArmed){miss('manual-or-unexpected-track-change');return}const hadAutoState=prepared||preparePromise||count>0;if(!hadAutoState)return;if(prepared&&prepared.originTrackId!==id){planGeneration++;prepared=null;preparePromise=null}if(count>=target){rearmOwed(false,id,'automatic-track-change-preserved');return}setPhase('COUNTING','automatic-track-change-preserved');if(remaining()===1&&!prepared&&!preparePromise)prepare({manual:false,originTrackId:id}).catch(()=>{})},4200);pendingUnexpected=record
}
function armManual(){const id=currentTrackId();if(!id||busy)return false;planGeneration++;prepared=null;preparePromise=null;manualArmed=true;skipNextBreak=false;const b=$('djNow');if(b){b.dataset.queued='1';const strong=b.querySelector('b'),small=b.querySelector('span');if(strong)strong.textContent='🎙️ DJ staat klaar';if(small)small.textContent='Praat bij de volgende natuurlijke overgang'}prepare({manual:true,originTrackId:id}).catch(()=>{});return true}
function skipNext(){if(busy)return false;skipNextBreak=true;planGeneration++;prepared=null;preparePromise=null;const b=$('skipTalk');if(b){b.dataset.queued='1';const span=b.querySelector('span');if(span)span.textContent='Volgende DJ-break wordt overgeslagen'}setPhase('COUNTING','skip-next-armed');return true}
function ownButtons(){const own=(id,flag,handler)=>{const old=$(id);if(!old||old.dataset[flag]==='v3')return;const b=old.cloneNode(true);old.replaceWith(b);b.dataset[flag]='v3';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();handler()},true)};own('djNow','mairDjOwner',armManual);own('skipTalk','mairDjSkipOwner',skipNext)}
async function writerCheck(){const r=await writerRequest({dj:profile(),breakType:'diagnostic',length:'short',currentTrack:{name:'Voice Check',artists:['MAIR']},station:'MAIR',show:window.JFMStationClock?.current?.()?.show||null,time:new Date().toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'})}),d=await r.json().catch(()=>({}));if(!r.ok||!d?.text)throw Error(d?.error||`Groq HTTP ${r.status}`);return d}
async function runVoiceCheck(onStep=()=>{}){const out=[],step=(name,status,detail='')=>{const x={name,status,detail,at:Date.now()};out.push(x);try{onStep(x,[...out])}catch{}return x};step('DJ runtime','pass',version);let w;try{w=await writerCheck();step('Groq DJ Writer','pass',`${w.model||'model'} · tekst klaar`)}catch(e){step('Groq DJ Writer','fail',safeErr(e));return out}const text='Dit is de MAIR Voice Check. Als je dit hoort, werkt de DJ-handoff goed.';try{const ok=await window.prepareSpeech?.(text,false);if(!ok)throw Error(audioStatus().error||'Fish Audio voorbereiding mislukt');step('Fish Audio generatie','pass',`${audioStatus().model||'model'} · centrale cache klaar`)}catch(e){step('Fish Audio generatie','fail',safeErr(e));return out}try{const ok=await unlock();if(!ok&&!audioStatus().audioUnlocked)throw Error('Audio niet ontgrendeld');step('Centrale audio-engine','pass','ontgrendeld')}catch(e){step('Centrale audio-engine','fail',safeErr(e));return out}const s=await stableCurrent('',1500).catch(()=>null),uri=s?.live?.item?.uri||'',hadSpotify=!!(uri&&s?.live?.is_playing);let paused=false,error='';try{if(hadSpotify){beginHandoff(uri);await pauseMusic(uri);paused=true;step('Spotify pause','pass',`pauze bevestigd · ${transportMode()}`)}setPhase('SPEAKING','voice-check');const ok=await window.speakText(text,false);if(!ok)throw Error(audioStatus().error||'Audio playback gaf false terug');step('DJ audio playback','pass',`afgespeeld via ${audioStatus().playbackMode||'centrale audio-engine'}`);if(hadSpotify){await resumeMusic(uri);paused=false;step('Spotify resume','pass',`hervat · ${transportMode()}`)}else step('Spotify pause/resume','skip','Geen actieve Spotify-playback')}catch(e){error=safeErr(e);step('Spotify/DJ handoff','fail',error)}finally{if(paused&&uri)try{await resumeMusic(uri)}catch{};endHandoff(error);busy=false;setPhase('COUNTING','voice-check-complete')}return out}
function bindFrequency(){const t=$('talk');if(!t||t.dataset.mairDjV3Bound)return;t.dataset.mairDjV3Bound='1';t.addEventListener('change',()=>resetPlan('frequency-change'));t.addEventListener('input',render)}
function boot(){ownButtons();bindFrequency();resetPlan('boot')}
window.MAIRDJ={version,prepare,air,armManual,skipNext,runVoiceCheck,diagnostics,unlock,plan:resetPlan,state:diagnostics,get busy(){return busy}};
window.JFMDJAuthoritative=window.MAIRDJ;
window.djBreak=(track=null,manual=false)=>manual?Promise.resolve(armManual()):Promise.resolve(false);
window.addEventListener('jfm:trackchange',e=>unexpectedTransition(e.detail||{}));
window.addEventListener('jfm:natural-next-ready',e=>naturalTransition(e.detail||{}).catch(err=>{const error=safeErr(err);if(due())rearmOwed(manualArmed,currentTrackId(),'natural-transition-error',error);else setPhase('COUNTING','natural-transition-error',error)}));
window.addEventListener('pageshow',()=>setTimeout(()=>{ownButtons();bindFrequency();render()},120));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();