(()=>{
'use strict';
if(window.MAIRDJ?.version?.startsWith('v3'))return;
const $=id=>document.getElementById(id),wait=ms=>new Promise(r=>setTimeout(r,ms));
const TALK_RANGES=[[6,9],[3,5],[2,4],[1,3]],LABELS=['Weinig','Normaal','Radio','Veel'];
let lastTrackId='',planTarget=4,count=0,prepared=null,preparing=null,handoffBusy=false,manualArmed=false,skipOnce=false,lastAttemptKey='';
let state={phase:'COUNTING',reason:'boot',error:'',updatedAt:Date.now(),writer:null,voice:null,lastAirAt:0,lastAirText:'',missed:0,played:0};
const recent=[];
const version='v3.0-single-owner-single-attempt';
const truth=()=>window.JFMPlaybackState?.get?.()||null;
const profile=()=>window.MAIRDJProfiles?.current||window.MAIRCurrentDJ||{id:'josh',name:'Josh',role:'MAIR DJ'};
const mode=()=>Math.max(0,Math.min(3,Number($('talk')?.value??1)||0));
const safeErr=e=>String(e?.message||e||'onbekende fout').slice(0,260);
const audioStatus=()=>window.JFMDJAudio?.status||{};
const station=()=>document.getElementById('mairActiveStation')?.textContent||window.MAIRStationController?.active?.()?.label||'MAIR';
function chooseTarget(){const r=TALK_RANGES[mode()]||TALK_RANGES[1];return Math.floor(Math.random()*(r[1]-r[0]+1))+r[0]}
function remaining(){return manualArmed?0:Math.max(0,planTarget-count)}
function diagnostics(){const a=audioStatus();return{version,phase:state.phase,reason:state.reason,error:state.error,remaining:remaining(),target:planTarget,count,pendingAir:manualArmed||state.phase==='ARMED',prepared:prepared?{text:prepared.text,manual:prepared.manual,forTrackId:prepared.forTrackId,nextId:prepared.nextId,createdAt:prepared.createdAt}:null,audioUnlocked:!!a.audioUnlocked,audioRoute:a.playbackMode||'',writer:state.writer,voice:state.voice,lastAirAt:state.lastAirAt,lastAirText:state.lastAirText,missed:state.missed,played:state.played,dj:profile()}}
function emit(){state.updatedAt=Date.now();const d=diagnostics();try{window.dispatchEvent(new CustomEvent('mair:dj-v2-state',{detail:d}))}catch{}try{window.dispatchEvent(new CustomEvent('mair:dj-schedule',{detail:d}))}catch{}render()}
function phase(p,reason='',error=''){state={...state,phase:p,reason,error};emit()}
function render(){const el=$('talkValue');if(!el)return;const label=LABELS[mode()]||'Normaal',rem=remaining();if(state.phase==='PREPARING')el.textContent=`${label} · DJ wordt voorbereid`;else if(state.phase==='ARMED')el.textContent=`${label} · DJ klaar voor volgende overgang`;else if(state.phase==='HANDOFF'||state.phase==='SPEAKING'||state.phase==='RESUMING')el.textContent=`${label} · DJ overgang`;else if(state.phase==='FAILED')el.textContent=`${label} · break overgeslagen`;else el.textContent=`${label} · DJ over ${rem} nummer${rem===1?'':'s'}`;el.dataset.djRemaining=String(rem);el.dataset.djPhase=state.phase}
function resetPlan(reason='complete'){planTarget=chooseTarget();count=0;prepared=null;preparing=null;manualArmed=false;lastAttemptKey='';phase('COUNTING',reason)}
function fromSpotifyItem(x){if(!x)return null;return{id:x.id||'',uri:x.uri||'',name:x.name||'',artists:(x.artists||[]).map(a=>a?.name||a).filter(Boolean),release:x.album?.release_date||x.release||'',request:typeof window.jfmIsRequest==='function'?!!window.jfmIsRequest(x):false}}
async function snapshot(){const live=await api('/me/player').catch(()=>null);if(!live?.item)return null;let next=null;try{const q=await api('/me/player/queue');next=fromSpotifyItem(q?.queue?.[0])}catch{}return{live,current:fromSpotifyItem(live.item),next}}
async function unlock(){if(typeof window.JFMDJAudio?.unlock!=='function')return false;return !!(await window.JFMDJAudio.unlock().catch(()=>false))}
async function writeBreak(ctx,manual){const p=profile(),r=await fetch('/api/dj-writer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({dj:p,breakType:manual?'manual-next':'automatic-transition',length:'short',previousTrack:ctx.previous||null,currentTrack:ctx.current||null,nextTrack:ctx.next||null,time:new Date().toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'}),station:station(),recentDJ:recent.slice(0,6)})}),d=await r.json().catch(()=>({}));if(!r.ok||!d?.text)throw Error(d?.error||`DJ writer HTTP ${r.status}`);state.writer={provider:d.provider||'groq',model:d.model||'',text:d.text};return d.text}
async function prepare({manual=false}={}){if(preparing)return preparing;if(prepared)return prepared;preparing=(async()=>{phase('PREPARING',manual?'manual':'automatic');try{const s=await snapshot();if(!s?.current||!s?.next)throw Error('Spotify queue-context ontbreekt');const text=await writeBreak({previous:null,current:s.current,next:s.next},manual);if(typeof window.prepareSpeech!=='function')throw Error('MAIR Voice Engine ontbreekt');const ok=await window.prepareSpeech(String(text).slice(0,1000),false);if(!ok)throw Error(audioStatus().error||'Fish Audio kon de break niet voorbereiden');const a=audioStatus();prepared={text,manual,createdAt:Date.now(),forTrackId:s.current.id,nextId:s.next.id};state.voice={provider:a.provider||'fish',voiceId:a.voiceId||'',model:a.model||'',route:'central'};phase('ARMED',manual?'manual-ready':'auto-ready');return prepared}catch(e){prepared=null;state.missed++;phase('FAILED','prepare',safeErr(e));return null}finally{preparing=null}})();return preparing}
async function waitExpectedTrack(expectedId,timeoutMs=3500){const until=Date.now()+timeoutMs;let s=null;while(Date.now()<until){s=await snapshot();if(s?.live?.is_playing&&String(s.current?.id||'')===String(expectedId))return s;await wait(180)}throw Error('Nieuwe Spotify-track werd niet stabiel bevestigd')}
async function pauseSpotify(){const t=window.JFMPlayback;if(typeof t?.pause!=='function')throw Error('Spotify transport ontbreekt');const ok=await t.pause();if(!ok)throw Error(t?.health?.lastError||'Spotify pauzeren mislukt');return true}
async function resumeSpotify(){const t=window.JFMPlayback;if(typeof t?.resume!=='function')throw Error('Spotify transport ontbreekt');const ok=await t.resume();if(!ok)throw Error(t?.health?.lastError||'Spotify hervatten mislukt');return true}
async function air(expectedTrackId){if(handoffBusy||!prepared)return false;const pack=prepared,key=`${pack.forTrackId}>${expectedTrackId}`;if(lastAttemptKey===key)return false;lastAttemptKey=key;handoffBusy=true;let paused=false;try{if(pack.nextId&&String(pack.nextId)!==String(expectedTrackId))throw Error('Voorbereide break hoort bij een andere track');await waitExpectedTrack(expectedTrackId);if(document.visibilityState==='hidden')throw Error('App staat op achtergrond');const a=audioStatus();if(Number(a.cacheSize||0)<1)throw Error('Voorbereide DJ-audio ontbreekt');const unlocked=await unlock();if(!unlocked&&!audioStatus().audioUnlocked)throw Error('DJ-audio is niet ontgrendeld');phase('HANDOFF',pack.manual?'manual':'automatic');await pauseSpotify();paused=true;phase('SPEAKING','voice-start');const ok=await window.speakText(pack.text,false);if(!ok)throw Error(audioStatus().error||'DJ-audio werd niet hoorbaar afgespeeld');phase('RESUMING','voice-complete');await resumeSpotify();paused=false;state.lastAirAt=Date.now();state.lastAirText=pack.text;state.played++;recent.unshift(pack.text);recent.splice(8);const bt=$('djBreakTime');if(bt)bt.textContent=new Date().toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'});const dt=$('djText');if(dt)dt.textContent=pack.text;resetPlan('break-complete');return true}catch(e){const msg=safeErr(e);state.missed++;phase('FAILED','handoff',msg);prepared=null;manualArmed=false;if(paused){try{await resumeSpotify()}catch{}}setTimeout(()=>resetPlan('failed-break-dropped'),250);return false}finally{handoffBusy=false;emit()}}
async function onTrackChange(id){id=String(id||truth()?.trackId||'');if(!id||id===lastTrackId)return;const previous=lastTrackId;lastTrackId=id;if(!previous){emit();return}if(skipOnce){skipOnce=false;prepared=null;manualArmed=false;resetPlan('user-skipped-break');return}if(manualArmed){if(prepared)await air(id);else{state.missed++;resetPlan('manual-not-ready-dropped')}return}count++;const due=count>=planTarget;if(due){if(prepared)await air(id);else{state.missed++;resetPlan('auto-not-ready-dropped')}return}emit();if(remaining()===1&&!prepared&&!preparing)prepare({manual:false}).catch(()=>{})}
function armManual(){const id=String(truth()?.trackId||'');if(!id||handoffBusy)return false;manualArmed=!manualArmed;prepared=null;preparing=null;const b=$('djNow');if(b){b.dataset.queued=manualArmed?'1':'0';const strong=b.querySelector('b'),small=b.querySelector('span');if(strong)strong.textContent=manualArmed?'🎙️ DJ staat klaar':'🎙️ DJ nu';if(small)small.textContent=manualArmed?'Praat bij het volgende nummer':'Laat de DJ iets vertellen'}if(manualArmed)prepare({manual:true}).catch(()=>{});else resetPlan('manual-cancel');emit();return manualArmed}
function skipNext(){skipOnce=true;prepared=null;manualArmed=false;phase('COUNTING','skip-next-break');return true}
function ownButtons(){const old=$('djNow');if(old&&old.dataset.mairDjOwner!=='v3'){const b=old.cloneNode(true);old.replaceWith(b);b.dataset.mairDjOwner='v3';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();armManual()},true)}const s=$('skipTalk');if(s&&s.dataset.mairDjOwner!=='v3'){const b=s.cloneNode(true);s.replaceWith(b);b.dataset.mairDjOwner='v3';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();skipNext();const x=b.querySelector('span');if(x)x.textContent='Volgende DJ-break wordt overgeslagen'},true)}}
async function runVoiceCheck(onStep=()=>{}){const out=[],step=(name,status,detail='')=>{const x={name,status,detail,at:Date.now()};out.push(x);try{onStep(x,[...out])}catch{}return x};step('DJ runtime','pass',version);try{const s=await snapshot();if(!s?.current)throw Error('Geen actieve Spotify-track');step('Spotify context','pass',s.current.name)}catch(e){step('Spotify context','fail',safeErr(e));return out}try{const p=await prepare({manual:true});if(!p)throw Error(state.error||'Voorbereiden mislukt');step('Groq + Fish Audio voorbereiding','pass','break staat in cache')}catch(e){step('Groq + Fish Audio voorbereiding','fail',safeErr(e));return out}step('Veilige handoff','skip','Echte pause/voice/resume wordt alleen bij een trackovergang getest');return out}
function bindFrequency(){const t=$('talk');if(!t||t.dataset.mairDjV3Bound)return;t.dataset.mairDjV3Bound='1';t.addEventListener('change',()=>resetPlan('frequency-change'));t.addEventListener('input',render)}
function boot(){ownButtons();bindFrequency();lastTrackId=String(truth()?.trackId||'');resetPlan('boot')}
window.MAIRDJ={version,prepare,air,armManual,skipNext,runVoiceCheck,diagnostics,unlock,plan:resetPlan,state:diagnostics,get busy(){return handoffBusy}};
window.JFMDJAuthoritative=window.MAIRDJ;
// Compatibility only: the legacy app scheduler may still call djBreak(track,false).
// Automatic legacy calls are deliberately ignored; v3 is the only scheduler.
window.djBreak=(track=null,manual=false)=>manual?Promise.resolve(armManual()):Promise.resolve(false);
window.addEventListener('jfm:trackchange',e=>setTimeout(()=>onTrackChange(e.detail?.trackId).catch(err=>{state.error=safeErr(err);emit()}),80));
window.addEventListener('pageshow',()=>setTimeout(()=>{ownButtons();bindFrequency();render()},120));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
