// Josh FM music channels + Hit Battle v4 — persistent channel selection and click-to-play.
(()=>{
  const $=id=>document.getElementById(id),CHANNEL_KEY='jfm_music_channel_v1',BATTLE_KEY='jfm_hit_battle_v1',SEARCH_KEY='jfm_channel_search_cache_v1';
  const CHANNELS={
    mix:{label:'Mijn Mix',icon:'🎧',desc:'Alles wat Josh FM van jouw smaak weet.',rule:'persoonlijke mix'},
    hits:{label:'Hits',icon:'🔥',desc:'Actuele bekende hits en populaire tracks.',rule:'actuele hits'},
    top40:{label:'Top 40',icon:'🏆',desc:'Actuele populaire tracks, maximaal 40.',rule:'actuele Top 40'},
    new:{label:'Nieuw',icon:'✨',desc:'Nieuwe releases uit het huidige jaar.',rule:'nieuwe muziek'},
    throwback:{label:'Throwback',icon:'📻',desc:'Bekende muziek van vóór 2017.',rule:'throwbacks'},
    '00s':{label:'00s',icon:'💿',desc:'Muziek uit 2000–2009.',rule:'00s'},
    '10s':{label:'10s',icon:'📱',desc:'Muziek uit 2010–2019.',rule:'10s'},
    nl:{label:'Nederlandstalig',icon:'🇳🇱',desc:'Nederlandstalige artiesten en tracks.',rule:'Nederlandstalig'},
    party:{label:'Party',icon:'🎉',desc:'Dansbaar en energiek.',rule:'party'},
    chill:{label:'Chill',icon:'🌙',desc:'Rustiger en warmer.',rule:'chill'},
    summer:{label:'Summer',icon:'☀️',desc:'Feelgood pop en zomertracks.',rule:'summer'}
  };
  let current=localStorage.getItem(CHANNEL_KEY)||'mix',pair=[],busy=false,baseBuild=null,lastGoodByChannel={};if(!CHANNELS[current])current='mix';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
  const year=t=>Number(String(t?.release||'').slice(0,4))||0,artist=t=>String(t?.artists?.[0]||'').toLowerCase().trim(),pairKey=(a,b)=>[a?.id,b?.id].filter(Boolean).sort().join('|');
  const trackFromSpotify=t=>({id:t.id,uri:t.uri,name:t.name,artists:(t.artists||[]).map(a=>a.name),album:t.album?.name||'',release:t.album?.release_date||'',image:t.album?.images?.[1]?.url||t.album?.images?.[0]?.url||'',url:t.external_urls?.spotify||'',duration:t.duration_ms||0,popularity:Number(t.popularity||0)});
  function emptyBattle(){return{votes:0,tracks:{},artists:{},history:[],recentPairs:[]}}
  function loadBattle(){try{return{...emptyBattle(),...JSON.parse(localStorage.getItem(BATTLE_KEY)||'{}')}}catch{return emptyBattle()}}
  function saveBattle(s){try{localStorage.setItem(BATTLE_KEY,JSON.stringify(s))}catch{}}
  function battleScore(t){const s=loadBattle(),x=s.tracks?.[t.id]||{},a=s.artists?.[artist(t)]||0;return Number(x.score||0)+Number(a||0)*.35}
  function sortWithTaste(list,extra=()=>0){return [...list].sort((a,b)=>(extra(b)+battleScore(b))-(extra(a)+battleScore(a))+(Math.random()-.5)*.2)}
  function searchCache(){try{return JSON.parse(localStorage.getItem(SEARCH_KEY)||'{}')}catch{return{}}}
  function saveSearchCache(c){try{localStorage.setItem(SEARCH_KEY,JSON.stringify(c))}catch{}}
  function channelQuery(id){const now=new Date().getFullYear();return{hits:`year:${Math.max(2022,now-3)}-${now}`,top40:`year:${Math.max(2025,now-1)}-${now}`,new:`year:${now}`,throwback:'year:1980-2016','00s':'year:2000-2009','10s':'year:2010-2019',nl:'genre:dutch',party:'genre:dance',chill:'genre:chill',summer:`genre:pop year:${Math.max(2020,now-6)}-${now}`}[id]||''}
  async function channelSearch(id){const q=channelQuery(id);if(!q)return[];const cache=searchCache(),key=id+'|'+q,hit=cache[key];if(hit?.at&&Date.now()-hit.at<45*60*1000&&Array.isArray(hit.items)&&hit.items.length)return hit.items;const d=await api('/search?type=track&limit=50&q='+encodeURIComponent(q));const items=(d?.tracks?.items||[]).filter(t=>t?.id&&t?.uri).map(trackFromSpotify);if(items.length){cache[key]={at:Date.now(),items};saveSearchCache(cache)}return items}
  function dedupe(list){const seen=new Set();return list.filter(t=>t?.id&&t?.uri&&!seen.has(t.id)&&(seen.add(t.id),true))}
  async function applyChannel(input,id=current){let list=dedupe((Array.isArray(input)?input:[]).filter(Boolean)),now=new Date().getFullYear();if(id!=='mix'){let found=[];try{found=dedupe(await channelSearch(id))}catch{}if(found.length<5)found=dedupe(lastGoodByChannel[id]||[]);if(found.length<5)throw Error(`${CHANNELS[id].label} kon niet betrouwbaar worden geladen. Je huidige muziek blijft staan.`);list=found}if(id==='hits')list=sortWithTaste(list,t=>Number(t.popularity||0)/5+(year(t)>=now-1?2:0));else if(id==='top40')list=sortWithTaste(list,t=>Number(t.popularity||0)/4+(year(t)>=now?3:year(t)>=now-1?1:0)).slice(0,40);else if(id==='new')list=sortWithTaste(list,t=>(year(t)===now?5:0)+Number(t.popularity||0)/10);else if(id==='throwback'||id==='00s'||id==='10s')list=sortWithTaste(list,t=>Number(t.popularity||0)/8);else if(id==='nl')list=sortWithTaste(list,t=>Number(t.popularity||0)/7);else if(id==='party')list=sortWithTaste(list,t=>Number(t.popularity||0)/6+2);else if(id==='chill')list=sortWithTaste(list,t=>Number(t.popularity||0)/10);else if(id==='summer')list=sortWithTaste(list,t=>Number(t.popularity||0)/6+(year(t)>=now-3?1.5:0));else list=sortWithTaste(list);const out=dedupe(list).slice(0,id==='top40'?40:50);if(out.length>=5)lastGoodByChannel[id]=[...out];return out}
  async function rebuildAndMaybeSwitch(target=current){if(busy)return false;busy=true;const previous=current,previousQueue=Array.isArray(queue)?[...queue]:[];try{const q=$('queueInfo');if(q){q.style.color='';q.textContent=`Josh FM ${CHANNELS[target].label} wordt gemaakt…`}let base=previousQueue;if(typeof baseBuild==='function'&&(target==='mix'||!base.length)){const r=await baseBuild();base=Array.isArray(queue)?queue:r}const next=await applyChannel(base,target);if(!next.length)throw Error('Geen bruikbare tracks gevonden.');queue=next;current=target;localStorage.setItem(CHANNEL_KEY,current);try{window.__jfmStationQueueSig=''}catch{};window.jfmRenderNext?.();window.JFMProgramDirector?.render?.();renderBattle();renderChannel();if(q)q.textContent=`${queue.length} tracks klaar · ${CHANNELS[current].label} · starten…`;if(queue[0]?.uri&&window.JFMPlayback?.playUri){const started=await window.JFMPlayback.playUri(queue[0].uri);if(started===false)throw Error('Spotify kon het eerste nummer niet starten.')}if(q)q.textContent=`${queue.length} tracks klaar · ${CHANNELS[current].label} speelt.`;return true}catch(e){queue=previousQueue;current=previous;localStorage.setItem(CHANNEL_KEY,current);renderChannel();const q=$('queueInfo');if(q){q.textContent='Kanaal wisselen mislukt: '+String(e?.message||e);q.style.color='#ffb4b4'}return false}finally{busy=false}}
  async function chooseChannel(id){if(!CHANNELS[id])return false;if(id===current&&Array.isArray(queue)&&queue.length&&window.JFMPlayback?.playUri)return window.JFMPlayback.playUri(queue[0].uri);return rebuildAndMaybeSwitch(id)}
  function nextPair(){const list=(Array.isArray(queue)?queue:[]).filter(t=>t?.id&&t?.uri);if(list.length<2){pair=[];return}const s=loadBattle(),recentPairs=new Set((s.recentPairs||[]).slice(0,12)),recentTracks=new Set((s.history||[]).slice(0,8).flatMap(x=>[x.winnerId,x.loserId]).filter(Boolean));let candidates=[];for(let i=0;i<Math.min(80,list.length*4);i++){const a=list[Math.floor(Math.random()*list.length)],alt=list.filter(t=>t.id!==a?.id&&artist(t)!==artist(a)),pool=alt.length?alt:list.filter(t=>t.id!==a?.id),b=pool[Math.floor(Math.random()*Math.max(1,pool.length))];if(!a||!b)continue;const key=pairKey(a,b),penalty=(recentPairs.has(key)?100:0)+(recentTracks.has(a.id)?3:0)+(recentTracks.has(b.id)?3:0)+Math.abs(battleScore(a)-battleScore(b))*.15;candidates.push({a,b,penalty:penalty+Math.random()})}candidates.sort((x,y)=>x.penalty-y.penalty);pair=candidates.length?[candidates[0].a,candidates[0].b]:list.slice(0,2)}
  function vote(winner,loser){if(!winner||!loser)return;const s=loadBattle();s.votes=Number(s.votes||0)+1;s.tracks=s.tracks||{};s.artists=s.artists||{};for(const[t,delta,field]of[[winner,2,'wins'],[loser,-1,'losses']]){const x=s.tracks[t.id]||{score:0,wins:0,losses:0,name:t.name,artist:t.artists?.join(', ')||''};x.score=Number(x.score||0)+delta;x[field]=Number(x[field]||0)+1;x.name=t.name;x.artist=t.artists?.join(', ')||'';x.image=t.image||x.image||'';s.tracks[t.id]=x;const a=artist(t);if(a)s.artists[a]=Number(s.artists[a]||0)+(delta>0?1:-.35)}s.history=Array.isArray(s.history)?s.history:[];s.history.unshift({at:Date.now(),winnerId:winner.id,loserId:loser.id,winner:winner.name,loser:loser.name});s.history=s.history.slice(0,50);s.recentPairs=Array.isArray(s.recentPairs)?s.recentPairs:[];s.recentPairs.unshift(pairKey(winner,loser));s.recentPairs=[...new Set(s.recentPairs)].slice(0,20);saveBattle(s);nextPair();renderBattle()}
  function recordFor(t){const x=loadBattle().tracks?.[t?.id]||{},total=Number(x.wins||0)+Number(x.losses||0);return total?`${x.wins||0}–${x.losses||0} · ${Math.round((Number(x.wins||0)/total)*100)}% winst`:''}
  function battleCard(t,n){if(!t)return'<div class="battle-empty">Nog geen track beschikbaar.</div>';const record=recordFor(t);return`<button class="battle-card" type="button" data-battle="${n}">${t.image?`<img src="${esc(t.image)}" alt="">`:'<div class="battle-art">JFM</div>'}<b>${esc(t.name)}</b><span>${esc((t.artists||[]).join(', '))}</span>${record?`<small>${esc(record)}</small>`:''}<em>Kies deze</em></button>`}
  function battleTop(s){return Object.entries(s.tracks||{}).map(([id,x])=>({id,...x})).filter(x=>Number(x.wins||0)>0).sort((a,b)=>Number(b.score||0)-Number(a.score||0)||Number(b.wins||0)-Number(a.wins||0)).slice(0,3)}
  function renderBattle(){const host=$('jfmBattle');if(!host)return;if(pair.length<2)nextPair();const s=loadBattle(),top=battleTop(s);host.innerHTML=`<div class="battle-head"><div><div class="kicker">HIT BATTLE</div><h3>Welke wil jij vaker horen?</h3></div><strong>${Number(s.votes||0)} keuzes</strong></div><div class="battle-grid">${battleCard(pair[0],0)}<div class="battle-vs">VS</div>${battleCard(pair[1],1)}</div><p class="muted">De winnaar krijgt meer gewicht in toekomstige radiosets.</p>${top.length?`<div class="battle-top"><b>Jouw Battle Top</b>${top.map((x,i)=>`<span>${i+1}. ${esc(x.name)} · ${Number(x.wins||0)} winst</span>`).join('')}</div>`:''}`;host.querySelectorAll('[data-battle]').forEach(b=>b.addEventListener('click',()=>{const n=Number(b.dataset.battle);vote(pair[n],pair[n?0:1])}))}
  function renderChannel(){document.querySelectorAll('[data-jfm-channel]').forEach(b=>b.classList.toggle('active',b.dataset.jfmChannel===current));const d=$('channelDescription');if(d)d.textContent=CHANNELS[current].desc;const mini=$('channelMini');if(mini)mini.textContent=CHANNELS[current].label;document.body.dataset.musicChannel=current;window.JFMMusicChannelContext={id:current,...CHANNELS[current]}}
  function inject(){if($('tab-choose'))return;const nav=document.querySelector('.tabs'),settingsTab=nav?.querySelector('[data-tab="settings"]');if(!nav)return;const b=document.createElement('button');b.className='tab';b.dataset.tab='choose';b.textContent='Kiezen';nav.insertBefore(b,settingsTab||null);const pane=document.createElement('section');pane.id='tab-choose';pane.className='tabpane';pane.innerHTML=`<article class="card"><div class="kicker">JOSH FM KANALEN</div><h3>Kies wat je wilt horen</h3><p id="channelDescription" class="muted"></p><div class="channel-grid">${Object.entries(CHANNELS).map(([id,c])=>`<button type="button" class="channel-card" data-jfm-channel="${id}"><span>${c.icon}</span><b>${c.label}</b></button>`).join('')}</div></article><article id="jfmBattle" class="card"></article>`;const settings=$('tab-settings');settings?.parentNode?.insertBefore(pane,settings);b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tabpane').forEach(x=>x.classList.toggle('active',x===pane));renderBattle();renderChannel()});const live=document.querySelector('.live');if(live&&!$('channelMini')){const x=document.createElement('span');x.id='channelMini';x.className='channel-mini';live.appendChild(x)}if(!$('jfm-choice-style')){const s=document.createElement('style');s.id='jfm-choice-style';s.textContent='.channel-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:14px}.channel-card{min-height:82px;border:1px solid #292f38;background:#15181e;color:#eef1f5;border-radius:15px;padding:12px;text-align:left}.channel-card span{font-size:22px;display:block;margin-bottom:7px}.channel-card b{font-size:13px}.channel-card.active{outline:2px solid #68e894;border-color:#68e894}.battle-head{display:flex;justify-content:space-between;gap:12px}.battle-grid{display:grid;grid-template-columns:1fr 34px 1fr;gap:8px;align-items:center;margin-top:14px}.battle-card{border:1px solid #292f38;background:#15181e;color:#fff;border-radius:16px;padding:10px;min-width:0;text-align:left}.battle-card img,.battle-art{width:100%;aspect-ratio:1;border-radius:11px;object-fit:cover;background:#20242b;display:grid;place-items:center}.battle-card b,.battle-card span,.battle-card small,.battle-card em{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.battle-card b{font-size:13px;margin-top:9px}.battle-card span,.battle-card small{font-size:10px;color:#929ba8;margin-top:3px}.battle-card em{font-style:normal;color:#68e894;font-size:10px;margin-top:9px}.battle-vs{text-align:center;font-size:10px;font-weight:900;color:#798390}.battle-top{margin-top:14px;border-top:1px solid #242a32;padding-top:11px}.battle-top b,.battle-top span{display:block;font-size:10px}.channel-mini{font-size:10px;font-weight:800;opacity:.8}';document.head.appendChild(s)}renderChannel();renderBattle()}
  function wrapBuild(){if(baseBuild||typeof window.buildSet!=='function')return false;baseBuild=window.buildSet;window.buildSet=async(...args)=>{const wanted=current,oldQueue=Array.isArray(queue)?[...queue]:[];const r=await baseBuild(...args);try{queue=await applyChannel(Array.isArray(queue)?queue:r,wanted);current=wanted;localStorage.setItem(CHANNEL_KEY,current)}catch(e){current=wanted;localStorage.setItem(CHANNEL_KEY,current);queue=(lastGoodByChannel[wanted]?.length?[...lastGoodByChannel[wanted]]:oldQueue.length?oldQueue:(Array.isArray(queue)?queue:r));const q=$('queueInfo');if(q){q.textContent=`${CHANNELS[current].label} blijft actief · Spotify kon de lijst tijdelijk niet vernieuwen.`;q.style.color='#ffcf70'}}renderBattle();renderChannel();return queue};return true}
  let tries=0;const boot=()=>{inject();if(!wrapBuild()&&++tries<50)setTimeout(boot,120)};boot();window.addEventListener('jfm:trackchange',()=>renderBattle());window.addEventListener('pageshow',()=>{inject();renderChannel();renderBattle()});
  window.JFMMusicChoice={version:'channels-hitbattle-v4-persistent-play',channels:CHANNELS,get channel(){return current},chooseChannel,applyChannel,rebuild:rebuildAndMaybeSwitch,battle:()=>loadBattle(),renderBattle};
})();