// Josh FM Personal Top 40 — privacy-local listening telemetry and explainable ranking.
(()=>{
  const KEY='jfm_top40_telemetry_v1',SNAP='jfm_top40_snapshot_v1',$=id=>document.getElementById(id);
  const now=()=>Date.now();let active=null,lastRender=0;
  function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return x&&typeof x==='object'?x:{}}catch{return{}}}
  function save(db){try{localStorage.setItem(KEY,JSON.stringify(db))}catch{}}
  function trackObjSafe(){try{return playback?.item?trackObj(playback.item):null}catch{return null}}
  function entry(db,t){if(!t?.id)return null;const e=db[t.id]||{id:t.id,name:t.name||'',artists:t.artists||[],image:t.image||'',uri:t.uri||'',firstAt:now(),lastAt:0,starts:0,completed:0,quickSkips:0,listenMs:0,likes:0,requests:0,discoveryWins:0,discoveryLosses:0};e.name=t.name||e.name;e.artists=t.artists||e.artists;e.image=t.image||e.image;e.uri=t.uri||e.uri;db[t.id]=e;return e}
  function begin(t){if(!t?.id)return;if(active?.id===t.id)return;finish('change');const db=load(),e=entry(db,t);e.starts++;e.lastAt=now();save(db);active={id:t.id,startedAt:now(),maxProgress:0,duration:Number(t.duration||0),lastSeen:now()}}
  function sample(){const t=trackObjSafe();if(!t?.id)return;if(!active||active.id!==t.id)begin(t);if(!active)return;let p=0,d=active.duration;try{p=Number(playback?.progress_ms||window.JFMPlaybackState?.get?.()?.progressMs||0);d=Number(playback?.item?.duration_ms||window.JFMPlaybackState?.get?.()?.durationMs||d||0)}catch{}active.maxProgress=Math.max(active.maxProgress,p);active.duration=Math.max(active.duration,d);active.lastSeen=now()}
  function finish(reason='change'){
    if(!active?.id)return;const db=load(),e=db[active.id];if(e){const elapsed=Math.max(0,Math.min(now()-active.startedAt,active.maxProgress||now()-active.startedAt));e.listenMs=(e.listenMs||0)+elapsed;const ratio=active.duration>0?Math.min(1,active.maxProgress/active.duration):0;if(ratio>=.72)e.completed=(e.completed||0)+1;if((reason==='skip'||reason==='change')&&ratio>0&&ratio<.22)e.quickSkips=(e.quickSkips||0)+1;e.lastAt=now();save(db)}active=null;renderSoon()}
  function bumpCurrent(field,n=1){const t=trackObjSafe();if(!t?.id)return;const db=load(),e=entry(db,t);e[field]=(e[field]||0)+n;e.lastAt=now();save(db);renderSoon()}
  function syncExternalSignals(){const db=load();let mem={};try{mem=window.jfmDirectorMemory?.()||{}}catch{};let changed=false;for(const e of Object.values(db)){const like=Number(mem.likes?.[e.id]||0),req=Number(mem.requests?.[e.id]||mem.requests?.[e.uri]||0),win=Number(mem.discoveryWins?.[e.id]||0),loss=Number(mem.discoveryLosses?.[e.id]||0);if(e.likes!==like||e.requests!==req||e.discoveryWins!==win||e.discoveryLosses!==loss){e.likes=like;e.requests=req;e.discoveryWins=win;e.discoveryLosses=loss;changed=true}}if(changed)save(db)}
  function score(e){const ageDays=Math.max(0,(now()-Number(e.lastAt||e.firstAt||now()))/86400000),recency=Math.max(0,8-Math.min(8,ageDays/4));const completionRate=e.starts?e.completed/e.starts:0;const listenMinutes=(e.listenMs||0)/60000;return (e.completed||0)*5.2+completionRate*6+Math.min(12,listenMinutes*.55)+(e.likes||0)*7.5+(e.requests||0)*8+(e.discoveryWins||0)*5-(e.quickSkips||0)*6-(e.discoveryLosses||0)*6+recency}
  function reason(e){const bits=[];if((e.requests||0)>0)bits.push('vaak aangevraagd');if((e.likes||0)>0)bits.push('positieve feedback');if((e.completed||0)>=2)bits.push('vaak afgeluisterd');if((e.discoveryWins||0)>0)bits.push('geslaagde ontdekking');if((e.quickSkips||0)>0&&!bits.length)bits.push('ondanks eerdere skips nog in de mix');return bits[0]||'op basis van je luistergedrag'}
  function ranked(){syncExternalSignals();return Object.values(load()).filter(e=>e?.id&&e.starts>0).map(e=>({...e,score:score(e)})).sort((a,b)=>b.score-a.score||Number(b.lastAt)-Number(a.lastAt)).slice(0,40)}
  function previousRanks(){try{return JSON.parse(localStorage.getItem(SNAP)||'{}')}catch{return{}}}
  function saveSnapshot(list){const map={};list.forEach((e,i)=>map[e.id]=i+1);try{localStorage.setItem(SNAP,JSON.stringify(map))}catch{}}
  function ensureCard(){if($('jfmTop40Card'))return;const stats=$('statHours')?.closest('.card'),pane=$('tab-radio');if(!pane)return;const card=document.createElement('article');card.className='card';card.id='jfmTop40Card';card.innerHTML='<div class="row between"><div><div class="kicker">PERSONAL TOP 40</div><h3>Jouw Josh FM-hitlijst</h3></div><span id="jfmTop40Count" class="accent">IN OPBOUW</span></div><p id="jfmTop40Status" class="muted">Josh FM verzamelt eerst genoeg luistergedrag voor een betrouwbare lijst.</p><div id="jfmTop40List"></div><button id="jfmTop40Toggle" class="secondary hidden" type="button">Bekijk volledige Top 40</button>';if(stats)stats.insertAdjacentElement('afterend',card);else pane.appendChild(card);$('jfmTop40Toggle')?.addEventListener('click',()=>{const b=$('jfmTop40Toggle');b.dataset.open=b.dataset.open==='1'?'0':'1';render(true)});render(true)}
  function safe(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function movement(id,pos,prev){const p=Number(prev[id]||0);if(!p)return'';if(p>pos)return`↑ ${p-pos}`;if(p<pos)return`↓ ${pos-p}`;return'='}
  function render(force=false){if(!force&&Date.now()-lastRender<3500)return;lastRender=Date.now();ensureCard();const list=ranked(),count=$('jfmTop40Count'),status=$('jfmTop40Status'),box=$('jfmTop40List'),toggle=$('jfmTop40Toggle');if(!box)return;const enough=list.length>=8;if(count)count.textContent=enough?`${Math.min(40,list.length)} TRACKS`:'IN OPBOUW';if(status)status.textContent=enough?(list.length>=40?'Gebaseerd op afluisteren, skips, likes, requests, Discovery en recente luistermomenten.':`Voorlopige Top ${list.length}. De lijst groeit automatisch richting 40 unieke tracks.`):`Nog ${Math.max(0,8-list.length)} unieke tracks nodig voor een eerste betrouwbare ranglijst.`;if(!list.length){box.innerHTML='<p class="muted">Luister naar Josh FM om de lijst op te bouwen.</p>';toggle?.classList.add('hidden');return}const prev=previousRanks(),open=toggle?.dataset.open==='1',shown=list.slice(0,open?40:Math.min(10,list.length));box.innerHTML=shown.map((e,i)=>`<div class="director-track"><span class="director-num">${i+1}</span>${e.image?`<img src="${safe(e.image)}" alt="" loading="lazy">`:''}<div class="director-meta"><b>${safe(e.name)}</b><span>${safe((e.artists||[]).join(', '))} · ${safe(reason(e))}</span></div><em>${movement(e.id,i+1,prev)||'NEW'}</em></div>`).join('');if(toggle){toggle.classList.toggle('hidden',list.length<=10);toggle.textContent=open?'Toon Top 10':`Bekijk volledige Top ${Math.min(40,list.length)}`};saveSnapshot(list)}
  function renderSoon(){setTimeout(()=>render(true),80)}
  window.addEventListener('jfm:trackchange',e=>{finish('change');const t=trackObjSafe();if(t?.id)begin(t);renderSoon()});window.addEventListener('jfm:playback-state',sample);document.addEventListener('visibilitychange',()=>{if(document.hidden)finish('background');else sample()});window.addEventListener('pagehide',()=>finish('background'));
  document.addEventListener('click',e=>{if(e.target.closest?.('#next,#banTrack')){sample();finish('skip')}if(e.target.closest?.('#loveTrack'))setTimeout(()=>{bumpCurrent('likes',0);syncExternalSignals();render(true)},120)},true);
  setInterval(()=>{sample();render()},5000);setInterval(syncExternalSignals,15000);
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensureCard);else ensureCard();setTimeout(sample,1800);
  window.JFMTop40={version:'top40-v1-telemetry',ranked,score,reason,telemetry:()=>load(),render};
})();
