// MAIR Radio Suite — memory, stats, hour markers, DJ feedback learning and controller boot.
(()=>{
 const $=id=>document.getElementById(id),K='jfm_radio_suite',DK='jfm_dj_feedback',DISC_KEY='jfm_discovered_tracks_v1',BUILD=String(window.JFM_ASSET_VERSION||'48');
 const load=()=>{try{return JSON.parse(localStorage.getItem(K)||'{}')}catch{return{}}},save=s=>{try{localStorage.setItem(K,JSON.stringify(s))}catch{}};
 const loadDj=()=>{try{return JSON.parse(localStorage.getItem(DK)||'{"up":0,"down":0,"liked":[],"disliked":[]}')}catch{return{up:0,down:0,liked:[],disliked:[]}}},saveDj=d=>{try{localStorage.setItem(DK,JSON.stringify(d))}catch{}};
 const loadDiscoveries=()=>{try{const v=JSON.parse(localStorage.getItem(DISC_KEY)||'[]');return Array.isArray(v)?v.filter(x=>x&&x.id):[]}catch{return[]}},saveDiscoveries=v=>{try{localStorage.setItem(DISC_KEY,JSON.stringify(v.slice(-1000)))}catch{}};
 const DISCOVERY_LISTEN_MS=30000,DISCOVERY_TICK_MS=1000,DISCOVERY_MAX_TICK_MS=2000;
 let s={minutes:0,tracks:0,discoveries:0,requests:0,likes:0,dislikes:0,lastIds:[],lastArtists:[],startedAt:0,...load()},discovered=loadDiscoveries(),discoveryListen={id:null,activeMs:0,lastTickAt:0,counted:false};
 document.querySelectorAll('link[rel="apple-touch-icon"]').forEach(x=>x.remove());const touch=document.createElement('link');touch.rel='apple-touch-icon';touch.sizes='512x512';touch.href=`./mair-logo.svg?v=9&build=${BUILD}`;document.head.appendChild(touch);let fav=document.querySelector('link[rel="icon"]');if(!fav){fav=document.createElement('link');fav.rel='icon';document.head.appendChild(fav)}fav.type='image/svg+xml';fav.href=`./mair-logo.svg?v=9&build=${BUILD}`;
 function queueTrack(id){try{return(typeof queue!=='undefined'&&Array.isArray(queue)?queue:[]).find(x=>x?.id===id)||null}catch{return null}}
 function isDiscovery(id){return!!queueTrack(id)?._discovery}
 function hasDiscovered(id){return discovered.some(x=>x.id===id)}
 function countDiscovery(id){if(!id||hasDiscovered(id))return false;discovered.push({id,at:Date.now()});saveDiscoveries(discovered);s.discoveries=Math.max(0,Number(s.discoveries)||0)+1;save(s);renderStats();try{window.dispatchEvent(new CustomEvent('mair:discovery-counted',{detail:{id,total:s.discoveries}}))}catch{}return true}
 function resetDiscoveryListening(id=null,now=Date.now()){discoveryListen={id,activeMs:0,lastTickAt:id?now:0,counted:false}}
 function scheduleDiscovery(t){const id=t?.id;if(!id||!isDiscovery(id)||hasDiscovered(id)){resetDiscoveryListening();return}if(discoveryListen.id!==id)resetDiscoveryListening(id)}
 function updateDiscoveryListening(now=Date.now()){try{const id=playback?.item?.id||null;if(!id||!isDiscovery(id)||hasDiscovered(id)){resetDiscoveryListening();return false}if(discoveryListen.id!==id){resetDiscoveryListening(id,now);return false}const elapsed=Math.max(0,Math.min(DISCOVERY_MAX_TICK_MS,now-discoveryListen.lastTickAt));discoveryListen.lastTickAt=now;if(!playback?.is_playing||discoveryListen.counted)return false;discoveryListen.activeMs+=elapsed;if(discoveryListen.activeMs<DISCOVERY_LISTEN_MS)return false;discoveryListen.counted=true;return countDiscovery(id)}catch{resetDiscoveryListening();return false}}
 function resetDiscoveries(){resetDiscoveryListening();discovered=[];saveDiscoveries(discovered);s.discoveries=0;save(s);renderStats();try{window.dispatchEvent(new CustomEvent('mair:discoveries-reset',{detail:{total:0}}))}catch{}return true}
 function rememberTrack(t){if(!t?.id||s.lastIds[0]===t.id)return;s.tracks++;s.lastIds.unshift(t.id);s.lastIds=s.lastIds.slice(0,100);const a=(t.artists?.[0]?.name||t.artists?.[0]||'').toLowerCase();if(a){s.lastArtists.unshift(a);s.lastArtists=s.lastArtists.slice(0,50)}save(s);renderStats();scheduleDiscovery(t)}
 function renderStats(){[['statTracks',s.tracks],['statDiscoveries',s.discoveries],['statRequests',s.requests],['statHours',(s.minutes/60).toFixed(1)+' u']].forEach(([id,v])=>{const e=$(id);if(e)e.textContent=v})}
 function autoMode(){if(localStorage.getItem('jfm_auto_program')==='0')return;const fromClock=window.JFMStationClock?.preferredMode?.();if(fromClock){if(settings?.mode!==fromClock&&typeof setMode==='function')setMode(fromClock);return}const h=new Date().getHours();const m=h<10?'morning':h>=23?'late':h>=20?'chill':'normal';if(settings?.mode!==m&&typeof setMode==='function')setMode(m)}
 function renderShow(){const central=window.JFMStationClock?.current?.(),clock=window.JFMRadioClock,show=central?.show?.name||clock?.showName?.()||'MAIR',phase=central?.phase||clock?.clockPhase?.()||'open';document.querySelectorAll('#showMini').forEach(x=>x.remove());document.body.dataset.show=central?.show?.id||show;document.body.dataset.clockPhase=phase;const pill=$('mairRadioMode'),mode=$('modeMini')?.textContent?.trim()||$('modeLabel')?.textContent?.trim();if(pill&&mode)pill.textContent=mode}
 setInterval(updateDiscoveryListening,DISCOVERY_TICK_MS);setInterval(()=>{if(playback?.is_playing){s.minutes++;save(s);renderStats()}},60000);let seen='';setInterval(()=>{const t=playback?.item;if(t?.id&&t.id!==seen){seen=t.id;rememberTrack(t)}renderShow()},6000);let hour=new Date().getHours();setInterval(()=>{const h=new Date().getHours();if(h!==hour){hour=h;window.jfmHourMarker=true}renderShow()},30000);
 window.addEventListener('mair:request-confirmed',e=>{try{const uri=String(e.detail?.uri||''),id=uri.split(':').pop();if(id){const m=JSON.parse(localStorage.getItem('jfm_director_memory')||'{"plays":{},"likes":{},"requests":{}}');m.requests=m.requests||{};m.requests[id]=(m.requests[id]||0)+1;m.requests[uri]=(m.requests[uri]||0)+1;localStorage.setItem('jfm_director_memory',JSON.stringify(m));s.requests++;save(s);renderStats()}}catch{}});
 $('loveTrack')?.addEventListener('click',()=>{s.likes++;save(s);renderStats()});$('banTrack')?.addEventListener('click',()=>{s.dislikes++;save(s);renderStats()});
 $('autoProgram')?.addEventListener('change',e=>{localStorage.setItem('jfm_auto_program',e.target.checked?'1':'0');if(e.target.checked)autoMode()});if($('autoProgram'))$('autoProgram').checked=localStorage.getItem('jfm_auto_program')!=='0';
 const djText=$('djText');if(djText&&$('factSource')&&!$('djFeedback')){const wrap=document.createElement('div');wrap.id='djFeedback';wrap.style.cssText='display:flex;gap:8px;margin-top:12px';wrap.innerHTML='<button id="djUp" type="button" style="flex:1;border:1px solid #293650;background:#111827;color:#fff;border-radius:12px;padding:9px">👍 Meer zo</button><button id="djDown" type="button" style="flex:1;border:1px solid #293650;background:#111827;color:#fff;border-radius:12px;padding:9px">👎 Minder zo</button>';$('factSource').insertAdjacentElement('afterend',wrap);const rate=good=>{const d=loadDj(),text=window.jfmLastDJText||djText.textContent||'';if(!text)return;if(good){d.up=(d.up||0)+1;d.liked=d.liked||[];d.liked.unshift(text);d.liked=d.liked.slice(0,15);$('djUp').textContent='👍 Onthouden'}else{d.down=(d.down||0)+1;d.disliked=d.disliked||[];d.disliked.unshift(text);d.disliked=d.disliked.slice(0,15);$('djDown').textContent='👎 Onthouden'}saveDj(d);setTimeout(()=>{if($('djUp'))$('djUp').textContent='👍 Meer zo';if($('djDown'))$('djDown').textContent='👎 Minder zo'},900)};$('djUp').onclick=()=>rate(true);$('djDown').onclick=()=>rate(false)}
 autoMode();setInterval(autoMode,10*60*1000);renderStats();setTimeout(renderShow,1400);if($('installHint')&&/iphone|ipad|ipod/i.test(navigator.userAgent))$('installHint').textContent='Op iPhone: open MAIR vanaf je beginscherm voor de volledige app-ervaring.';
 // Het koppelvenster hoort alleen open te gaan als de Spotify-sessie echt weg is.
 // Dit hing eerder aan de tekst in #queueInfo, en dat is de gedeelde statusregel van
 // vier modules: elke voorbijgaande fout met 'niet gekoppeld' erin zette het venster
 // binnen 4 seconden open terwijl de sessie geldig was. Nu wordt de sessiestatus
 // zelf gelezen. reauthRequired komt uit spotify-test-config.js en gaat uitsluitend
 // op true bij Spotify's definitieve invalid_grant; een 429, een timeout of een
 // netwerkfout levert daar bewust AUTH_REFRESH_RECOVERABLE op en dus geen venster.
 function sessionNeedsReauth(){
   const hardened=window.MAIRSpotifySessionReliability?.state;
   if(hardened&&hardened.reauthRequired===true)return true;
   const auth=window.JFMAuth?.state;
   if(!auth)return false;
   return !auth.hasRefreshToken&&!auth.hasAccessToken
 }
 function authGuard(){const setup=$('setup');if(!setup||!sessionNeedsReauth())return;setup.classList.remove('hidden');if($('connect'))$('connect').disabled=false}
 setInterval(authGuard,4000);window.addEventListener('pageshow',authGuard);window.addEventListener('online',authGuard);setTimeout(authGuard,800);
 window.JFMRadioSuite={state:()=>s,save,autoMode,renderShow,djFeedback:loadDj,discoveries:()=>[...discovered],discoveryListening:()=>({...discoveryListen}),resetDiscoveries,build:BUILD,boot:null};
 const versioned=src=>{try{const u=new URL(src,location.href);u.searchParams.set('v',BUILD);return u.href}catch{return src+(src.includes('?')?'&':'?')+'v='+encodeURIComponent(BUILD)}};
 const loadScript=(src,id)=>new Promise((resolve,reject)=>{if(document.getElementById(id))return resolve({src,loaded:true,existing:true});const x=document.createElement('script');x.id=id;x.src=versioned(src);x.async=false;x.onload=()=>resolve({src,loaded:true});x.onerror=()=>reject(new Error(`Kon ${src} niet laden`));document.body.appendChild(x)});
 const modules=[['./queue-core.js','jfm-queue-core'],['./station-clock.js','jfm-station-clock'],['./station-clock-bridge.js','jfm-station-clock-bridge'],['./rotation-engine.js','jfm-rotation-engine'],['./dj-context.js','jfm-dj-context'],['./dj-audio-guard.js','jfm-dj-audio-guard'],['./spotify-upcoming-truth.js','jfm-spotify-upcoming-truth'],['./request-manager.js','jfm-request-manager'],['./playback-state.js','jfm-playback-state'],['./transition-controller.js','mair-transition-controller'],['./spotify-recovery.js','jfm-spotify-recovery'],['./station-queue.js','jfm-station-queue'],['./runtime-modes.js','jfm-runtime-modes'],['./personal-top40.js','jfm-personal-top40'],['./live-ui.js','jfm-live-ui'],['./pwa-platform.js','jfm-pwa-platform'],['./integration-guards.js','jfm-integration-guards'],['./station-health.js','jfm-station-health']];
 (async()=>{const loaded=[],failed=[];for(const[src,id]of modules){try{await loadScript(src,id);loaded.push(src)}catch(e){failed.push({src,error:String(e?.message||e)});console.error('MAIR module load',src,e)}}const criticalMissing=['./playback-state.js','./spotify-recovery.js'].filter(x=>failed.some(f=>f.src===x));if(criticalMissing.length){const q=$('queueInfo');if(q){q.textContent='Een essentieel Spotify-onderdeel kon niet laden. Vernieuw MAIR.';q.style.color='#ffb4b4'}}else if(failed.length){console.warn('MAIR optionele modules niet beschikbaar',failed)}try{autoMode();renderShow();window.jfmRenderNext?.();window.JFMTop40?.render?.();window.JFMLiveUI?.render?.();window.JFMPWA?.updateMediaSession?.();window.JFMRuntimeModes?.apply?.();window.JFMIntegrationGuards?.sanity?.();window.JFMStationHealth?.applySafeMode?.()}catch{}window.JFMRadioSuite.boot={loaded,failed,at:Date.now()}})();
})();
