// Josh FM Request Manager — smart scheduling with reliable arming and natural-queue adoption.
(()=>{
  if(window.JFMRequests?.version)return;
  const KEY='jfm_requests_v1',PLAYED_KEY='jfm_played_request_v1',PLAYED_TTL=10*60*1000,MAX_ACTIVE=8,MAX_ARMED_TRANSITIONS=3,MAX_NATURAL_MISSES=2,MIN_NORMAL_TRACKS_AFTER_REQUEST=2,TRACK_URI=/^spotify:track:[A-Za-z0-9]{22}$/,$=id=>document.getElementById(id),now=()=>Date.now();
  let requests=load(),playedRequest=loadPlayed(),arming=false,lastObservedUri='';const events=[];
  function validUri(v){return TRACK_URI.test(String(v||''))}
  function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x.filter(r=>r&&validUri(r.uri)&&r.status!=='played').slice(0,MAX_ACTIVE).map(r=>({...r,status:['planned','armed'].includes(r.status)?r.status:'planned',armedTransitions:Number(r.armedTransitions||0),armAttempts:Number(r.armAttempts||0),natural:!!r.natural,naturalMisses:Number(r.naturalMisses||0)})):[]}catch{return[]}}
function loadPlayed(){try{const x=JSON.parse(localStorage.getItem(PLAYED_KEY)||'null');if(!x||typeof x!=='object')return null;if(!Number(x.playedAt)||now()-Number(x.playedAt)>PLAYED_TTL){localStorage.removeItem(PLAYED_KEY);return null}return x}catch{return null}}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(requests.slice(0,MAX_ACTIVE)))}catch{}render();try{window.dispatchEvent(new CustomEvent('jfm:requests-change',{detail:{requests:requests.map(r=>({...r}))}}))}catch{}}
function savePlayed(){try{if(playedRequest)localStorage.setItem(PLAYED_KEY,JSON.stringify(playedRequest));else localStorage.removeItem(PLAYED_KEY)}catch{}}
function currentRequest(track){if(!playedRequest)return null;if(now()-Number(playedRequest.playedAt||0)>PLAYED_TTL){playedRequest=null;savePlayed();return null}const uri=String(track?.uri||''),id=String(track?.id||'');if((uri&&uri===playedRequest.uri)||(id&&id===playedRequest.trackId))return{...playedRequest,artists:[...(playedRequest.artists||[])]};return null}
function consumeCurrentRequest(track){const marker=currentRequest(track);if(!marker)return null;playedRequest=null;savePlayed();trace('request-announcement-consumed',{requestId:marker.requestId,uri:marker.uri});return marker}
  function trace(stage,extra={}){events.unshift({at:now(),stage,...extra});if(events.length>100)events.length=100}
  const artistKey=t=>String(t?.artists?.[0]||'').toLowerCase().trim();
  function currentTrack(){try{return playback?.item?trackObj(playback.item):null}catch{return null}}
  function upcoming(){try{return window.jfmUpcoming?.()||[]}catch{return[]}}
  function futurePosition(uri){const list=upcoming(),i=list.findIndex(t=>t?.uri===uri);return i>=0&&i<6?i+1:0}
  function chooseDelay(track){const current=currentTrack(),future=upcoming();let delay=2+Math.floor(Math.random()*2);const a=artistKey(track);if(a){if(a===artistKey(current))delay=Math.max(delay,3);for(let i=0;i<Math.min(5,future.length);i++)if(a===artistKey(future[i]))delay=Math.max(delay,i+3)}const active=requests.filter(r=>r.status==='planned'||r.status==='armed');if(active.length)delay=Math.max(delay,Math.min(5,2+active.length));return Math.min(6,delay)}
  async function resolveTrack(uri,button){const id=String(uri||'').split(':').pop();if(/^[A-Za-z0-9]{22}$/.test(id))try{const raw=await api('/tracks/'+id);if(raw?.id&&validUri(raw.uri))return trackObj(raw)}catch{}const name=button?.querySelector('b')?.textContent?.trim()||'Spotify request',artists=(button?.querySelector('small')?.textContent||'').split(',').map(x=>x.trim()).filter(Boolean);return{id,uri,name,artists,image:button?.querySelector('img')?.src||'',duration:0}}
  function activeFor(uri){return requests.find(r=>r.uri===uri&&(r.status==='planned'||r.status==='armed'))||null}
  async function add(uri,button=null){if(!validUri(uri)){status('Dit zoekresultaat bevat geen geldige Spotify-track en is niet toegevoegd.');trace('invalid-request-uri',{uri:String(uri||'')});return null}const existing=activeFor(uri);if(existing){paintButton(button,existing);return existing}const current=currentTrack();if(current?.uri===uri){status(`${current.name||'Dit nummer'} draait al op Josh FM.`);trace('request-already-playing',{uri});return null}if(current?.uri)lastObservedUri=current.uri;if(requests.filter(r=>r.status==='planned'||r.status==='armed').length>=MAX_ACTIVE){status('Je request-wachtrij zit vol. Wacht tot er eentje draait.');return null}const track=await resolveTrack(uri,button);if(!validUri(track?.uri)){status('Request kon niet veilig worden toegevoegd.');return null}const naturalPos=futurePosition(uri),delay=naturalPos||chooseDelay(track),r={id:'req_'+now()+'_'+Math.random().toString(36).slice(2,7),uri,track,status:'planned',remaining:delay,requestedAt:now(),armedAt:0,armedTransitions:0,armAttempts:0,natural:!!naturalPos,naturalMisses:0};requests.push(r);save();paintButton(button,r);trace(naturalPos?'request-adopted-upcoming':'request-added',{uri,remaining:delay});status(naturalPos?`${track.name} stond al in de planning · request gekoppeld aan dat moment.`:`${track.name} staat gepland · verwacht over ongeveer ${delay} nummers.`);return r}
  function paintButton(button,r){if(!button||!r)return;const em=button.querySelector('em');if(em)em.textContent=r.status==='armed'?'HIERNA ✓':r.natural?`PLANNING ±${Math.max(1,r.remaining||1)} ✓`:`±${Math.max(1,r.remaining||1)} ✓`;button.dataset.requested='1'}
  function status(text){const q=$('queueInfo');if(q)q.textContent=text}
  function etaText(r){if(r.status==='armed')return'Hierna';const n=Math.max(1,Number(r.remaining)||1);return r.natural?`In planning · ± ${n}`:`± ${n} nummer${n===1?'':'s'}`}
  function ensurePanel(){if($('requestQueue'))return;const pane=$('tab-requests');if(!pane)return;const first=pane.querySelector('.card'),card=document.createElement('article');card.className='card';card.id='requestQueue';card.innerHTML='<div class="row between"><div><div class="kicker">REQUEST LINE</div><h3>Geplande verzoeken</h3></div><span id="requestCount" class="accent">0</span></div><div id="requestItems"><p class="muted">Nog geen verzoeken gepland.</p></div>';first?.insertAdjacentElement('afterend',card)}
  function render(){ensurePanel();const box=$('requestItems'),count=$('requestCount');if(!box)return;const active=requests.filter(r=>r.status==='planned'||r.status==='armed');if(count)count.textContent=String(active.length);if(!active.length){box.innerHTML='<p class="muted">Nog geen verzoeken gepland.</p>';return}const safe=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));box.innerHTML=active.map(r=>`<div class="director-track" data-request-id="${safe(r.id)}">${r.track?.image?`<img src="${safe(r.track.image)}" alt="" loading="lazy">`:''}<div class="director-meta"><b>${safe(r.track?.name||'Request')}</b><span>${safe((r.track?.artists||[]).join(', '))}${r.natural?' · al in Josh FM-planning':''}</span></div><em>${etaText(r)}</em></div>`).join('')}
  async function remoteQueuePosition(uri){if(!validUri(uri))return-1;try{const d=await api('/me/player/queue');return(d?.queue||[]).findIndex(t=>t?.uri===uri)}catch{return-1}}
  async function armDue(){if(arming||requests.some(x=>x.status==='armed'))return false;const r=requests.find(x=>x.status==='planned'&&!x.natural&&Number(x.remaining)<=1);if(!r||!validUri(r.uri))return false;arming=true;try{if(!window.JFMQueue?.programNext)throw Error('Centrale wachtrij is nog niet beschikbaar.');await window.JFMQueue.programNext(r.track||{id:r.uri.split(':').pop(),uri:r.uri},'request-arm');r.status='armed';r.armedAt=now();r.armedTransitions=0;r.armAttempts=Number(r.armAttempts||0)+1;save();trace('request-armed-next',{uri:r.uri,attempt:r.armAttempts});status(`${r.track?.name||'Je request'} staat bevestigd als eerstvolgende Spotify-track.`);return true}catch(e){trace('request-arm-error',{uri:r.uri,error:String(e?.message||e)});status('Request kon nog niet als eerstvolgende worden bevestigd · MAIR probeert het opnieuw zodra Spotify speelt.');return false}finally{arming=false}}
  async function recoverStaleArmed(){const r=requests.find(x=>x.status==='armed');if(!r||Number(r.armedTransitions||0)<MAX_ARMED_TRANSITIONS)return false;const position=await remoteQueuePosition(r.uri);if(position===0){r.armedTransitions=1;save();trace('request-still-next',{uri:r.uri});return false}r.status='planned';r.remaining=1;r.armedAt=0;r.armedTransitions=0;save();trace('request-replanned',{uri:r.uri,attempt:r.armAttempts,position});status(`${r.track?.name||'Request'} is opnieuw ingepland omdat Spotify hem niet als volgende bevestigde.`);setTimeout(()=>armDue().catch(()=>{}),300);return true}
  function onTrackChange(){const cur=currentTrack(),uri=cur?.uri||'';if(!uri||uri===lastObservedUri){trace('duplicate-trackchange',{uri});return}lastObservedUri=uri;const played=requests.find(r=>r.uri===uri&&(r.status==='armed'||r.status==='planned'));if(played){played.status='played';played.playedAt=now();playedRequest=Object.freeze({requestId:played.id,uri:played.uri,trackId:String(played.track?.id||cur?.id||''),name:String(played.track?.name||cur?.name||'Request'),artists:[...(played.track?.artists||cur?.artists||[])].map(a=>String(a?.name||a||'')).filter(Boolean),playedAt:played.playedAt});savePlayed();trace('request-played',{uri,natural:!!played.natural,requestId:played.id});requests=requests.filter(r=>r.id!==played.id);for(const r of requests){if(r.status==='planned'&&!r.natural)r.remaining=Math.max(Number(r.remaining)||1,MIN_NORMAL_TRACKS_AFTER_REQUEST+1)}trace('request-radio-gap',{afterRequest:played.uri,normalTracks:MIN_NORMAL_TRACKS_AFTER_REQUEST});save();status(`${played.track?.name||'Request'} draait nu · daarna eerst ${MIN_NORMAL_TRACKS_AFTER_REQUEST} gewone MAIR-nummers.`);return}for(const r of requests){if(r.status==='planned'){const before=Number(r.remaining)||1;r.remaining=Math.max(1,before-1);if(r.natural&&before<=1){r.naturalMisses=Number(r.naturalMisses||0)+1;if(r.naturalMisses>=MAX_NATURAL_MISSES){r.natural=false;r.naturalMisses=0;trace('natural-request-fallback',{uri:r.uri})}}}else if(r.status==='armed')r.armedTransitions=Number(r.armedTransitions||0)+1}save();recoverStaleArmed().catch(()=>{});armDue().catch(()=>{})}
  document.addEventListener('click',e=>{const b=e.target.closest?.('.result');if(!b?.dataset?.uri)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();add(b.dataset.uri,b).catch(err=>{trace('request-add-error',{error:String(err?.message||err)});status('Request toevoegen lukte niet.')})},true);
  window.addEventListener('jfm:trackchange',()=>onTrackChange());window.addEventListener('online',()=>{recoverStaleArmed().catch(()=>{});armDue().catch(()=>{})});
  setInterval(()=>{render();if(document.visibilityState==='visible'){recoverStaleArmed().catch(()=>{});armDue().catch(()=>{})}},7000);
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{ensurePanel();render()});else{ensurePanel();render()}
  window.JFMRequests={version:'requests-v7-radio-gap',add,list:()=>requests.map(r=>({...r})),currentRequest,consumeCurrentRequest,isRequest:t=>!!t&&(requests.some(r=>(r.uri===t.uri||r.track?.id===t.id)&&(r.status==='planned'||r.status==='armed'))||!!currentRequest(t)),eta:t=>{const r=requests.find(x=>x.uri===t?.uri||x.track?.id===t?.id);return r?etaText(r):''},armDue,recoverStaleArmed,log:()=>[...events]};
  window.MAIRRuntime?.register?.('request-manager',{version:'requests-v7-radio-gap',owner:'request-transport'});
})();
