// MAIR Director 3.0 — one explainable 30–60 minute programming horizon.
(()=>{
  'use strict';
  if(window.JFMRotation?.version?.startsWith?.('mair-director-v3'))return;
  const RECENT_WINDOW=30,ARTIST_WINDOW=10,TRACK_COOLDOWN_PLAYS=24,HORIZON_TRACKS=10,STATE_KEY='mair_director_state_v3',clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,n));
  const MODES=new Set(['mair','energy','chill','drive','party','discover','forgotten']),CHANGES=new Set(['more-energy','calmer','older','more-familiar','more-discovery']);
  const nowYear=()=>new Date().getFullYear(),norm=s=>String(s||'').toLowerCase().trim(),read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
  const blank=()=>({satisfaction:.58,recoveryUntil:0,consecutiveRapidSkips:0,rapidSkips:[],mode:'mair',adjustment:null,completed:0,skipped:0,updatedAt:0});
  let adaptive={...blank(),...read(STATE_KEY,{})};if(!MODES.has(adaptive.mode))adaptive.mode='mair';
  function save(reason='update'){adaptive.satisfaction=clamp(Number(adaptive.satisfaction)||.5);adaptive.rapidSkips=(adaptive.rapidSkips||[]).filter(at=>Date.now()-Number(at)<10*60*1000).slice(-8);adaptive.updatedAt=Date.now();try{localStorage.setItem(STATE_KEY,JSON.stringify(adaptive))}catch{};try{window.dispatchEvent(new CustomEvent('mair:director-state',{detail:{...state(),reason}}))}catch{};return state()}
  function memory(){try{return window.jfmDirectorMemory?.()||read('jfm_director_memory',{})}catch{return{}}}
  function skips(){try{return typeof skipMap==='function'?skipMap():read('jfm_skips',{})}catch{return{}}}
  function history(){try{return window.JFMRadioSuite?.state?.()||{lastIds:[],lastArtists:[]}}catch{return{lastIds:[],lastArtists:[]}}}
  function clock(){const c=window.JFMStationClock?.current?.()||{},show=c.show||{};return{show,phase:c.phase||'open',pattern:Array.isArray(show.musicPattern)&&show.musicPattern.length?show.musicPattern:['Familiar','Current','Power','Discovery'],targetMomentum:Number.isFinite(Number(show.targetMomentum))?Number(show.targetMomentum):.66}}
  function year(t){return Number(String(t?.release||t?.album?.release_date||'').slice(0,4))||0}
  function artist(t){return norm(t?.artists?.[0]?.name||t?.artists?.[0]||'')}
  function requested(t){try{return !!window.JFMRequests?.isRequest?.(t)||!!window.jfmIsRequest?.(t)}catch{return false}}
  function isForgotten(t){if(!t?.id||requested(t))return false;const m=memory(),likes=Number(m.likes?.[t.id]||0),plays=Number(m.plays?.[t.id]||0),last=Number(m.lastPlayed?.[t.id]||0),recent=(history().lastIds||[]).slice(0,RECENT_WINDOW);if(recent.includes(t.id)||likes<=0&&plays<2)return false;return!last||Date.now()-last>21*86400000}
  function category(t){if(requested(t))return'Request';if(isForgotten(t))return'Forgotten';if(t?._discovery)return'Discovery';const m=memory(),likes=Number(m.likes?.[t?.id]||0),plays=Number(m.plays?.[t?.id]||0),y=year(t),age=y?nowYear()-y:0;if(likes>=2||plays>=5)return'Power';if(y&&age<=2)return'Current';if(y&&age>=10)return'Throwback';return'Familiar'}
  function momentum(t){const c=category(t),pop=clamp(Number(t?.popularity||55)/100),y=year(t),fresh=y&&nowYear()-y<=2?.07:0,cat=({Power:.13,Current:.09,Request:.07,Discovery:.02,Familiar:0,Forgotten:.01,Throwback:-.05})[c]||0,station=localStorage.getItem('jfm_music_channel_v1')||'mix',stationAdj=station==='party'?.12:station==='sleep'?-.24:station==='chill'?-.12:station==='hits'||station==='top40'?.06:0;return clamp(pop*.72+.18+fresh+cat+stationAdj)}
  function familiarity(t){const m=memory(),id=t?.id||'',taste=Number(window.JFMTasteModel?.score?.(t)||0),pop=Number(t?.popularity||55)/100;return clamp(.25+pop*.38+Number(m.likes?.[id]||0)*.12+Math.min(8,Number(m.plays?.[id]||0))*.035+taste*.012+(isForgotten(t)?.12:0)-(t?._discovery?.28:0))}
  function recovery(){return Number(adaptive.recoveryUntil||0)>Date.now()}
  function discoveryBudget(){const station=localStorage.getItem('jfm_music_channel_v1')||'mix';if(recovery())return.03;let value=adaptive.mode==='discover'?.58:.12+adaptive.satisfaction*.15;if(station==='new')value=clamp(Number(localStorage.getItem('jfm_discovery')||50)/100);if(adaptive.adjustment?.id==='more-discovery')value+=.28;if(adaptive.adjustment?.id==='more-familiar')value-=.2;return clamp(value,.02,.82)}
  function cooldownPenalty(t){const h=history(),ids=(h.lastIds||[]).slice(0,RECENT_WINDOW),artists=(h.lastArtists||[]).slice(0,ARTIST_WINDOW).map(norm),idIndex=ids.indexOf(t?.id),a=artist(t),artistIndex=a?artists.indexOf(a):-1;let p=0;if(idIndex>=0)p-=idIndex<TRACK_COOLDOWN_PLAYS?90-idIndex*2.5:24;if(artistIndex===0)p-=65;else if(artistIndex===1)p-=45;else if(artistIndex===2)p-=30;else if(artistIndex>=3)p-=Math.max(7,24-artistIndex*2);return p}
  function preferenceScore(t){const m=memory(),s=skips(),id=t?.id||'';return Number(m.likes?.[id]||0)*4.6-Number(s[id]||0)*5.2+Number(m.discoveryWins?.[id]||0)*3.2-Number(m.discoveryLosses?.[id]||0)*5+Math.min(10,Number(m.completions?.[id]||0))*1.1}
  function transitionPenalty(t,out=[]){const a=artist(t),recent=(out||[]).slice(-10),cat=category(t);let p=0;for(let back=1;back<=recent.length;back++)if(a&&a===artist(recent[recent.length-back]))p-=[0,120,78,50,34,24,17,12,9,7,5][back]||5;if(recent.some(x=>x?.id===t?.id))p-=150;if(cat==='Discovery'&&recent.slice(-2).some(x=>category(x)==='Discovery'))p-=28;if(cat==='Throwback'&&recent.slice(-3).filter(x=>category(x)==='Throwback').length>=2)p-=10;if(cat==='Request'&&recent.slice(-3).some(requested))p-=14;return p}
  function clockFit(t,out=[]){const c=clock(),slot=(Math.floor(new Date().getMinutes()/10)+(out?.length||0))%c.pattern.length,target=c.pattern[slot],cat=category(t),mom=momentum(t),station=localStorage.getItem('jfm_music_channel_v1')||'mix',targetMomentum=station==='sleep'?.28:c.targetMomentum;let s=cat===target?5.2:(cat==='Request'?3.4:0);s-=Math.abs(mom-targetMomentum)*8;if(c.phase==='top'&&['Power','Current','Request'].includes(cat)&&station!=='sleep')s+=3.2;if(c.phase==='sweep'&&cat==='Discovery')s-=1.5;return s}
  function modeScore(t,out=[]){try{return Number(window.MAIRModeManager?.rotationScore?.(t,out))||0}catch{return 0}}
  function strategies(){
    if(recovery())return['safe','familiar','same-vibe','safe','forgotten','familiar','calmer','safe','familiar','same-vibe'];
    const map={mair:['familiar','same-vibe','discovery','safe','energy-up','forgotten','calmer','familiar','discovery','safe'],energy:['energy-up','power','same-vibe','energy-up','familiar','power','energy-up','safe','same-vibe','power'],chill:['calmer','familiar','same-vibe','calmer','forgotten','safe','calmer','discovery','familiar','calmer'],drive:['familiar','energy-up','same-vibe','power','discovery','energy-up','safe','forgotten','energy-up','familiar'],party:['energy-up','power','same-vibe','energy-up','familiar','energy-up','power','discovery','energy-up','safe'],discover:['safe','discovery','same-vibe','discovery','familiar','discovery','forgotten','safe','discovery','familiar'],forgotten:['forgotten','familiar','forgotten','same-vibe','safe','forgotten','calmer','familiar','forgotten','safe']};
    const result=[...(map[adaptive.mode]||map.mair)],change=adaptive.adjustment?.id;if(change==='more-energy')return result.map((x,i)=>i%3===0?'energy-up':x);if(change==='calmer')return result.map((x,i)=>i%3===0?'calmer':x);if(change==='older')return result.map((x,i)=>i%3===0?'older':x);if(change==='more-familiar')return result.map(x=>x==='discovery'?'safe':x);if(change==='more-discovery')return result.map((x,i)=>i%3===1?'discovery':x);return result
  }
  function slotFit(t,slot,out=[]){const cat=category(t),fam=familiarity(t),mom=momentum(t),last=out.at(-1),budget=discoveryBudget(),age=year(t)?nowYear()-year(t):0;let s=0;if(slot==='familiar'||slot==='safe')s+=fam*18-(cat==='Discovery'?(1-budget)*30:0)+(cat==='Power'?5:0);if(slot==='power')s+=cat==='Power'?18:fam*8;if(slot==='discovery')s+=cat==='Discovery'?16+budget*16:-Math.max(0,budget-.35)*5;if(slot==='forgotten')s+=isForgotten(t)?24:fam*4;if(slot==='energy-up')s-=Math.abs(mom-.84)*20;if(slot==='calmer')s-=Math.abs(mom-.4)*20;if(slot==='older')s+=age>=8?Math.min(18,age*.45):-8;if(slot==='same-vibe'&&last)s-=Math.abs(mom-momentum(last))*22;if(recovery()&&cat==='Discovery')s-=45;if(cat==='Discovery'&&budget<.08)s-=36;return s}
  function score(t,out=[],slot=''){return cooldownPenalty(t)+preferenceScore(t)+transitionPenalty(t,out)+clockFit(t,out)+modeScore(t,out)+slotFit(t,slot||strategies()[(out?.length||0)%HORIZON_TRACKS],out)}
  function reason(t){const special=window.MAIRModeManager?.rotationReason?.(t);if(special)return special;if(requested(t))return'Jouw verzoek staat gepland in de uitzending.';if(recovery())return'Vertrouwde keuze terwijl MAIR herstelt van snelle skips.';if(isForgotten(t))return'Een vergeten favoriet die al een tijd niet voorbij kwam.';if(t?._discovery)return t._discoveryReason||'Nieuwe muziek die past bij je huidige ontdekkingsruimte.';const m=memory(),s=skips(),id=t?.id||'',c=category(t);if(Number(m.likes?.[id]||0)>0)return'Je hebt eerder positief op deze track gereageerd.';if(Number(s[id]||0)>0)return`${c}, met lagere prioriteit door eerdere skips.`;return`${c} past in de komende MAIR-programmering.`}
  function annotate(t,slot=''){if(!t)return t;t._rotationCategory=category(t);t._momentum=momentum(t);t._directorSlot=slot;t._why=reason(t);return t}
  function annotateAll(list=[]){return(list||[]).map(t=>annotate(t))}
  function isHardBlocked(t){if(requested(t))return false;const h=history(),ids=(h.lastIds||[]).slice(0,TRACK_COOLDOWN_PLAYS),artists=(h.lastArtists||[]).slice(0,3).map(norm);return!!t?.id&&(ids.includes(t.id)||!!artist(t)&&artists.includes(artist(t)))}
  function plan(list=[],context=[]){let pool=(list||[]).filter(Boolean),out=[],prefix=(context||[]).filter(Boolean).slice(-10),slots=strategies();const fresh=pool.filter(t=>!isHardBlocked(t));if(fresh.length>=Math.min(HORIZON_TRACKS,pool.length))pool=fresh;while(pool.length){const slot=slots[out.length%slots.length];let best=0,bestScore=-Infinity;for(let i=0;i<pool.length;i++){const value=score(pool[i],[...prefix,...out],slot);if(value>bestScore){bestScore=value;best=i}}out.push(annotate(pool.splice(best,1)[0],slot))}return out}
  function setMode(id='mair'){if(!MODES.has(id))return false;adaptive.mode=id;adaptive.adjustment=null;save('mode');return true}
  function change(id){if(!CHANGES.has(id))return false;adaptive.adjustment={id,remaining:HORIZON_TRACKS,expiresAt:Date.now()+45*60*1000};save('change');return true}
  function state(){const slots=strategies(),recoveryActive=recovery();return{version:'mair-director-v3-horizon',mode:adaptive.mode,satisfaction:adaptive.satisfaction,recovery:recoveryActive,recoveryUntil:recoveryActive?adaptive.recoveryUntil:0,consecutiveRapidSkips:adaptive.consecutiveRapidSkips,adjustment:adaptive.adjustment?{...adaptive.adjustment}:null,discoveryBudget:discoveryBudget(),strategy:[...slots],horizonTracks:HORIZON_TRACKS,completed:Number(adaptive.completed||0),skipped:Number(adaptive.skipped||0)}}
  function rememberCompletion(detail={}){const track=detail.fromTrack||{},id=String(track.trackId||track.id||detail.fromTrackId||'');if(!id)return;try{const m=read('jfm_director_memory',{});m.completions=m.completions||{};m.completions[id]=Math.min(999,Number(m.completions[id]||0)+1);localStorage.setItem('jfm_director_memory',JSON.stringify(m))}catch{}}
  function transition(detail={}){const cause=String(detail.cause||'');if(cause==='NATURAL_END'){rememberCompletion(detail);adaptive.completed=Number(adaptive.completed||0)+1;adaptive.consecutiveRapidSkips=Math.max(0,Number(adaptive.consecutiveRapidSkips||0)-1);adaptive.satisfaction=clamp(adaptive.satisfaction+.028);if(adaptive.satisfaction>.7)adaptive.recoveryUntil=0;save('completed');return}if(cause!=='USER_NEXT')return;const position=Number(detail.fromTrack?.progressMs||detail.fromTrack?.positionMs||0),duration=Number(detail.fromTrack?.durationMs||0),fast=position<45000||duration>0&&position/duration<.22,now=Date.now();adaptive.skipped=Number(adaptive.skipped||0)+1;adaptive.consecutiveRapidSkips=fast?Number(adaptive.consecutiveRapidSkips||0)+1:Math.max(0,Number(adaptive.consecutiveRapidSkips||0)-1);adaptive.satisfaction=clamp(adaptive.satisfaction-(fast?.13:.055));if(fast)adaptive.rapidSkips=[...(adaptive.rapidSkips||[]),now].filter(at=>now-at<6*60*1000);if(adaptive.consecutiveRapidSkips>=2||(adaptive.rapidSkips||[]).length>=2)adaptive.recoveryUntil=now+20*60*1000;save(recovery()?'rapid-recovery':'skip')}
  window.addEventListener?.('mair:track-transition',e=>transition(e.detail||{}));window.addEventListener?.('mair:taste-feedback',e=>{adaptive.satisfaction=clamp(adaptive.satisfaction+(e.detail?.type==='more'?.09:-.11));if(e.detail?.type==='more'&&adaptive.satisfaction>.72)adaptive.recoveryUntil=0;save('taste')});
  window.addEventListener?.('jfm:trackchange',()=>{const a=adaptive.adjustment;if(!a)return;if(Date.now()>Number(a.expiresAt||0)||--a.remaining<=0)adaptive.adjustment=null;save('adjustment-progress')});
  if(typeof document!=='undefined')document.addEventListener?.('click',e=>{if(e.target.closest?.('#clearHistory'))setTimeout(()=>{adaptive=blank();save('reset')},0)},true);
  window.JFMRotation={version:'mair-director-v3-horizon',category,score,reason,annotate,annotateAll,isHardBlocked,cooldownPenalty,preferenceScore,modeScore,transitionPenalty,clockFit,momentum,familiarity,isForgotten,clockProfile:clock,plan,setMode,change,state,strategies,noteTransition:transition};
  window.MAIRRuntime?.register?.('mair-director',{version:'mair-director-v3-horizon',owner:'music-programming'});save('boot');
})();
