// Josh FM Smart DJ — generative first, local fallback, session memory, varied break types.
(()=>{
const recentKey='jfm_dj_recent';const recent=()=>{try{return JSON.parse(localStorage.getItem(recentKey)||'[]')}catch{return[]}};const remember=s=>{const r=recent();r.unshift(s);localStorage.setItem(recentKey,JSON.stringify(r.slice(0,30)))};const pick=a=>a[Math.floor(Math.random()*a.length)];const artists=t=>(t?.artists||[]).join(' en ');const title=t=>t?.name||'';const year=t=>Number(String(t?.release||'').slice(0,4))||null;const req=t=>typeof window.jfmIsRequest==='function'&&window.jfmIsRequest(t);const chance=n=>Math.random()<n;
function queueNext(){try{return window.jfmUpcoming?.()?.[0]||null}catch{return null}}function current(){return playback?.item?trackObj(playback.item):null}function clean(s){return s.replace(/\s+/g,' ').replace(/\s+([,.!?])/g,'$1').trim()}function notRecent(a){const r=recent().join(' ').toLowerCase();const f=a.filter(x=>!r.includes(x.toLowerCase().slice(0,34)));return pick(f.length?f:a)}
function chooseLength(manual){if(manual)return pick(['short','medium','medium','long']);const r=Math.random();return r<.24?'micro':r<.55?'short':r<.9?'medium':'long'}
function chooseBreakType(manual){if(manual)return pick(['vrije studiobreak','muziekobservatie','mini-verhaal']);if(window.jfmHourMarker){window.jfmHourMarker=false;return'uur-opener met tijd en zenderidentiteit'}const r=Math.random();if(r<.18)return'niet-muzikale sfeerbreak';if(r<.38)return'creatieve overgang';if(r<.56)return'mini-verhaal rond muziek';if(r<.72)return'vooruitblik op volgende plaat';if(r<.86)return'korte droge studiobreak';return'verzoek of luistercontext'}
function softenFact(text=''){let x=String(text).replace(/\[[^\]]*\]/g,'').replace(/\([^)]*bron[^)]*\)/gi,'').trim().replace(/^het nummer\s+/i,'').replace(/^de single\s+/i,'').replace(/^het lied\s+/i,'').replace(/\.$/,'');if(x.length>170)x=x.slice(0,167).replace(/\s+\S*$/,'')+'…';return x}
function factScene(t,f){if(!f?.text)return'';const x=softenFact(f.text);if(!x)return'';const s=title(t),a=artists(t);return notRecent([`${x}. En ja, dat verhaal hoort dus bij ${s} van ${a}.`,`Soms heeft een plaat meer bagage dan je hoort. ${x}. We hebben het over ${s} van ${a}.`,`Luister de volgende keer nét even anders naar deze: ${x}. ${s}, ${a}.`,`Je hoort een paar minuten muziek, maar daarachter zit dit: ${x}. ${a} met ${s}.`,`${x}. Best bijzonder eigenlijk. Dat was dus ${s} van ${a}.`])}
async function reversePlace(lat,lon){try{const k=`jfm_place_${lat.toFixed(2)}_${lon.toFixed(2)}`,c=JSON.parse(localStorage.getItem(k)||'null');if(c&&Date.now()-c.at<86400000)return c.name;const r=await fetch(`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${encodeURIComponent(lat)}&longitude=${encodeURIComponent(lon)}&localityLanguage=nl`);if(!r.ok)return'';const d=await r.json(),name=d.city||d.locality||d.principalSubdivision||d.countryName||'';if(name)localStorage.setItem(k,JSON.stringify({at:Date.now(),name}));return name}catch{return''}}
window.getWeather=getWeather=async function(){if(!document.getElementById('weatherMention')?.checked)return null;if(weatherCache&&Date.now()-weatherCache.at<1200000)return weatherCache.data;return new Promise(resolve=>{if(!navigator.geolocation)return resolve(null);navigator.geolocation.getCurrentPosition(async p=>{try{const{latitude,longitude}=p.coords;const[r,location]=await Promise.all([fetch(`https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current=temperature_2m,weather_code&timezone=auto`),reversePlace(latitude,longitude)]);const d=await r.json(),temp=Math.round(d.current?.temperature_2m),data=Number.isFinite(temp)?{temperature:temp,code:d.current?.weather_code,location}:null;weatherCache={at:Date.now(),data};resolve(data)}catch{resolve(null)}},()=>resolve(null),{timeout:6000,maximumAge:900000})})};
window.weatherText=weatherText=w=>{if(!w)return'';const c=w.code;let x='';if(c===0)x='helder';else if(c<=3)x='bewolkt';else if(c<=48)x='mistig';else if(c<=67)x='regenachtig';else if(c<=77)x='winters';else if(c<=82)x='met buien';else if(c>=95)x='onweersachtig';return`${w.location?'in '+w.location+' ':''}${w.temperature} graden${x?' en '+x:''}`};
function transition(prev,now){if(!now)return'Je luistert naar Josh FM.';if(req(now))return notRecent([`Deze kwam binnen als verzoek: ${title(now)} van ${artists(now)}.`,`De luisteraar bepaalt even. ${title(now)} van ${artists(now)}, op verzoek.`]);if(!prev)return `${title(now)} van ${artists(now)} op Josh FM.`;const py=year(prev),ny=year(now),same=(prev.artists||[]).some(a=>(now.artists||[]).includes(a));if(same)return `${artists(now)} krijgt nog een ronde. Eerst ${title(prev)}, nu ${title(now)}.`;if(py&&ny&&Math.abs(py-ny)>14)return `Geen regels hier. Van ${py} rechtstreeks naar ${ny}, met ${title(now)} van ${artists(now)}.`;return notRecent([`Dat was ${title(prev)}. Deze kant op: ${title(now)} van ${artists(now)}.`,`Nieuwe bocht in de set: ${title(now)} van ${artists(now)}.`,`We laten ${title(prev)} achter ons en schuiven door naar ${title(now)} van ${artists(now)}.`])}
function localBreak(previous,fact,weather,manual){const now=current(),next=queueNext(),mode=settings?.mode||'normal',parts=[];const type=chooseBreakType(manual),factFirst=fact?.text&&chance(.35);if(type.includes('niet-muzikale')){if(weather&&chance(.65))parts.push(`Even buiten de studio: ${weather}.`);else parts.push(notRecent(['Soms hoef je een goeie radioset niet uit te leggen. Gewoon laten lopen.','Geen groot verhaal hier. Muziek aan en verder.','Dit is zo’n moment waarop de set zichzelf wel redt.']))}else{if(factFirst){const l=factScene(previous||now,fact);if(l)parts.push(l)}if(!factFirst||chance(.55))parts.push(transition(previous,now));if(fact?.text&&!factFirst&&chance(.62)){const l=factScene(previous||now,fact);if(l)parts.push(l)}}if(next&&chance(.32))parts.push(req(next)?`Verderop staat nog een verzoek klaar: ${title(next)} van ${artists(next)}.`:`Straks nog ${title(next)} van ${artists(next)}.`);if(document.getElementById('timeMention')?.checked&&chance(.16))parts.push(`Het is ${new Date().toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'})}.`);const tails={normal:['En door.','Muziek terug aan.','We rollen verder.'],morning:['Koffie erbij, wij regelen de muziek.'],chill:['Geen haast. Laat maar lopen.'],party:['Genoeg gepraat. Gas erop.'],throwback:['Tijdmachine blijft aan.'],late:['We blijven nog even hangen.']};if(chance(.3))parts.push(pick(tails[mode]||tails.normal));return clean(parts.join(' '))}
async function aiBreak(previous,fact,weather,manual){const now=current(),next=queueNext(),desiredLength=chooseLength(manual),breakType=chooseBreakType(manual);const payload={previousTrack:previous||null,currentTrack:now,nextTrack:next,fact:fact?.text||'',factSource:fact?.source||'',time:document.getElementById('timeMention')?.checked?new Date().toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'}):'',weather:weatherText?weatherText(weather):'',mode:MODES?.[settings?.mode||'normal']||settings?.mode,manual,session:(session||[]).slice(0,10),recentDJ:recent(),desiredLength,breakType,requests:{current:req(now),next:req(next)}};try{const r=await fetch('/api/dj',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(r.ok){const d=await r.json();if(d?.text)return clean(d.text)}}catch{}return''}
window.makeDJScript=makeDJScript=async function(track,fact,weather,manual){let out=await aiBreak(track,fact,weather,manual);if(!out)out=localBreak(track,fact,weatherText?weatherText(weather):'',manual);remember(out);window.jfmLastDJText=out;return out};
})();