// Josh FM Smart DJ — highly varied local radio personality + location-aware weather.
(()=>{
const recentKey='jfm_dj_recent';const recent=()=>{try{return JSON.parse(localStorage.getItem(recentKey)||'[]')}catch{return[]}};const remember=s=>{const r=recent();r.unshift(s);localStorage.setItem(recentKey,JSON.stringify(r.slice(0,30)))};const pick=a=>a[Math.floor(Math.random()*a.length)];const artists=t=>(t?.artists||[]).join(' en ');const title=t=>t?.name||'';const year=t=>Number(String(t?.release||'').slice(0,4))||null;const req=t=>typeof window.jfmIsRequest==='function'&&window.jfmIsRequest(t);const chance=n=>Math.random()<n;
function queueNext(){try{return window.jfmUpcoming?.()?.[0]||null}catch{return null}}function current(){return playback?.item?trackObj(playback.item):null}function clean(s){return s.replace(/\s+/g,' ').replace(/\s+([,.!?])/g,'$1').trim()}function notRecent(a){const r=recent().join(' ').toLowerCase();const f=a.filter(x=>!r.includes(x.toLowerCase().slice(0,34)));return pick(f.length?f:a)}
function softenFact(text=''){let x=String(text).replace(/\[[^\]]*\]/g,'').replace(/\([^)]*bron[^)]*\)/gi,'').trim().replace(/^het nummer\s+/i,'').replace(/^de single\s+/i,'').replace(/^het lied\s+/i,'').replace(/\.$/,'');if(x.length>170)x=x.slice(0,167).replace(/\s+\S*$/,'')+'…';return x}
function factScene(t,f){if(!f?.text)return'';const x=softenFact(f.text);if(!x)return'';const s=title(t),a=artists(t);return notRecent([
`${x}. En ja, dat verhaal hoort dus bij ${s} van ${a}.`,
`${x}. Niet meteen het eerste waar je aan denkt als ${s} langskomt, maar precies daarom is het leuk.`,
`Soms heeft een plaat meer bagage dan je hoort. ${x}. We hebben het over ${s} van ${a}.`,
`Luister de volgende keer nét even anders naar deze: ${x}. ${s}, ${a}.`,
`Stel je voor: ${x}. En uit dat verhaal komt dus ${s} van ${a}.`,
`Er zit hier een klein verhaal verstopt. ${x}. Dat was dus ${s} van ${a}.`,
`${x}. Best bijzonder eigenlijk. En ondertussen klinkt ${s} alsof het nooit anders bedoeld is geweest.`,
`Je hoort een paar minuten muziek, maar daarachter zit dit: ${x}. ${a} met ${s}.`,
`Dit soort dingen hoor je niet in de eerste drie seconden van een plaat: ${x}. We hadden het over ${s}.`,
`${x}. Goed verhaal, maar uiteindelijk telt maar één ding: klinkt-ie lekker? ${s} van ${a}.`
])}
async function reversePlace(lat,lon){try{const k=`jfm_place_${lat.toFixed(2)}_${lon.toFixed(2)}`,c=JSON.parse(localStorage.getItem(k)||'null');if(c&&Date.now()-c.at<86400000)return c.name;const r=await fetch(`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${encodeURIComponent(lat)}&longitude=${encodeURIComponent(lon)}&localityLanguage=nl`);if(!r.ok)return'';const d=await r.json(),name=d.city||d.locality||d.principalSubdivision||d.countryName||'';if(name)localStorage.setItem(k,JSON.stringify({at:Date.now(),name}));return name}catch{return''}}
window.getWeather=getWeather=async function(){if(!document.getElementById('weatherMention')?.checked)return null;if(weatherCache&&Date.now()-weatherCache.at<1200000)return weatherCache.data;return new Promise(resolve=>{if(!navigator.geolocation)return resolve(null);navigator.geolocation.getCurrentPosition(async p=>{try{const{latitude,longitude}=p.coords;const[r,location]=await Promise.all([fetch(`https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current=temperature_2m,weather_code&timezone=auto`),reversePlace(latitude,longitude)]);const d=await r.json(),temp=Math.round(d.current?.temperature_2m),data=Number.isFinite(temp)?{temperature:temp,code:d.current?.weather_code,location}:null;weatherCache={at:Date.now(),data};resolve(data)}catch{resolve(null)}},()=>resolve(null),{timeout:6000,maximumAge:900000})})};
window.weatherText=weatherText=w=>{if(!w)return'';const c=w.code;let x='';if(c===0)x='helder';else if(c<=3)x='bewolkt';else if(c<=48)x='mistig';else if(c<=67)x='regenachtig';else if(c<=77)x='winters';else if(c<=82)x='met buien';else if(c>=95)x='onweersachtig';return`${w.location?'in '+w.location+' ':''}${w.temperature} graden${x?' en '+x:''}`};
function transition(prev,now){if(!now)return'Je luistert naar Josh FM.';if(req(now))return notRecent([`Oké, iemand heeft smaak. Deze kwam binnen als verzoek: ${title(now)} van ${artists(now)}.`,`Deze stond niet toevallig klaar. Verzoekje binnen, volume omhoog: ${title(now)} van ${artists(now)}.`,`De luisteraar bepaalt even. ${title(now)} van ${artists(now)}, op verzoek.`]);if(!prev)return notRecent([`${title(now)} van ${artists(now)} op Josh FM.`,`We zijn onderweg met ${title(now)} van ${artists(now)}.`]);const py=year(prev),ny=year(now),same=(prev.artists||[]).some(a=>(now.artists||[]).includes(a));if(same)return notRecent([`${artists(now)} krijgt gewoon nog een ronde. Eerst ${title(prev)}, nu ${title(now)}.`,`Blijkbaar waren we nog niet klaar met ${artists(now)}. ${title(now)} mag erachteraan.`]);if(py&&ny&&Math.abs(py-ny)>14)return notRecent([`${py} ligt ineens heel ver achter ons. We landen in ${ny}: ${title(now)} van ${artists(now)}.`,`Geen regels hier. Van ${py} rechtstreeks naar ${ny}, met ${title(now)} van ${artists(now)}.`]);return notRecent([`Dat was ${title(prev)}. Deze kant op: ${title(now)} van ${artists(now)}.`,`Nieuwe bocht in de set: ${title(now)} van ${artists(now)}.`,`We laten ${title(prev)} achter ons en schuiven door naar ${title(now)} van ${artists(now)}.`,`En zonder lange vergadering: ${title(now)} van ${artists(now)}.`])}
function localBreak(previous,fact,weather,manual){const now=current(),next=queueNext(),mode=settings?.mode||'normal',parts=[];const factFirst=fact?.text&&chance(.38);if(factFirst){const l=factScene(previous||now,fact);if(l)parts.push(l)}
if(manual)parts.push(now?notRecent([`Josh FM is wakker. ${title(now)} van ${artists(now)} staat aan.`,`Daar zijn we. ${title(now)} van ${artists(now)}, en we gaan vanaf hier verder.`,`Studio aan, muziek aan. ${title(now)} van ${artists(now)}.`]):'Josh FM is wakker.');else if(!factFirst||chance(.55))parts.push(transition(previous,now));
if(fact?.text&&!factFirst&&chance(.67)){const l=factScene(previous||now,fact);if(l)parts.push(l)}
if(weather&&chance(.27))parts.push(notRecent([`Mocht je naar buiten kijken: ${weather}.`,`Voor de mensen die zo de deur uit moeten: ${weather}.`,`Even buiten de studio: ${weather}.`,`En terwijl deze set binnen lekker doorloopt: buiten is het ${weather}.`]));
if(document.getElementById('timeMention')?.checked&&chance(.18))parts.push(notRecent([`Op de klok ${new Date().toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'})}.`,`Het is inmiddels ${new Date().toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'})}.`]));
if(next&&chance(.34))parts.push(req(next)?`Ik zie trouwens nog een verzoek in de rij: ${title(next)} van ${artists(next)}.`:notRecent([`Ik verklap er alvast één: straks ${title(next)} van ${artists(next)}.`,`Verderop wacht ${title(next)} van ${artists(next)}.`,`Niet weglopen, ${title(next)} van ${artists(next)} komt er ook nog aan.`]));
const tails={normal:['En door.','Muziek terug aan.','Goed, genoeg woorden.','We rollen verder.','Dat gezegd hebbende: volume omhoog.'],morning:['Koffie erbij, wij regelen de muziek.','De ochtend kan beginnen.'],chill:['Geen haast. Laat maar lopen.','We houden het soepel.'],party:['Genoeg gepraat. Gas erop.','We gaan niet stilvallen.'],throwback:['Tijdmachine blijft aan.','We blijven nog even graven.'],late:['De nacht is nog jong genoeg.','We blijven nog even hangen.']};if(chance(.38))parts.push(notRecent(tails[mode]||tails.normal));const out=clean(parts.join(' '));remember(out);return out}
window.makeDJScript=makeDJScript=async function(track,fact,weather,manual){return localBreak(track,fact,weatherText?weatherText(weather):'',manual)};
})();