// Josh FM Smart DJ — bilingual free broadcast-clock engine.
(()=>{
const RECENT_KEY='jfm_dj_recent_lang_v1';
const recent=()=>{try{return JSON.parse(localStorage.getItem(RECENT_KEY)||'[]')}catch{return[]}};
const remember=s=>{if(!s)return;const r=recent();r.unshift(s);localStorage.setItem(RECENT_KEY,JSON.stringify(r.slice(0,40)))};
const pick=a=>a[Math.floor(Math.random()*a.length)];const chance=n=>Math.random()<n;
const lang=()=>window.JFMDJLanguage||localStorage.getItem('jfm_dj_language')||'en';
const isNL=()=>lang().toLowerCase().startsWith('nl');
const L=(en,nl)=>isNL()?nl:en;
const joinArtists=t=>(t?.artists||[]).join(isNL()?' en ':' and ');
const title=t=>t?.name||'';const year=t=>Number(String(t?.release||'').slice(0,4))||null;
const req=t=>typeof window.jfmIsRequest==='function'&&window.jfmIsRequest(t);
const clean=s=>String(s||'').replace(/\s+/g,' ').replace(/\s+([,.!?])/g,'$1').trim();
function current(){try{return playback?.item?trackObj(playback.item):null}catch{return null}}
function nextTrack(){try{return window.jfmUpcoming?.()?.[0]||null}catch{return null}}
function notRecent(options){const used=recent().join(' ').toLowerCase();const fresh=options.filter(x=>x&&!used.includes(x.toLowerCase().slice(0,42)));return pick(fresh.length?fresh:options.filter(Boolean))||''}
function stationId(){return notRecent(isNL()?['Dit is Josh FM.','Je luistert naar Josh FM.','Josh FM. Jouw muziek, jouw station.','Blijf hier. Dit is Josh FM.']:['This is Josh FM.','You are listening to Josh FM.','Josh FM. Your music, your station.','Stay right here. This is Josh FM.'])}
function daypart(){const h=new Date().getHours();if(h<6)return'night';if(h<10)return'morning';if(h<12)return'late-morning';if(h<17)return'afternoon';if(h<20)return'early-evening';if(h<23)return'evening';return'late-evening'}
function moodLine(){const d=daypart();const en={night:['Still awake? I’ve got the music covered.','Late night on Josh FM. Let’s keep it moving.'],morning:['Good morning. Let’s get this day moving.','Morning on Josh FM. Music first, everything else later.'],'late-morning':['The morning is moving along nicely.','Late morning, and the music keeps coming.'],afternoon:['Afternoon on Josh FM. Let’s keep the soundtrack going.','We’re keeping the afternoon moving.'],'early-evening':['The day may be winding down, but we’re not.','Early evening on Josh FM. Time to switch off a little.'],evening:['Evening on Josh FM. Let the music do the work.','The evening is underway. We’re staying right here.'],'late-evening':['It’s getting late, but there’s still plenty of music left.','Late evening on Josh FM. One more tune is never really one more.']};const nl={night:['Nog wakker? Ik heb de muziek geregeld.','Late night op Josh FM. We gaan nog even door.'],morning:['Goedemorgen. Tijd om de dag op gang te krijgen.','Ochtend op Josh FM. Eerst muziek, de rest komt later.'],'late-morning':['De ochtend loopt lekker door.','Late ochtend, en de muziek blijft komen.'],afternoon:['Middag op Josh FM. We houden de soundtrack aan.','We houden de middag in beweging.'],'early-evening':['De dag loopt langzaam af, maar wij nog niet.','Vooravond op Josh FM. Tijd om een beetje af te schakelen.'],evening:['Avond op Josh FM. Laat de muziek het werk doen.','De avond is begonnen. Wij blijven hier.'],'late-evening':['Het wordt laat, maar er is nog genoeg muziek over.','Late avond op Josh FM. Nog eentje kan altijd.']};return notRecent((isNL()?nl:en)[d])}
function softenFact(text=''){let x=String(text).replace(/\[[^\]]*\]/g,'').replace(/\([^)]*(source|bron)[^)]*\)/gi,'').replace(/\b(Wikipedia|MusicBrainz|Spotify|metadata|source|database|bron|databank)\b/gi,'').trim().replace(/\.$/,'');if(x.length>180)x=x.slice(0,177).replace(/\s+\S*$/,'')+'…';return x}
function factBreak(t,f){if(!t||!f?.text)return'';const x=softenFact(f.text);if(!x)return'';return notRecent(isNL()?[`${x}. Dat was het verhaal achter ${title(t)} van ${joinArtists(t)}.`,`${x}. Met dat in je achterhoofd klinkt ${title(t)} van ${joinArtists(t)} toch net even anders.`]:[`${x}. That was the story behind ${title(t)} by ${joinArtists(t)}.`,`${x}. Keep that in mind next time you hear ${title(t)} by ${joinArtists(t)}.`])}
function backsell(t){if(!t)return'';return notRecent(isNL()?[`Dat was ${joinArtists(t)} met ${title(t)}.`,`Je hoorde ${title(t)} van ${joinArtists(t)}.`,`${joinArtists(t)}, ${title(t)}. Die werkt nog steeds.`]:[`That was ${joinArtists(t)} with ${title(t)}.`,`You just heard ${title(t)} by ${joinArtists(t)}.`,`${joinArtists(t)}, ${title(t)}. That one still works.`])}
function frontsell(t){if(!t)return'';if(req(t))return notRecent(isNL()?[`Deze kwam binnen als verzoek: ${joinArtists(t)} met ${title(t)}.`,`Op verzoek: ${title(t)} van ${joinArtists(t)}.`]:[`This one came in as a request: ${joinArtists(t)} with ${title(t)}.`,`A request for you now. ${title(t)} by ${joinArtists(t)}.`]);return notRecent(isNL()?[`Nu ${joinArtists(t)} met ${title(t)}.`,`Hier is ${title(t)} van ${joinArtists(t)}.`,`Door met ${joinArtists(t)} en ${title(t)}.`]:[`Now, ${joinArtists(t)} with ${title(t)}.`,`Here’s ${title(t)} by ${joinArtists(t)}.`,`Let’s keep moving with ${joinArtists(t)} and ${title(t)}.`])}
function tease(t){if(!t)return'';return notRecent(isNL()?[`Blijf nog even hangen. ${joinArtists(t)} komt hierna.`,`Hierna: ${title(t)} van ${joinArtists(t)}.`]:[`Stay with me. ${joinArtists(t)} is coming up next.`,`Still to come: ${title(t)} by ${joinArtists(t)}.`])}
function bridge(prev,now){if(!now)return stationId();if(req(now))return frontsell(now);if(!prev)return frontsell(now);const py=year(prev),ny=year(now),same=(prev.artists||[]).some(a=>(now.artists||[]).includes(a));if(same)return notRecent(isNL()?[`${joinArtists(now)} nog een keer. Net ${title(prev)}, nu ${title(now)}.`]:[`${joinArtists(now)} again. That was ${title(prev)}, and now here’s ${title(now)}.`]);if(py&&ny&&Math.abs(py-ny)>=15&&chance(.55))return L(`From ${py} to ${ny} in one jump. Here’s ${joinArtists(now)} with ${title(now)}.`,`Van ${py} naar ${ny} in één stap. Nu ${joinArtists(now)} met ${title(now)}.`);return clean(`${backsell(prev)} ${L('And now,','En nu')} ${joinArtists(now)} ${L('with','met')} ${title(now)}.`)}
function weatherLine(w){if(!w)return'';const loc=w.location?L(` in ${w.location}`,` in ${w.location}`):'';const c=w.code;let en='',nl='';if(c===0){en='clear';nl='helder'}else if(c<=3){en='cloudy';nl='bewolkt'}else if(c<=48){en='misty';nl='mistig'}else if(c<=67){en='rainy';nl='regenachtig'}else if(c<=77){en='wintry';nl='winters'}else if(c<=82){en='showery';nl='met buien'}else if(c>=95){en='stormy';nl='onweersachtig'};return isNL()?`Buiten${loc} is het ${w.temperature} graden${nl?' en '+nl:''}. Hier blijft de muziek aan.`:`Outside${loc}, it’s ${w.temperature} degrees${en?' and '+en:''}. In here, the music keeps going.`}
function timeLine(){return isNL()?`Het is ${new Date().toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'})}.`:`It’s ${new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}.`}
function chooseIntent({manual,now,next,fact,weather}){if(manual)return fact?.text?'manual-fact':'manual-react';if(window.jfmHourMarker){window.jfmHourMarker=false;return'hour-opener'}if(req(now))return'request';const pool=['bridge','bridge','backsell-frontsell','backsell-frontsell','micro','micro'];if(fact?.text)pool.push('fact','fact');if(next)pool.push('tease');if(weather&&document.getElementById('weatherMention')?.checked)pool.push('weather');if(document.getElementById('timeMention')?.checked)pool.push('time');pool.push('companion','station-id');return pick(pool)}
function localBreak(previous,fact,weather,manual){const now=current(),next=nextTrack(),intent=chooseIntent({manual,now,next,fact,weather});let out='';switch(intent){case'manual-fact':out=factBreak(previous||now,fact);break;case'manual-react':out=previous?clean(`${backsell(previous)} ${L('That landed nicely.','Die zat precies goed.')}`):stationId();break;case'hour-opener':out=clean(`${stationId()} ${moodLine()}${now?' '+frontsell(now):''}`);break;case'request':out=frontsell(now);break;case'fact':out=factBreak(previous||now,fact);break;case'tease':out=clean(`${previous?backsell(previous):''} ${tease(next)}`);break;case'weather':out=clean(`${weatherLine(weather)}${now?' '+frontsell(now):''}`);break;case'time':out=clean(`${timeLine()}${now?' '+frontsell(now):''}`);break;case'companion':out=clean(`${moodLine()}${now&&chance(.65)?' '+frontsell(now):''}`);break;case'station-id':out=clean(`${stationId()}${now?' '+frontsell(now):''}`);break;case'backsell-frontsell':out=bridge(previous,now);break;default:out=now?frontsell(now):(previous?backsell(previous):stationId())}const max=manual?320:235;if(out.length>max){const sentences=out.match(/[^.!?]+[.!?]/g)||[];out=clean(sentences.slice(0,2).join(' '))}return clean(out)}
async function reversePlace(lat,lon){try{const code=isNL()?'nl':'en';const k=`jfm_place_${code}_${lat.toFixed(2)}_${lon.toFixed(2)}`,c=JSON.parse(localStorage.getItem(k)||'null');if(c&&Date.now()-c.at<86400000)return c.name;const r=await fetch(`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${encodeURIComponent(lat)}&longitude=${encodeURIComponent(lon)}&localityLanguage=${code}`);if(!r.ok)return'';const d=await r.json(),name=d.city||d.locality||d.principalSubdivision||d.countryName||'';if(name)localStorage.setItem(k,JSON.stringify({at:Date.now(),name}));return name}catch{return''}}
window.getWeather=getWeather=async function(){if(!document.getElementById('weatherMention')?.checked)return null;if(weatherCache&&Date.now()-weatherCache.at<1200000)return weatherCache.data;return new Promise(resolve=>{if(!navigator.geolocation)return resolve(null);navigator.geolocation.getCurrentPosition(async p=>{try{const{latitude,longitude}=p.coords;const[r,location]=await Promise.all([fetch(`https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current=temperature_2m,weather_code&timezone=auto`),reversePlace(latitude,longitude)]);const d=await r.json(),temp=Math.round(d.current?.temperature_2m),data=Number.isFinite(temp)?{temperature:temp,code:d.current?.weather_code,location}:null;weatherCache={at:Date.now(),data};resolve(data)}catch{resolve(null)}},()=>resolve(null),{timeout:6000,maximumAge:900000})})};window.weatherText=weatherText=w=>w||null;
window.makeDJScript=makeDJScript=async function(track,fact,weather,manual){let out=localBreak(track,fact,weather,manual);if(!out)out=stationId();remember(out);window.jfmLastDJText=out;return out};window.JFMRadioClock={version:'free-radio-clock-bilingual-v1',localBreak,recent,get language(){return lang()}};
})();