// MAIR Station Clock — one source of truth for shows, dayparts, presenters and radio moments.
(()=>{
  const $=id=>document.getElementById(id),pad=n=>String(n).padStart(2,'0');
  const SHOWS=[
    {id:'after-hours',name:'MAIR After Hours',start:0,end:6,mode:'late',djId:'noah',tone:'low-key overnight radio',format:'music-first, calm links',targetMomentum:.42,musicPattern:['Familiar','Throwback','Discovery','Familiar']},
    {id:'morning',name:'MAIR Morning',start:6,end:10,mode:'morning',djId:'josh',tone:'bright morning radio',format:'fresh, concise, useful clock hits',targetMomentum:.72,musicPattern:['Power','Current','Familiar','Discovery','Power','Current']},
    {id:'daytime',name:'MAIR Daytime',start:10,end:16,mode:'normal',djId:'maya',tone:'music-first daytime radio',format:'warm, familiar, low interruption',targetMomentum:.65,musicPattern:['Familiar','Current','Power','Discovery','Familiar','Current']},
    {id:'drive',name:'MAIR Drive',start:16,end:20,mode:'normal',djId:'max',tone:'upbeat drive-time radio',format:'momentum, short punchy links',targetMomentum:.82,musicPattern:['Power','Current','Power','Familiar','Discovery','Current']},
    {id:'evening',name:'MAIR Evening',start:20,end:23,mode:'chill',djId:'maya',tone:'warm evening radio',format:'atmosphere, discovery and familiar songs',targetMomentum:.58,musicPattern:['Familiar','Discovery','Current','Throwback','Familiar']},
    {id:'late-night',name:'MAIR Late Night',start:23,end:24,mode:'late',djId:'noah',tone:'calm late-night radio',format:'curated, sparse and confident',targetMomentum:.45,musicPattern:['Familiar','Throwback','Discovery','Familiar']}
  ];
  const SPECIALS=[
    {id:'weekend-warmup',name:'MAIR Weekend Warm-up',days:[5],start:20,end:23,mode:'party',djId:'max',tone:'weekend energy',format:'fast, celebratory, music-forward',targetMomentum:.86,preferredStation:'party',musicPattern:['Power','Current','Power','Familiar','Current']},
    {id:'new-music',name:'MAIR New Music',days:[6],start:10,end:12,mode:'normal',djId:'noah',tone:'curious and informed',format:'new music with concise context',targetMomentum:.68,preferredStation:'new',musicPattern:['Current','Discovery','Current','Discovery','Power']},
    {id:'saturday-night',name:'MAIR Saturday Night',days:[6],start:20,end:24,mode:'party',djId:'max',tone:'high-energy Saturday radio',format:'party momentum and very short links',targetMomentum:.9,preferredStation:'party',musicPattern:['Power','Current','Power','Current','Familiar']},
    {id:'throwback-lunch',name:'MAIR Throwback Lunch',days:[0],start:12,end:14,mode:'throwback',djId:'noah',tone:'nostalgic but modern',format:'recognition, stories only when grounded',targetMomentum:.58,preferredStation:'throwback',musicPattern:['Throwback','Familiar','Throwback','Power']},
    {id:'top40',name:'MAIR Top 40',days:[0],start:16,end:18,mode:'normal',djId:'josh',tone:'confident chart radio',format:'chart pace, clean IDs, strong openers',targetMomentum:.8,preferredStation:'top40',musicPattern:['Power','Current','Power','Current','Familiar']}
  ];
  const MOMENTS=[{minute:0,type:'top',label:'Top of hour'},{minute:15,type:'quarter',label:'Quarter-hour ID'},{minute:30,type:'half',label:'Half-hour show ID'},{minute:45,type:'quarter',label:'Quarter-hour ID'}];
  let lastShow='',lastMomentKey='',lastTick=0;const log=[];
  function trace(stage,extra={}){log.unshift({at:Date.now(),stage,...extra});if(log.length>80)log.length=80}
  function specialAt(date){const day=date.getDay(),h=date.getHours()+date.getMinutes()/60;return SPECIALS.find(s=>s.days.includes(day)&&h>=s.start&&h<s.end)||null}
  function showAt(date=new Date()){const special=specialAt(date);if(special)return special;const h=date.getHours()+date.getMinutes()/60;return SHOWS.find(s=>h>=s.start&&h<s.end)||SHOWS[0]}
  function boundaryCandidates(date){const out=[];for(let add=0;add<3;add++){const base=new Date(date);base.setDate(base.getDate()+add);base.setHours(0,0,0,0);for(const h of [...new Set(SHOWS.flatMap(s=>[s.start,s.end]).filter(x=>x>=0&&x<=24))]){const d=new Date(base);if(h===24){d.setDate(d.getDate()+1);d.setHours(0,0,0,0)}else d.setHours(h,0,0,0);out.push(d)}for(const s of SPECIALS){if(!s.days.includes(base.getDay()))continue;for(const h of [s.start,s.end]){const d=new Date(base);if(h===24){d.setDate(d.getDate()+1);d.setHours(0,0,0,0)}else d.setHours(h,0,0,0);out.push(d)}}}return out.filter(d=>d>date).sort((a,b)=>a-b)}
  function nextShow(date=new Date()){const cur=showAt(date);for(const at of boundaryCandidates(date)){const probe=new Date(at.getTime()+1000),next=showAt(probe);if(next.id!==cur.id)return{show:next,at}}const d=new Date(date);d.setDate(d.getDate()+1);d.setHours(0,0,0,0);return{show:showAt(d),at:d}}
  function phase(date=new Date()){const m=date.getMinutes();if(m<=2)return'top';if(m>=13&&m<=17)return'q1';if(m>=28&&m<=32)return'half';if(m>=43&&m<=47)return'q3';if((m>=6&&m<=11)||(m>=20&&m<=26)||(m>=35&&m<=41)||(m>=50&&m<=57))return'sweep';return'open'}
  function nextMoment(date=new Date()){const candidates=[];for(const m of MOMENTS){const d=new Date(date);d.setSeconds(0,0);d.setMinutes(m.minute);if(d<=date)d.setHours(d.getHours()+1);candidates.push({type:m.type,label:m.label,at:d})}const n=nextShow(date);candidates.push({type:'show-change',label:`${n.show.name} start`,at:n.at,show:n.show});candidates.sort((a,b)=>a.at-b.at);return candidates[0]}
  function guide(date=new Date()){const current=showAt(date),n=nextShow(date);return{current,next:n.show,nextAt:n.at,shows:SHOWS.map(x=>({...x})),specials:SPECIALS.map(x=>({...x}))}}
  function formatTime(d){if(!(d instanceof Date)||!Number.isFinite(d.getTime()))return'--:--';return`${pad(d.getHours())}:${pad(d.getMinutes())}`}
  function emit(type,detail={}){try{window.dispatchEvent(new CustomEvent(type,{detail}))}catch{}}
  function tick(){const d=new Date(),cur=showAt(d),ph=phase(d),key=`${d.getFullYear()}-${d.getMonth()}-${d.getDate()}-${d.getHours()}-${ph}`;if(cur.id!==lastShow){const previous=lastShow;lastShow=cur.id;trace('show-change',{from:previous,to:cur.id,djId:cur.djId});emit('jfm:show-change',{show:cur,previous});window.jfmHourMarker=true}if(['top','q1','half','q3'].includes(ph)&&key!==lastMomentKey){lastMomentKey=key;trace('clock-moment',{phase:ph,show:cur.id});emit('jfm:clock-moment',{phase:ph,show:cur});if(ph==='top')window.jfmHourMarker=true}lastTick=Date.now();render()}
  function ensureGuide(){if($('jfmProgramGuide'))return;const radio=$('tab-radio');if(!radio)return;const cards=[...radio.querySelectorAll('.card')],program=cards.find(c=>c.querySelector('#modeLabel'))||cards[cards.length-1],card=document.createElement('article');card.className='card';card.id='jfmProgramGuide';card.innerHTML='<div class="row between"><div><div class="kicker">PROGRAMMAGIDS</div><h3 id="jfmGuideNow">MAIR</h3></div><span id="jfmGuideTime" class="accent">LIVE</span></div><div id="jfmGuideDJ" class="muted"></div><div id="jfmGuideNext" class="muted"></div><div id="jfmGuideMoment" class="muted" style="margin-top:8px"></div>';if(program?.nextSibling)radio.insertBefore(card,program.nextSibling);else radio.appendChild(card)}
  function djName(id){return window.MAIRDJProfiles?.profiles?.[id]?.name||String(id||'MAIR DJ').replace(/^./,x=>x.toUpperCase())}
  function render(){ensureGuide();const d=new Date(),cur=showAt(d),n=nextShow(d),m=nextMoment(d);if($('jfmGuideNow'))$('jfmGuideNow').textContent=cur.name;if($('jfmGuideTime'))$('jfmGuideTime').textContent=`${pad(cur.start)}:00–${pad(cur.end===24?0:cur.end)}:00`;if($('jfmGuideDJ'))$('jfmGuideDJ').textContent=`Presentatie: ${djName(cur.djId)}${cur.preferredStation?` · aanbevolen station: ${cur.preferredStation}`:''}`;if($('jfmGuideNext'))$('jfmGuideNext').textContent=`Hierna: ${n.show.name} om ${formatTime(n.at)}`;if($('jfmGuideMoment'))$('jfmGuideMoment').textContent=`Volgend radiomoment: ${m.label} · ${formatTime(m.at)}`;const mini=$('showMini');if(mini){mini.textContent=cur.name;mini.dataset.phase=phase(d);mini.title=`${cur.name} · ${phase(d)}`}document.body.dataset.show=cur.id;document.body.dataset.clockPhase=phase(d)}
  function preferredMode(date=new Date()){return showAt(date).mode}
  function current(){const d=new Date(),show=showAt(d),m=nextMoment(d);return{show,phase:phase(d),nextShow:nextShow(d),nextMoment:m,at:d}}
  window.JFMStationClock={version:'station-clock-v3-show-director',shows:SHOWS,specials:SPECIALS,current,showAt,nextShow,nextMoment,guide,phase,preferredMode,render,log:()=>[...log],get lastTick(){return lastTick}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{ensureGuide();tick()});else{ensureGuide();tick()}setInterval(tick,15000);
})();
