// MAIR Station Health — central diagnostics, music-first safe mode and non-destructive self test.
(()=>{
  const $=id=>document.getElementById(id),log=[];let safe=false,safeReasons=[],lastTest=null,lastRenderSig='',savedSafe=null;
  const brand=s=>String(s??'').replace(/Josh\s*FM/gi,'MAIR').replace(/JoshFM/gi,'MAIR');
  const now=()=>Date.now(),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const trace=(stage,detail={})=>{log.unshift({at:now(),stage,...detail});if(log.length>100)log.length=100};
  const playback=()=>{try{return window.JFMPlaybackState?.get?.()||null}catch{return null}},queueState=()=>{try{return window.JFMStationQueue?.state?.()||null}catch{return null}},fish=()=>{try{return window.JFMDJAudioGuard?.state||null}catch{return null}},clock=()=>{try{return window.JFMStationClock?.current?.()||null}catch{return null}},requests=()=>{try{return window.JFMRequests?.list?.()||[]}catch{return[]}},spotify=()=>{try{return window.JFMSpotifyGuard?.state||null}catch{return null}},discovery=()=>{try{return window.JFMDiscovery?.diagnostic?.()||null}catch{return null}},audio=()=>{try{return window.JFMDJAudio?.status||null}catch{return null}},dj=()=>{try{return window.JFMDJAuthoritative?.diagnostics?.()||window.MAIRDJ?.diagnostics?.()||null}catch{return null}},boot=()=>{try{return window.JFMRadioSuite?.boot||null}catch{return null}};
  function currentReasons(){const r=[],q=queueState(),f=fish(),p=playback(),b=boot();if(!navigator.onLine)r.push('Geen netwerk');if(f&&!f.available)r.push('Fish Audio tijdelijk in backoff');if(q?.lastError&&q.remaining!==null&&q.remaining<4)r.push('Queue-aanvulling heeft een fout');if(p?.expectedLive&&!p?.isPlaying&&Number(window.JFMPlayback?.health?.failures||0)>=2)r.push('Playback-herstel heeft meerdere fouten');if(b?.failed?.some?.(x=>['./playback-state.js','./spotify-recovery.js'].includes(x.src)))r.push('Essentiële controller kon niet laden');return r}
  function applySafeMode(reasons=currentReasons()){const next=reasons.length>0,changed=next!==safe||reasons.join('|')!==safeReasons.join('|');if(next&&!safe)savedSafe={skipNextTalk:!!window.skipNextTalk,musicRun:!!window.jfmMusicRun};if(!next&&safe&&savedSafe){try{window.skipNextTalk=savedSafe.skipNextTalk}catch{};try{window.jfmMusicRun=savedSafe.musicRun}catch{};savedSafe=null}safe=next;safeReasons=[...reasons];document.body.classList.toggle('jfm-safe-mode',safe);document.body.dataset.safeMode=safe?'1':'0';if(safe){try{window.skipNextTalk=true}catch{};try{window.jfmMusicRun=true}catch{}}if(changed){trace(safe?'safe-enter':'safe-exit',{reasons:[...safeReasons]});try{window.dispatchEvent(new CustomEvent('jfm:safe-mode',{detail:{active:safe,reasons:[...safeReasons]}}))}catch{};render()}return safe}
  function snapshot(){const p=playback(),q=queueState(),f=fish(),c=clock(),sg=spotify(),d=discovery(),a=audio(),djState=dj(),b=boot(),current=window.playback?.item||null,next=window.__jfmSpotifyUpcomingTruth?.items?.[0]||null;return{at:now(),online:navigator.onLine,safeMode:safe,safeReasons:[...safeReasons],playback:p,playbackHealth:window.JFMPlayback?.health||null,currentTrack:current?{id:current.id||'',uri:current.uri||'',name:current.name||'',artists:(current.artists||[]).map(x=>x?.name||x)}:null,nextTrack:next?{id:next.id||'',uri:next.uri||'',name:next.name||'',artists:(next.artists||[]).map(x=>x?.name||x)}:null,queue:q,fish:f,spotifyGuard:sg,discovery:d,audio:a,dj:djState,boot:b,show:c?.show?{...c.show,name:brand(c.show.name)}:null,clockPhase:c?.phase||'',requests:requests().length,serviceWorker:{supported:'serviceWorker'in navigator,controlled:!!navigator.serviceWorker?.controller},mediaSession:'mediaSession'in navigator}}
  function testRow(x){const icon=x.level==='PASS'?'✓':x.level==='WARN'?'⚠':'✕';return `<div class="jfm-health-row" data-level="${x.level}"><span>${esc(brand(x.label))}</span><span><b>${icon} ${x.level}</b>${x.detail?`<small>${esc(brand(x.detail))}</small>`:''}</span></div>`}
  async function runSelfTest(){
    const out=$('selfTestResults'),btn=$('selfTest');if(btn){btn.disabled=true;btn.textContent='Test bezig…'}if(out)out.innerHTML='<p class="muted">Niet-destructieve controle bezig…</p>';const results=[],add=(level,label,detail='')=>results.push({level,label:brand(label),detail:brand(detail)});
    add(navigator.onLine?'PASS':'FAIL','Internet',navigator.onLine?'Browser is online':'Spotify en Fish hebben internet nodig');
    try{const t=await ensure();add(t?'PASS':'FAIL','Spotify-auth',t?'Token beschikbaar':'Opnieuw koppelen nodig')}catch(e){add('FAIL','Spotify-auth',String(e?.message||e))}
    try{const d=await api('/me/player/devices'),usable=(d?.devices||[]).filter(x=>!x.is_restricted);add(usable.length?'PASS':'WARN','Spotify-device',usable.length?`${usable.length} bruikbaar apparaat${usable.length===1?'':'en'}`:'Open Spotify kort om een device actief te maken')}catch(e){add('WARN','Spotify-device',String(e?.message||e))}
    try{const s=await api('/me/player');add(s?.device?.id?'PASS':'WARN','Spotify playback',s?.item?`${s.is_playing?'Speelt':'Gepauzeerd'} · ${s.item.name}`:'Geen actieve track')}catch(e){add('WARN','Spotify playback',String(e?.message||e))}
    const sg=spotify();if(window.JFMSpotifyGuard){const left=Math.max(0,Number(sg?.cooldownUntil||0)-Date.now());add(left?'WARN':'PASS','Spotify request guard',left?`Discovery cooldown ${Math.ceil(left/1000)} sec`:`${sg?.searchCache||0} zoekresultaten gecachet`)}else add('WARN','Spotify request guard','Nog niet geladen');
    const d=discovery();if(window.JFMDiscovery){add(d?.rateLimited?'WARN':'PASS','Discovery',d?`${d.found||0} gevonden · ${d.searches||0}/${window.JFMDiscovery.maxSearches||12} searches · ${d.errors||0} fouten`:'Nog geen radioset-discovery uitgevoerd')}else add('WARN','Discovery','Niet geladen');
    add(window.JFMPlaybackState?'PASS':'FAIL','Playback truth',window.JFMPlaybackState?.version||'Niet geladen');add(window.MAIRTransitionController?'PASS':'FAIL','Transition controller',window.MAIRTransitionController?.version||'Niet geladen');const ph=window.JFMPlayback?.health;add(window.JFMPlayback?(ph?.lastError?'WARN':'PASS'):'FAIL','Playback controller',ph?.lastError?`Laatste fout: ${ph.lastError}`:(window.JFMPlayback?.version||'Niet geladen'));
    const q=queueState();add(window.JFMStationQueue?(q?.lastError?'WARN':'PASS'):'FAIL','Station queue',q?`${q.remaining??'—'} tracks resterend · generatie ${q.generation??0}${q.lastError?' · '+q.lastError:''}`:'Niet geladen');add(window.JFMProgramDirector?'PASS':'FAIL','Program Director',window.JFMProgramDirector?.version||'Niet geladen');add(window.JFMRotation?'PASS':'FAIL','Rotation engine',window.JFMRotation?.version||'Niet geladen');add(window.JFMStationClock?'PASS':'FAIL','Station clock',brand(clock()?.show?.name||'Niet geladen'));add(window.JFMRequests?'PASS':'WARN','Request manager',window.JFMRequests?.version||'Niet geladen');add(window.JFMDJContext?'PASS':'WARN','DJ-context',window.JFMDJContext?.version||'Niet geladen');
    const f=fish(),a=audio(),dj=window.JFMDJAuthoritative||window.MAIRDJ,djState=dj?.diagnostics?.()||dj?.state?.()||null;add(window.JFMDJAudioGuard?(f?.available?'PASS':'WARN'):'FAIL','Fish Audio guard',f?(f.available?'Beschikbaar':`Backoff · ${Math.ceil((f.retryInMs||0)/1000)} sec`):'Niet geladen');add(window.JFMDJAudio?(a?.error?'WARN':a?.lastPlaybackAt?'PASS':'WARN'):'FAIL','DJ audio playback',a?`${a.audioUnlocked?'unlocked':'locked'} · route ${a.playbackMode||'nog niet gebruikt'}${a.lastPlaybackAt?' · playback bewezen':' · nog niet hoorbaar bewezen'}`:'Niet geladen');add(dj?(djState?.played>0?'PASS':'WARN'):'FAIL','DJ handoff',dj?`${dj.version}${djState?.played?` · ${djState.played} break(s) bewezen`:' · nog niet on-air bewezen'}`:'Niet geladen');
    const b=boot();if(b){add(b.failed?.length?'WARN':'PASS','Controller boot',b.failed?.length?`${b.failed.length} optionele module(s) niet geladen`:`${b.loaded?.length||0} modules geladen`)}else add('WARN','Controller boot','Bootresultaat nog niet beschikbaar');
    try{const r=await fetch('/api/config',{cache:'no-store'});add(r.ok?'PASS':'WARN','Backend/config',r.ok?'Endpoint bereikbaar':`HTTP ${r.status}`)}catch{add('WARN','Backend/config','Niet bereikbaar')}try{const r=await fetch('/api/tts',{method:'GET',cache:'no-store'});add(r.ok?'PASS':'WARN','Fish/TTS route',r.ok?'Stemconfiguratie bevestigd':`HTTP ${r.status} · niet operationeel bewezen`)}catch{add('WARN','Fish/TTS route','Niet bereikbaar')}
    add('serviceWorker'in navigator?(navigator.serviceWorker.controller?'PASS':'WARN'):'WARN','PWA/service worker','serviceWorker'in navigator?(navigator.serviceWorker.controller?'Actief':'Ondersteund, nog niet controlerend'):'Niet ondersteund');add('mediaSession'in navigator?'PASS':'WARN','Media Session','mediaSession'in navigator?'Ondersteund':'Niet ondersteund');add(window.JFMPWA?'PASS':'WARN','PWA platform',window.JFMPWA?.version||'Niet geladen');add(window.JFMRuntimeModes?'PASS':'WARN','Runtime modes',window.JFMRuntimeModes?.version||'Niet geladen');add(window.JFMTop40?'PASS':'WARN','Personal Top 40',window.JFMTop40?.version||'Niet geladen');const contract=window.JFMIntegrationGuards?.sanity?.();add(contract?.missing?.length?'WARN':'PASS','Controller-contracten',contract?.missing?.length?`Ontbreekt: ${contract.missing.join(', ')}`:'Alle kerncontrollers aanwezig');const reasons=currentReasons();add(reasons.length?'WARN':'PASS','Safe Mode',reasons.length?reasons.join(' · '):'Geen degradatie actief');
    const rank={FAIL:0,WARN:1,PASS:2};results.sort((a,b)=>rank[a.level]-rank[b.level]);lastTest={at:now(),results};trace('self-test',{pass:results.filter(x=>x.level==='PASS').length,warn:results.filter(x=>x.level==='WARN').length,fail:results.filter(x=>x.level==='FAIL').length});if(out)out.innerHTML=results.map(testRow).join('');if(btn){btn.disabled=false;btn.textContent='Test MAIR opnieuw'}render();return lastTest
  }
  function installSelfTestOwner(){const old=$('selfTest');if(!old)return false;const b=old.cloneNode(true);old.replaceWith(b);b.textContent=brand(b.textContent).replace(/Test\s+MAIR(?:\s+opnieuw)?/i,'Test MAIR opnieuw');b.addEventListener('click',()=>runSelfTest().catch(e=>{trace('self-test-error',{error:String(e?.message||e)});b.disabled=false;b.textContent='Test MAIR opnieuw'}));window.JFMSelfTest={version:'selftest-v5-mair',run:runSelfTest};return true}
  function ensureSummary(){let box=$('jfmHealthSummary');if(box)return box;const out=$('selfTestResults');if(!out)return null;box=document.createElement('div');box.id='jfmHealthSummary';box.className='jfm-health-summary';out.insertAdjacentElement('beforebegin',box);return box}
  function render(){const box=ensureSummary();if(!box)return;const s=snapshot(),sig=JSON.stringify({safe:s.safeMode,reasons:s.safeReasons,playing:s.playback?.isPlaying,queue:s.queue?.remaining,fish:s.fish?.available,show:s.show?.id,online:s.online,cooldown:s.spotifyGuard?.cooldownUntil||0});if(sig===lastRenderSig)return;lastRenderSig=sig;const queueText=s.queue?`${s.queue.remaining??'—'} vooruit`:'—',fishText=s.fish?(s.fish.available?'OK':'BACKOFF'):'—',playText=s.playback?(s.playback.isPlaying?'SPEELT':s.playback.expectedLive?'HERSTEL':'PAUZE'):'—';box.innerHTML=`<div class="jfm-health-head"><b>${safe?'SAFE MODE':'STATION OK'}</b><span>${safe?esc(brand(safeReasons.join(' · '))):'Muziek, queue en DJ worden bewaakt.'}</span></div><div class="jfm-health-grid"><span>Playback <b>${esc(playText)}</b></span><span>Queue <b>${esc(queueText)}</b></span><span>Fish <b>${esc(fishText)}</b></span><span>Show <b>${esc(brand(s.show?.name||'—'))}</b></span></div>`}
  function poll(){applySafeMode();render()}['online','offline','jfm:dj-audio-health','jfm:trackchange','jfm:playback-state','jfm:show-change','jfm:requests-change'].forEach(e=>window.addEventListener(e,poll));function install(){let tries=0;const own=()=>{if(installSelfTestOwner()){poll();return}if(++tries<24)setTimeout(own,250)};own();setInterval(poll,8000)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
  window.JFMStationHealth={version:'health-v4-mair',snapshot,runSelfTest,applySafeMode,get safeMode(){return safe},get reasons(){return[...safeReasons]},get lastTest(){return lastTest},log:()=>[...log]};
})();
