// Josh FM station queue continuity — keeps the authored radioset ahead of Spotify playback.
(()=>{
  const wait=ms=>new Promise(r=>setTimeout(r,ms));
  const BATCH_SIZE=10,INITIAL_LOADED=30,LOW_WATER=8,ROTATION_TRIGGER=12,ROTATION_ADD=30,ROLL_KEEP_BEHIND=8,ROLL_AT_INDEX=24,TRACK_URI=/^spotify:track:[A-Za-z0-9]{22}$/,MAX_APPEND_FAILURES=2,FATAL_APPEND=/rustiger|429|niet gekoppeld|sessie is verlopen|geen actief|device/i;
  let busy=false,building=false,lastTrackId='',lastRun=0,appended=new Set(),lastError='',generation=0,loadedThrough=INITIAL_LOADED;
  const log=[];
  function trace(stage,extra={}){const item={at:Date.now(),stage,...extra};log.unshift(item);if(log.length>100)log.length=100;window.JFMStationQueueLog=log}
  function status(text,bad=false){const e=document.getElementById('queueInfo');if(!e)return;e.textContent=text;e.style.color=bad?'#ffb4b4':''}
  function stationQueue(){try{return window.JFMQueue?.current?.()||(Array.isArray(queue)?queue.filter(t=>t?.id&&TRACK_URI.test(t?.uri||'')):[])}catch{return[]}}
  function currentId(){try{return window.JFMPlaybackState?.get?.()?.trackId||playback?.item?.id||''}catch{return''}}
  function stationId(){return localStorage.getItem('jfm_music_channel_v1')||'mix'}
  function repeatWindow(id=stationId()){if(id==='hits')return 45;if(id==='top40')return 35;if(id==='sleep')return 35;return 24}
  function artistWindow(id=stationId()){if(id==='hits'||id==='top40')return 12;if(id==='sleep')return 10;return 8}
  function currentIndex(q,id){return id?q.findIndex(t=>t.id===id):-1}
  function managed(q,id){return q.length>0&&currentIndex(q,id)>=0}
  // Include enough of the authored order to avoid restoring stale loadedThrough/appended state
  // when a rebuilt set happens to share the same first few tracks.
  function signature(q){return q.length?`${q.length}|${q.slice(0,12).map(t=>t.id).join('.')}`:''}
  function restore(q){const sig=signature(q);if(!sig)return;try{const x=JSON.parse(sessionStorage.getItem('jfm_station_queue_v4')||'{}');if(x.signature===sig){generation=Number(x.generation||0);loadedThrough=Math.min(INITIAL_LOADED,q.length)}}catch{}}
  function persist(q){try{sessionStorage.setItem('jfm_station_queue_v4',JSON.stringify({signature:signature(q),appended:[...appended],generation,loadedThrough,at:Date.now()}))}catch{}}
  async function remoteQueueUris(){try{const d=await api('/me/player/queue');lastError='';return new Set((d?.queue||[]).map(x=>x?.uri).filter(x=>TRACK_URI.test(x||'')))}catch(e){lastError=String(e?.message||e);trace('remote-queue-unavailable',{message:lastError});return null}}
  function desiredWindow(q,index){if(index<0)return[];loadedThrough=Math.max(Math.min(q.length,loadedThrough),Math.min(INITIAL_LOADED,q.length));if(loadedThrough-index>LOW_WATER)return[];return q.slice(loadedThrough,Math.min(q.length,loadedThrough+BATCH_SIZE))}
  async function appendTracks(q,tracks){if(!tracks.length)return 0;const remote=await remoteQueueUris();if(!remote)throw Error(lastError||'Spotify-wachtrij niet beschikbaar.');let added=0,failed=0;for(const track of tracks){if(!TRACK_URI.test(track?.uri||'')){trace('invalid-uri-skip',{id:track?.id||'',uri:track?.uri||''});continue}const pos=q.findIndex(t=>t.id===track.id);if(remote.has(track.uri)){appended.add(track.id);if(pos>=0)loadedThrough=Math.max(loadedThrough,pos+1);continue}try{const device=localStorage.getItem('jfm_spotify_device_id')||'';const path='/me/player/queue?uri='+encodeURIComponent(track.uri)+(device?'&device_id='+encodeURIComponent(device):'');await api(path,{method:'POST'});appended.add(track.id);remote.add(track.uri);if(pos>=0)loadedThrough=Math.max(loadedThrough,pos+1);added++;trace('track-appended',{id:track.id,name:track.name,loadedThrough});await wait(120)}catch(e){const message=String(e?.message||e);lastError=message;/* Een enkele geweigerde track mag de hele bijvulronde niet stoppen. Rate limit, ontbrekend device en een verloren sessie zijn wel fataal: doorgaan zou die fout alleen vermenigvuldigen. */const fatal=FATAL_APPEND.test(message)||++failed>MAX_APPEND_FAILURES;trace('append-error',{id:track.id,message,fatal,failed});if(fatal)break;await wait(160)}}if(added)lastError='';persist(q);return added}
  function recentHistoryIds(limit=repeatWindow()){const ids=new Set();try{const s=window.JFMRadioSuite?.state?.();for(const id of(s?.lastIds||[]).slice(0,limit))ids.add(id)}catch{}return ids}
  function recentlyUsedArtists(q,limit=artistWindow()){const names=[];for(const t of q.slice(-limit)){const a=String(t?.artists?.[0]||'').toLowerCase().trim();if(a)names.push(a)}try{const s=window.JFMRadioSuite?.state?.();for(const a of(s?.lastArtists||[]).slice(0,limit)){const x=String(a||'').toLowerCase().trim();if(x)names.push(x)}}catch{}return new Set(names)}
  function rollWindow(q,index){if(index<ROLL_AT_INDEX)return{q,index};const cut=Math.max(0,index-ROLL_KEEP_BEHIND),next=q.slice(cut),keep=new Set(next.map(t=>t.id));queue=window.JFMQueue?.commit?.(next,{source:'continuity',station:stationId(),reason:'window-roll'})||next;loadedThrough=Math.max(1,loadedThrough-cut);appended=new Set([...appended].filter(id=>keep.has(id)));window.__jfmStationQueueSig=signature(next);persist(next);trace('window-rolled',{cut,kept:next.length,loadedThrough});return{q:next,index:index-cut}}
  async function prepareNextRotation(reason='low-buffer'){
    if(building||busy||!window.JFMQueue?.buildActive)return false;let active=stationQueue(),id=currentId(),index=currentIndex(active,id);if(!managed(active,id))return false;const remaining=active.length-index-1;if(remaining>ROTATION_TRIGGER)return false;({q:active,index}=rollWindow(active,index));building=true;const previousInfo=document.getElementById('queueInfo')?.textContent||'',activeStation=stationId(),repeatLock=repeatWindow(activeStation);trace('rotation-build-start',{reason,index,remaining:active.length-index-1,tracks:active.length,station:activeStation,repeatLock});
    try{const old=[...active],recentIds=recentHistoryIds(repeatLock),recentArtists=recentlyUsedArtists(old,artistWindow(activeStation)),oldIds=new Set(old.map(t=>t.id)),generated=await window.JFMQueue.buildActive('continuity-'+reason);let candidates=generated.filter(t=>t?.id&&TRACK_URI.test(t?.uri||'')&&!oldIds.has(t.id)&&!recentIds.has(t.id));
      // For HITS/TOP40, never bypass the recent-track lock just to fill a batch. A smaller fresh batch is preferable to an early repeat.
      if(candidates.length<10&&!['hits','top40'].includes(activeStation)){const relaxedRecent=recentHistoryIds(Math.min(20,repeatLock));const relaxed=generated.filter(t=>t?.id&&TRACK_URI.test(t?.uri||'')&&!oldIds.has(t.id)&&!relaxedRecent.has(t.id)&&!candidates.some(x=>x.id===t.id));candidates=[...candidates,...relaxed]}
      candidates.sort((a,b)=>{const aa=String(a?.artists?.[0]||'').toLowerCase().trim(),ba=String(b?.artists?.[0]||'').toLowerCase().trim();return Number(recentArtists.has(aa))-Number(recentArtists.has(ba))});const context=old.slice(-6),director=window.JFMProgramDirector;if(director?.directWithContext)candidates=director.directWithContext(candidates,context);const next=candidates.slice(0,ROTATION_ADD);if(next.length){queue=window.JFMQueue.commit([...old,...next],{context:old.slice(-2),source:'continuity',station:activeStation,reason:'rotation-ready'});generation++;persist(queue);window.__jfmStationQueueSig=signature(queue);lastError='';trace('rotation-build-ready',{reason,added:next.length,generation,total:queue.length,station:activeStation,repeatLock});try{window.jfmRenderNext?.()}catch{};status(`MAIR programmeert vooruit · ${next.length} nieuwe tracks klaar.`);setTimeout(()=>maintain('rotation-ready').catch(()=>{}),120);return true}trace('rotation-build-empty',{reason,generated:generated.length,station:activeStation,repeatLock});if(previousInfo)status(previousInfo);return false}catch(e){lastError=String(e?.message||e);trace('rotation-build-error',{reason,message:lastError});queue=active;window.__jfmStationQueueSig=signature(active);if(previousInfo)status(previousInfo,true);return false}finally{building=false}}
  async function maintain(reason='poll'){if(busy||building||Date.now()-lastRun<1200)return false;const q=stationQueue(),id=currentId();if(!managed(q,id))return false;const index=currentIndex(q,id),wanted=desiredWindow(q,index);if(!wanted.length){prepareNextRotation(reason).catch(()=>{});return false}busy=true;lastRun=Date.now();trace('maintain-start',{reason,index,wanted:wanted.length,loadedThrough});try{const added=await appendTracks(q,wanted);if(added){status(`MAIR bewaakt de wachtrij · ${added} volgende track${added===1?'':'s'} toegevoegd.`);trace('maintain-end',{reason,index,added,loadedThrough})}return added>0}finally{busy=false;prepareNextRotation(reason).catch(()=>{})}}
  function resetForNewSet(){const q=stationQueue();appended=new Set();generation=0;loadedThrough=Math.min(INITIAL_LOADED,q.length);restore(q);trace('set-detected',{tracks:q.length,signature:signature(q),loadedThrough})}
  function resetAfterReload(uri=''){const q=stationQueue(),index=q.findIndex(t=>t?.uri===uri);if(index<0)return false;appended=new Set();loadedThrough=Math.min(q.length,index+1);persist(q);trace('reload-context-reset',{uri,index,loadedThrough});setTimeout(()=>maintain('reload-context').catch(()=>{}),120);return true}
  window.addEventListener('jfm:trackchange',e=>{const id=e?.detail?.trackId||currentId();if(id&&id!==lastTrackId){lastTrackId=id;maintain('trackchange').catch(()=>{});prepareNextRotation('trackchange').catch(()=>{})}});window.addEventListener('jfm:queue-change',()=>{resetForNewSet();window.__jfmStationQueueSig=signature(stationQueue())});
  window.addEventListener('jfm:reload-context-restored',e=>resetAfterReload(e.detail?.uri||''));
  setInterval(()=>maintain('watchdog').catch(()=>{}),6000);setInterval(()=>prepareNextRotation('rotation-watchdog').catch(()=>{}),12000);setInterval(()=>{if(building)return;const q=stationQueue(),sig=signature(q);if(sig&&sig!==window.__jfmStationQueueSig){window.__jfmStationQueueSig=sig;resetForNewSet()}},3000);
  setTimeout(()=>{resetForNewSet();window.__jfmStationQueueSig=signature(stationQueue());if(!resetAfterReload(window.__jfmReloadContextUri||'')){maintain('startup').catch(()=>{});prepareNextRotation('startup').catch(()=>{})}},1600);
  window.JFMStationQueue={version:'continuity-v6.3-mode-aware-rotation',maintain,prepareNextRotation,resetAfterReload,repeatWindow,artistWindow,log:()=>[...log],state:()=>{const q=stationQueue(),id=currentId(),index=currentIndex(q,id);return{managed:managed(q,id),trackId:id,index,tracks:q.length,remaining:index>=0?q.length-index-1:null,loadedThrough,appended:[...appended],generation,busy,building,lastError,signature:signature(q),repeatWindow:repeatWindow(),artistWindow:artistWindow(),core:window.JFMQueue?.state?.()||null}}};
})();