const CACHE='mair-v76-request-transition-dedupe-20260824';
const CORE=['./','./index.html','./styles.css','./pwa-platform.css','./version.js','./brand-config.js','./brand-runtime-v9.js','./channel-start-guard-v2b01.js','./dj-handoff-bootstrap-v2b02.js','./ios-transport-v2b02.js','./queue-status-v2b02.js','./app.js','./spotify-test-config.js','./stability-core.js','./playback-primary.js','./spotify-api-budget.js','./dj-resume.js','./discovery.js','./debug-tts.js','./dj-audio-guard.js','./dj-context.js','./dj-quality-v2.js','./dj-context-v2.js','./request-manager.js','./station-clock.js','./station-clock-bridge.js','./rotation-engine.js','./director.js','./smart-dj.js','./radio-suite.js','./radio-upgrades.js','./playback-state.js','./spotify-recovery.js','./station-queue.js','./runtime-modes.js','./personal-top40.js','./live-ui.js','./pwa-platform.js','./integration-guards.js','./station-health.js','./radio-core-health-v1.js','./dj-now-queue.js','./mair-dj-v2.js','./mair-dj-schedule-sync.js','./mair-audio-unlock-v1.js','./mair-voice-check.js','./mair-diagnostics-hub.js','./mair-background-guard.js','./progress-clock-v226.js','./music-choice.js','./mair-station-policy.js','./channel-click-fix.js','./music-intelligence-v3.js','./personal-learning-v4.js','./product-model-v6.js','./product-ux-v5.js','./beta-status.js','./release-diagnostics.js','./mair-foundation.js','./mair-foundation.css','./mair-station-art.css','./mair-category-search.js','./mair-category-search.css','./mair-template-assets.css','./assets/stations/mair-hits.webp','./assets/stations/mair-top40.webp','./assets/stations/mair-discovery.webp','./assets/stations/mair-nederlandstalig.webp','./assets/stations/mair-party.webp','./assets/stations/mair-chill.webp','./assets/stations/mair-summer.webp','./assets/stations/mair-throwback.webp','./assets/stations/mair-00s.webp','./assets/stations/mair-10s.webp','./assets/mair-mix.svg','./assets/dj-josh.webp','./assets/dj-maya.webp','./assets/dj-max.webp','./assets/dj-noah.webp','./mair-radio-home.js','./mair-radio-home.css','./mair-tts-profile-bridge.js','./mair-live-context.js','./mair-location.js','./mair-voice-engine.js','./mair-dj-persona.js','./mair-ui-hardening.js','./mair-user-controls.js','./mair-dj-visuals.js','./mair-runtime-core.js','./mair-pwa-polish.js','./mair-easy-use-v1.js','./build7.js','./manifest.webmanifest','./mair-logo.svg'];
CORE.push('./queue-core.js','./spotify-upcoming-truth.js','./request-layer-fix.css');
async function cacheCore(){const cache=await caches.open(CACHE),jobs=CORE.map(async path=>{try{const r=await fetch(path,{cache:'reload'});if(r.ok)await cache.put(path,r.clone())}catch{}});await Promise.allSettled(jobs)}
self.addEventListener('install',event=>{event.waitUntil(cacheCore());self.skipWaiting()});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>(k.startsWith('josh-fm-')||k.startsWith('mair-'))&&k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim()})())});
function bypass(request,url){return request.method!=='GET'||url.pathname.startsWith('/api/')||url.hostname.includes('spotify')||url.hostname.includes('wikipedia')||url.hostname.includes('musicbrainz')||url.hostname.includes('open-meteo')||url.hostname.includes('bigdatacloud')||url.hostname.includes('fish.audio')||url.hostname.includes('groq.com')}
async function fetchTimed(request,ms=9000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),ms);try{return await fetch(request,{cache:'no-store',signal:c.signal})}finally{clearTimeout(timer)}}
async function networkFirst(request){const cache=await caches.open(CACHE);try{const response=await fetchTimed(request,request.mode==='navigate'?7000:10000);if(response?.ok)await cache.put(request,response.clone());return response}catch{const cached=await cache.match(request,{ignoreSearch:true});if(cached)return cached;if(request.mode==='navigate')return cache.match('./index.html')||cache.match('./');throw new Error('offline')}}
self.addEventListener('fetch',event=>{const url=new URL(event.request.url);if(bypass(event.request,url))return;event.respondWith(networkFirst(event.request))});
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting();if(event.data?.type==='CACHE_VERSION')event.source?.postMessage?.({type:'CACHE_VERSION',cache:CACHE,core:CORE.length})});
