const CACHE='mair-rc-v1';
const CORE=['./','./index.html','./styles.css','./mair-foundation.css','./mair-radio-home.css','./version.js','./brand-config.js','./brand-runtime-v9.js','./app.js','./spotify-test-config.js','./stability-core.js','./playback-primary.js','./dj-resume.js','./discovery.js','./debug-tts.js','./director.js','./smart-dj.js','./dj-quality-v2.js','./dj-context-v2.js','./radio-suite.js','./radio-upgrades.js','./dj-now-queue.js','./music-choice.js','./channel-click-fix.js','./music-intelligence-v3.js','./release-diagnostics.js','./mair-location.js','./mair-live-context.js','./mair-voice-engine.js','./mair-tts-profile-bridge.js','./mair-dj-persona.js','./mair-foundation.js','./mair-radio-home.js','./build7.js','./mair-pwa-polish.js','./manifest.webmanifest','./mair-logo.svg','./assets/mair-visual-sprite.svg'];
async function cacheCore(){const cache=await caches.open(CACHE),jobs=CORE.map(async path=>{try{const r=await fetch(path,{cache:'reload'});if(r.ok)await cache.put(path,r.clone())}catch{}});await Promise.allSettled(jobs)}
self.addEventListener('install',event=>{event.waitUntil(cacheCore());self.skipWaiting()});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim()})())});
function bypass(request,url){return request.method!=='GET'||url.pathname.startsWith('/api/')||url.hostname.includes('spotify')||url.hostname.includes('wikipedia')||url.hostname.includes('musicbrainz')||url.hostname.includes('open-meteo')||url.hostname.includes('bigdatacloud')||url.hostname.includes('fish.audio')}
async function fetchTimed(request,ms=9000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),ms);try{return await fetch(request,{cache:'no-store',signal:c.signal})}finally{clearTimeout(timer)}}
async function networkFirst(request){const cache=await caches.open(CACHE);try{const response=await fetchTimed(request,request.mode==='navigate'?7000:10000);if(response?.ok)await cache.put(request,response.clone());return response}catch{const cached=await cache.match(request,{ignoreSearch:true});if(cached)return cached;if(request.mode==='navigate')return cache.match('./index.html')||cache.match('./');throw new Error('offline')}}
self.addEventListener('fetch',event=>{const url=new URL(event.request.url);if(bypass(event.request,url))return;event.respondWith(networkFirst(event.request))});
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting();if(event.data?.type==='CACHE_VERSION')event.source?.postMessage?.({type:'CACHE_VERSION',cache:CACHE,core:CORE.length})});