import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
const root=process.cwd(),fail=[],pass=[];const read=p=>fs.readFileSync(path.join(root,p),'utf8'),exists=p=>fs.existsSync(path.join(root,p));const ok=(n,c,d='')=>(c?pass:fail).push(`${n}${d?` — ${d}`:''}`);
function walk(dir='.') {const out=[];for(const e of fs.readdirSync(path.join(root,dir),{withFileTypes:true})){if(['.git','node_modules','.vercel','backups'].includes(e.name))continue;const rel=path.join(dir,e.name).replace(/^\.\//,'').split(path.sep).join('/');if(e.isDirectory())out.push(...walk(rel));else out.push(rel)}return out}
const files=walk(),js=files.filter(f=>f.endsWith('.js')||f.endsWith('.mjs'));for(const f of js){try{execFileSync(process.execPath,['--check',path.join(root,f)],{stdio:'pipe'});pass.push(`syntax ${f}`)}catch(e){fail.push(`syntax ${f} — ${String(e.stderr||e.message).trim()}`)}}
const runtimeJs=js.filter(f=>!f.startsWith('scripts/')&&!f.startsWith('tests/')&&!f.startsWith('.github/')),allJs=runtimeJs.map(f=>[f,read(f)]),players=allJs.filter(([,s])=>s.includes('new Spotify.Player'));
ok('backup policy exists',exists('backups/README.md')&&read('PRE_DEPLOY.md').includes('backup'));ok('at least one production backup exists',exists('backups')&&fs.readdirSync(path.join(root,'backups')).some(x=>x!=='README.md'));
ok('single Spotify.Player',players.length===1&&players[0]?.[0]==='stability-core.js',players.map(([f])=>f).join(', ')||'none');ok('legacy controllers removed',!exists('spotify-core.js')&&!exists('playback-web-sdk.js')&&!exists('stable-playback.js'));
const sdk=read('stability-core.js'),primary=read('playback-primary.js'),dj=read('dj-handoff-v34.js'),pwa=read('pwa-platform.js'),director=read('director.js'),cfg=read('spotify-test-config.js'),suite=read('radio-suite.js'),sw=read('sw.js'),index=read('index.html'),versionJs=read('version.js'),versionApi=read('api/version.js'),choice=read('music-choice.js'),diag=read('release-diagnostics.js'),pkg=JSON.parse(read('package.json'));
ok('SDK disables own MediaSession',sdk.includes('enableMediaSession:false')&&sdk.includes('sdk-core-v5-device-refresh'));ok('SDK emits natural end signal',sdk.includes('jfm:natural-track-end')&&sdk.includes('nearEnd'));ok('SDK no transport/DJ ownership',!sdk.includes('window.djBreak=')&&!/(?:ownButton|own|replace)\(['"](?:start|play|next|prev)['"]/.test(sdk));
ok('SDK refreshes stale devices',sdk.includes("api('/me/player/devices')")&&sdk.includes('async function reconnect()')&&sdk.includes('async function ensureDevice()'));ok('primary prefers live SDK device',primary.includes('sdkDeviceId')&&primary.includes('JFMSpotifySDK?.ensureDevice')&&primary.includes('primary-v5-device-heal'));
ok('primary owns transport',primary.includes("JFMPlaybackPrimary='playback-primary'")&&primary.includes("dataset.jfmOwner='primary'"));ok('iOS gesture capture',primary.includes('activateElement')&&primary.includes("document.addEventListener('click'"));ok('natural end guard exists',primary.includes('handleNaturalEnd')&&primary.includes('jfm:natural-track-end')&&primary.includes('primary-natural-end'));ok('natural end does not count skip',primary.includes("advance({record:false,source:'primary-natural-end'})"));ok('skip fallback retained',primary.includes('stationNeighbor')&&primary.includes('playContextDirect'));
ok('DJ flow mute first',dj.includes('await setVolume(0)'));ok('DJ requires confirmed mute before speech',dj.includes('confirmedMute')&&dj.includes("if(!(await confirmedMute()))")&&dj.indexOf('confirmedMute'));
ok('DJ iOS uses Spotify volume API',dj.includes("/me/player/volume?volume_percent=")&&dj.includes('isiOS()'));ok('DJ flow stays playing',!dj.includes('/me/player/pause')&&!dj.includes('player()?.pause'));ok('DJ rewinds same new track',dj.includes('rewindExpected(expectedUri)')&&dj.includes('seek(0)'));ok('DJ unmutes after rewind',dj.includes('await setVolume(1)'));ok('DJ validates track/device',dj.includes('TRACK_URI')&&dj.includes('DEVICE')&&dj.includes('validDevice'));ok('DJ v36.2 owner',dj.includes("dataset.jfmHandoffOwner='v36'")&&dj.includes('handoff-v36.2-mute-rewind-skip-safe'));
ok('DJ now survives manual skip',dj.includes('consumeArmedIfChanged')&&dj.includes('armed={fromId:id,requestedAt:Date.now()}')&&dj.includes('runBreak(null,true)')&&dj.includes("window.addEventListener('jfm:trackchange'"));
ok('PWA sole MediaSession owner',pwa.includes('pwa-v4-single-mediasession-owner')&&pwa.includes('safePositionState'));ok('MediaSession bounds position',pwa.includes('position>=duration')&&pwa.includes('durationMs-1'));ok('track change resets media position',pwa.includes('updateMediaSession({reset:true})'));ok('iOS metadata reassertion',pwa.includes('reassertMediaSession')&&pwa.includes('new MediaMetadata')&&pwa.includes('[0,120,400,1000,2200]'));ok('no other runtime MediaSession writers',allJs.filter(([f,s])=>f!=='pwa-platform.js'&&(s.includes('setPositionState')||s.includes('new MediaMetadata'))).length===0,allJs.filter(([f,s])=>f!=='pwa-platform.js'&&(s.includes('setPositionState')||s.includes('new MediaMetadata'))).map(([f])=>f).join(', '));
ok('Spotify queue owns upcoming UI',director.includes('if(window.JFMSpotifyUpcomingTruth)')&&director.includes('director-v10-horizon-owner')&&read('spotify-upcoming-truth.js').includes('v2-single-authoritative-owner'));ok('legacy radio mode hidden',director.includes('hideLegacyRadioMode')&&director.includes("textContent.trim()==='Radiomodus'")&&director.includes("modeMini"));
ok('central asset version exists',versionJs.includes("JFM_ASSET_VERSION='39'")&&cfg.includes("window.JFM_ASSET_VERSION||'39'")&&suite.includes("window.JFM_ASSET_VERSION||'39'"));ok('critical loaders use central asset',cfg.includes("loadScriptOnce('script[data-jfm-playback-primary]','./playback-primary.js'")&&!cfg.includes('playback-primary.js?v=36'));ok('PWA cache v39',sw.includes("josh-fm-v39-v22-hardening")&&sw.includes("'./version.js'")&&sw.includes("'./music-choice.js'")&&sw.includes("'./release-diagnostics.js'"));ok('release version matches package',versionJs.includes(`version:'${pkg.version}'`)&&versionApi.includes(`version:'${pkg.version}'`));ok('release endpoint uses deployed commit',versionApi.includes('VERCEL_GIT_COMMIT_SHA')&&versionJs.includes("fetch('/api/version'"));ok('release endpoint exposes v39 cache',versionApi.includes("cache:'josh-fm-v39-v22-hardening'")&&versionJs.includes('updateAvailable'));
ok('release features wired at runtime',index.includes('<script src="music-choice.js"></script>')&&index.includes('<script src="release-diagnostics.js"></script>'));ok('music channels exist',choice.includes("top40:{label:'Top 40'")&&choice.includes("nl:{label:'Nederlandstalig'")&&choice.includes("summer:{label:'Summer'"));ok('channels use distinct Spotify queries',choice.includes('channelQuery')&&choice.includes("nl:'genre:dutch'")&&choice.includes("party:'genre:dance'")&&choice.includes("chill:'genre:chill'")&&choice.includes("throwback:'year:1980-2016'"));ok('channel failure does not silently reuse same list',choice.includes('kon niet betrouwbaar worden geladen')&&choice.includes('previousQueue')&&choice.includes('queue=previousQueue'));ok('channel switch loads selected queue into playback',choice.includes('rebuildAndMaybeSwitch')&&choice.includes('JFMPlayback.playUri')&&primary.includes('stationContext(uri)'));ok('Hit Battle persists learning',choice.includes('jfm_hit_battle_v1')&&choice.includes('battleScore')&&choice.includes('vote(winner,loser)'));ok('Hit Battle prevents fast repeats',choice.includes('recentPairs')&&choice.includes('recentTracks')&&choice.includes('pairKey'));ok('Hit Battle exposes top/history',choice.includes('battleTop')&&choice.includes('history.unshift'));ok('channel search cached',choice.includes('jfm_channel_search_cache_v1')&&choice.includes('45*60*1000'));ok('diagnostics expose update state',diag.includes('Update beschikbaar')&&diag.includes('Spotify-device')&&diag.includes('App-cache'));ok('diagnostics safe repair exists',diag.includes('Herstel Josh FM')&&diag.includes("recover('manual-diagnostics')")&&diag.includes("maintain?.('manual-diagnostics')"));
ok('legacy alternate TTS APIs removed',!exists('api/tts-elevenlabs.js')&&!exists('api/tts-piper.js')&&!exists('api/elevenlabs-voices.js'));ok('Fish remains primary TTS endpoint',exists('api/tts.js')&&read('debug-tts.js').includes("fetch('/api/tts'"));
for(const f of ['api/fact.js','api/discover.js','api/dj.js'])if(exists(f))ok(`${f} timeout`,read(f).includes('AbortController')&&read(f).includes('timedFetch'));if(exists('personal-top40.js')){const t=read('personal-top40.js');ok('Top 40 dedupe/clear',t.includes('canonicalKey')&&t.includes('mergeEntries')&&t.includes('clearTop40'))}
const temp=files.filter(f=>/(^|\/)(\.noop|\.placeholder|__noop__|.*-replacement\.js|.*\.tmp)$/.test(f));ok('no temporary deploy files',temp.length===0,temp.join(', '));for(const j of ['package.json','vercel.json','manifest.webmanifest'])if(exists(j)){try{JSON.parse(read(j));pass.push(`valid JSON ${j}`)}catch(e){fail.push(`valid JSON ${j} — ${e.message}`)}}
console.log(`Josh FM predeploy: ${pass.length} PASS, ${fail.length} FAIL`);if(fail.length){for(const x of fail)console.error('FAIL:',x);process.exit(1)}for(const x of pass.filter(x=>!x.startsWith('syntax ')))console.log('PASS:',x);
