import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
const root=process.cwd(),fail=[],pass=[];const read=p=>fs.readFileSync(path.join(root,p),'utf8'),exists=p=>fs.existsSync(path.join(root,p));const ok=(n,c,d='')=>(c?pass:fail).push(`${n}${d?` — ${d}`:''}`);
function walk(dir='.') {const out=[];for(const e of fs.readdirSync(path.join(root,dir),{withFileTypes:true})){if(['.git','node_modules','.vercel','backups'].includes(e.name))continue;const rel=path.join(dir,e.name).replace(/^\.\//,'');if(e.isDirectory())out.push(...walk(rel));else out.push(rel)}return out}
const files=walk(),js=files.filter(f=>f.endsWith('.js')||f.endsWith('.mjs'));for(const f of js){try{execFileSync(process.execPath,['--check',path.join(root,f)],{stdio:'pipe'});pass.push(`syntax ${f}`)}catch(e){fail.push(`syntax ${f} — ${String(e.stderr||e.message).trim()}`)}}
const runtimeJs=js.filter(f=>!f.startsWith('scripts/')&&!f.startsWith('tests/')&&!f.startsWith('.github/')),allJs=runtimeJs.map(f=>[f,read(f)]),players=allJs.filter(([,s])=>s.includes('new Spotify.Player'));
ok('backup policy exists',exists('backups/README.md')&&read('PRE_DEPLOY.md').includes('backup'));ok('at least one production backup exists',exists('backups')&&fs.readdirSync(path.join(root,'backups')).some(x=>x!=='README.md'));
ok('single Spotify.Player',players.length===1&&players[0]?.[0]==='stability-core.js',players.map(([f])=>f).join(', ')||'none');ok('legacy controllers removed',!exists('spotify-core.js')&&!exists('playback-web-sdk.js')&&!exists('stable-playback.js'));
const sdk=read('stability-core.js'),primary=read('playback-primary.js'),dj=read('dj-handoff-v34.js'),pwa=read('pwa-platform.js'),cfg=read('spotify-test-config.js'),sw=read('sw.js'),versionJs=read('version.js'),versionApi=read('api/version.js'),pkg=JSON.parse(read('package.json'));
ok('SDK disables own MediaSession',sdk.includes('enableMediaSession:false')&&sdk.includes('sdk-core-v4-end-signal-no-mediasession'));ok('SDK emits natural end signal',sdk.includes('jfm:natural-track-end')&&sdk.includes('nearEnd'));ok('SDK no transport/DJ ownership',!sdk.includes('window.djBreak=')&&!/(?:ownButton|own|replace)\(['"](?:start|play|next|prev)['"]/.test(sdk));
ok('primary owns transport',primary.includes("JFMPlaybackPrimary='playback-primary'")&&primary.includes("dataset.jfmOwner='primary'"));ok('iOS gesture capture',primary.includes('activateElement')&&primary.includes("document.addEventListener('click'"));ok('natural end guard exists',primary.includes('handleNaturalEnd')&&primary.includes('jfm:natural-track-end')&&primary.includes('primary-natural-end'));ok('natural end does not count skip',primary.includes("advance({record:false,source:'primary-natural-end'})"));ok('skip fallback retained',primary.includes('stationNeighbor')&&primary.includes('playContextDirect'));
ok('DJ flow mute first',dj.includes('await setVolume(0)'));ok('DJ flow stays playing',!dj.includes('/me/player/pause')&&!dj.includes('player()?.pause'));ok('DJ rewinds same new track',dj.includes('rewindExpected(expectedUri)')&&dj.includes('seek(0)'));ok('DJ unmutes after rewind',dj.includes('await setVolume(1)'));ok('DJ validates track/device',dj.includes('TRACK_URI')&&dj.includes('DEVICE')&&dj.includes('validDevice'));ok('DJ v36 owner',dj.includes("dataset.jfmHandoffOwner='v36'")&&dj.includes("handoff-v36-mute-rewind"));
ok('PWA sole MediaSession owner',pwa.includes('pwa-v4-single-mediasession-owner')&&pwa.includes('safePositionState'));ok('MediaSession bounds position',pwa.includes('position>=duration')&&pwa.includes('durationMs-1'));ok('track change resets media position',pwa.includes('updateMediaSession({reset:true})'));ok('no other runtime MediaSession writers',allJs.filter(([f,s])=>f!=='pwa-platform.js'&&(s.includes('setPositionState')||s.includes('new MediaMetadata'))).length===0,allJs.filter(([f,s])=>f!=='pwa-platform.js'&&(s.includes('setPositionState')||s.includes('new MediaMetadata'))).map(([f])=>f).join(', '));
ok('v36 loaders wired',cfg.includes('playback-primary.js?v=36')&&cfg.includes('spotify-api-budget.js?v=36')&&cfg.includes('dj-handoff-v34.js?v=36'));ok('PWA cache v37',sw.includes("josh-fm-v37-release-identity")&&sw.includes("'./version.js'")&&sw.includes("'./playback-primary.js'")&&sw.includes("'./dj-handoff-v34.js'"));ok('release version matches package',versionJs.includes(`version:'${pkg.version}'`)&&versionApi.includes(`version:'${pkg.version}'`));ok('release endpoint uses deployed commit',versionApi.includes('VERCEL_GIT_COMMIT_SHA')&&versionJs.includes("fetch('/api/version'"));
for(const f of ['api/fact.js','api/discover.js','api/dj.js'])if(exists(f))ok(`${f} timeout`,read(f).includes('AbortController')&&read(f).includes('timedFetch'));if(exists('personal-top40.js')){const t=read('personal-top40.js');ok('Top 40 dedupe/clear',t.includes('canonicalKey')&&t.includes('mergeEntries')&&t.includes('clearTop40'))}
const temp=files.filter(f=>/(^|\/)(\.noop|\.placeholder|__noop__)$/.test(f));ok('no temporary deploy files',temp.length===0,temp.join(', '));for(const j of ['package.json','vercel.json','manifest.webmanifest'])if(exists(j)){try{JSON.parse(read(j));pass.push(`valid JSON ${j}`)}catch(e){fail.push(`valid JSON ${j} — ${e.message}`)}}
console.log(`Josh FM predeploy: ${pass.length} PASS, ${fail.length} FAIL`);if(fail.length){for(const x of fail)console.error('FAIL:',x);process.exit(1)}for(const x of pass.filter(x=>!x.startsWith('syntax ')))console.log('PASS:',x);
