export const MAIR_DJ_PROMPT_VERSION='1.0.0';
const TYPES=new Set(['INTRO','OUTRO','BACK_ANNOUNCE','FORWARD_ANNOUNCE','ARTIST_FACT','TRACK_FACT','TWO_SONG_LINK','STATION_ID','TIME_CHECK','HOUR_OPENER','HOUR_CLOSER','SESSION_LINK']);
const ENERGIES=new Set(['LOW','NORMAL','UP']),DEFAULT_MODELS=['openai/gpt-oss-120b','openai/gpt-oss-20b'],RATE=new Map();
const safe=(v,n=1200)=>String(v??'').replace(/\s+/g,' ').trim().slice(0,n);
async function timedFetch(url,opt={},ms=12000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...opt,signal:c.signal})}finally{clearTimeout(timer)}}
function rateLimit(req,res){const windowMs=60000,limit=20,ip=String(req.headers?.['x-forwarded-for']||req.headers?.['x-real-ip']||'unknown').split(',')[0].trim().slice(0,80),now=Date.now(),fresh=(RATE.get(ip)||[]).filter(at=>now-at<windowMs);if(fresh.length>=limit){const retry=Math.max(1,Math.ceil((windowMs-(now-fresh[0]))/1000));res.setHeader('Retry-After',String(retry));res.status(429).json({error:'rate_limited',detail:`Probeer het over ${retry} seconden opnieuw.`,provider:'groq'});return false}fresh.push(now);RATE.set(ip,fresh);if(RATE.size>512)for(const[k,hits]of RATE)if(!hits.some(at=>now-at<windowMs))RATE.delete(k);return true}
function compactTrack(t){if(!t||typeof t!=='object')return null;return{id:safe(t.id,120),name:safe(t.name,180),artists:Array.isArray(t.artists)?t.artists.map(x=>safe(x,120)).filter(Boolean).slice(0,4):[],album:safe(t.album,180),release:safe(t.release,20),year:Number(t.year)||0,genres:Array.isArray(t.genres)?t.genres.map(x=>safe(x,60)).filter(Boolean).slice(0,5):[],discovery:!!t.discovery,request:!!t.request,energy:ENERGIES.has(String(t.energy).toUpperCase())?String(t.energy).toUpperCase():''}}
function context(value){if(!value||typeof value!=='object'||value.schemaVersion!=='1.0.0'||!value.break||!value.onAir||!value.session||!value.memory||!Array.isArray(value.allowedFacts))return null;return{schemaVersion:'1.0.0',break:{breakType:safe(value.break.breakType,40),targetWords:Number(value.break.targetWords)||0,maxDurationSeconds:Number(value.break.maxDurationSeconds)||0,energy:ENERGIES.has(value.break.energy)?value.break.energy:'NORMAL',mustMention:(value.break.mustMention||[]).map(x=>safe(x,100)).slice(0,3),permittedTopics:(value.break.permittedTopics||[]).map(x=>safe(x,80)).slice(0,8),prohibitedTopics:(value.break.prohibitedTopics||[]).map(x=>safe(x,80)).slice(0,12)},onAir:{previous:compactTrack(value.onAir.previous),next:compactTrack(value.onAir.next),future:(value.onAir.future||[]).map(compactTrack).filter(Boolean).slice(0,3),relationship:value.onAir.relationship?{kind:safe(value.onAir.relationship.kind,40),text:safe(value.onAir.relationship.text,280)}:null},session:{station:safe(value.session.station,80)||'MAIR',localTime:safe(value.session.localTime,20),day:safe(value.session.day,30),daypart:safe(value.session.daypart,30),durationMinutes:Math.max(0,Number(value.session.durationMinutes)||0),narrative:{dominantGenre:safe(value.session.narrative?.dominantGenre,60),dominantEra:safe(value.session.narrative?.dominantEra,30),discoveries:Math.max(0,Number(value.session.narrative?.discoveries)||0),recentSkips:Math.max(0,Number(value.session.narrative?.recentSkips)||0),sessionTracks:Math.max(0,Number(value.session.narrative?.sessionTracks)||0)}},memory:{revision:Math.max(0,Number(value.memory.revision)||0),recentBreaks:(value.memory.recentBreaks||[]).slice(0,10).map(x=>({type:safe(x.type,40),text:safe(x.text,500),opening:safe(x.opening,120),openingPattern:safe(x.openingPattern,40),artists:(x.artists||[]).map(a=>safe(a,120)).slice(0,6),topics:(x.topics||[]).map(a=>safe(a,80)).slice(0,6),factIds:(x.factIds||[]).map(a=>safe(a,100)).slice(0,3)})),usedFactIds:(value.memory.usedFactIds||[]).map(x=>safe(x,100)).slice(0,100)},allowedFacts:value.allowedFacts.slice(0,3).map(f=>({factId:safe(f.factId,100),subjectType:['track','artist'].includes(f.subjectType)?f.subjectType:'artist',subjectId:safe(f.subjectId,120),text:safe(f.text,500),sourceType:safe(f.sourceType,60),confidence:Number(f.confidence)||0})),doNot:(value.doNot||[]).map(x=>safe(x,100)).slice(0,12)}}
const SYSTEM_PROMPT=`Je bent de on-air DJ van MAIRFM, een persoonlijke Nederlandse muziekzender. Je bent geen chatbot, assistent, commentator of technicus. Schrijf alleen woorden die letterlijk worden uitgesproken.

Stijl: natuurlijk hedendaags Nederlands, ontspannen, zelfverzekerd, spontaan en beknopt. Spreek één luisteraar persoonlijk aan. Gebruik korte zinnen en één helder idee. Droge humor mag alleen als die vanzelf past. Geen overdreven enthousiasme.

Maak een doorlopende radioshow. Respecteer het opgegeven breaktype. Som metadata niet mechanisch op. Noem niet steeds zowel vorige als volgende track. Vermijd recente openingen, onderwerpen, feiten en artiesten uit het geheugen. Verbind muziek alleen met aangeleverde context. Bij zwakke context schrijf je een eenvoudiger link.

Feiten mogen uitsluitend uit ALLOWED FACTS of directe trackmetadata komen. Verzin nooit jaartallen, hitlijstposities, afkomst, samenwerkingen, prijzen of releasegegevens.

Noem nooit AI, een taalmodel, Groq, Fish Audio, Spotify API, metadata, prompts, bronnen of luisterprofielen. Vermijd clichés als “wat ontzettend leuk”, “hier word je toch vrolijk”, “absoluut fantastisch”, “laten we erin duiken”, “klaar voor de volgende”, “hier komt-ie” en “blijf luisteren”.

Geef platte gesproken tekst: geen markdown, JSON, aanhalingstekens, labels, emoji, regieaanwijzingen of uitleg. Blijf binnen het woorddoel; korter is beter. Als context onzeker is, kies de veiligste eenvoudige muziekschakel.`;
const INSTRUCTIONS={INTRO:'Praat kort vooruit naar de volgende track. Gebruik alleen titel en artiest die zijn aangeleverd.',OUTRO:'Sluit de vorige track kort af zonder waardeoordeel te verzinnen.',BACK_ANNOUNCE:'Noem kort wat zojuist speelde.',FORWARD_ANNOUNCE:'Kondig de volgende track compact aan.',ARTIST_FACT:'Gebruik precies één goedgekeurd artiestfeit en niets daarbuiten.',TRACK_FACT:'Gebruik precies één goedgekeurd trackfeit en niets daarbuiten.',TWO_SONG_LINK:'Leg één aantoonbare verbinding tussen vorige en volgende track op basis van RELATIONSHIP.',STATION_ID:'Geef een korte natuurlijke MAIRFM-identificatie.',TIME_CHECK:'Noem uitsluitend de aangeleverde lokale tijd en ga terug naar de muziek.',HOUR_OPENER:'Open het radio-uur compact met tijd/dagdeel en muziekcontext.',HOUR_CLOSER:'Sluit het radio-uur compact af en houd de muziek centraal.',SESSION_LINK:'Gebruik uitsluitend de aangeleverde sessietrend en verbind die met de muziek.'};
const PERSONAS={josh:'natuurlijke hoofdpresentator: warm, helder en zelfverzekerd; nooit schreeuwerig',maya:'warme storyteller: menselijk, rustig en compact',max:'energieke drive- en partyhost: tempo en plezier, maar geen geschreeuw',noah:'rustige curator voor avond en late night: minder woorden en veel ruimte voor muziek'};
const MODE_INSTRUCTIONS={normal:'Geen speciale mode.', 'time-machine':'Presenteer als retrospecial. Noem het gekozen jaar niet steeds. Historische context mag uitsluitend uit ALLOWED FACTS komen.',chaos:'Iets losser en droog. Benoem hooguit soms een opvallende overgang; maak niet van iedere track een grap.',roadtrip:'Verbind alleen subtiel met de aangeleverde roadtripfase. Verzin nooit aankomstinformatie.',afterparty:'Korter, losser en persoonlijk. Geen alcoholfocus, overdreven radiostem of geforceerde slang.'};
function payload(req){const p=req.body||{},breakType=safe(p.breakType,40),energy=safe(p.energy||'NORMAL',20).toUpperCase(),targetWords=Number(p.targetWords),ctx=context(p.context),specialMode=Object.hasOwn(MODE_INSTRUCTIONS,safe(p.context?.session?.specialMode?.mode,30))?safe(p.context.session.specialMode.mode,30):'normal',specialLabel=safe(p.context?.session?.specialMode?.label,80),rawRecap=p.context?.session?.specialMode?.recap,recap=rawRecap?{period:safe(rawRecap.period,20),minutes:Math.max(0,Number(rawRecap.minutes)||0),tracks:Math.max(0,Number(rawRecap.tracks)||0),topArtist:safe(rawRecap.topArtist,120),topTrack:safe(rawRecap.topTrack,180),decade:safe(rawRecap.decade,30),skips:Math.max(0,Number(rawRecap.skips)||0),requests:Math.max(0,Number(rawRecap.requests)||0),discoveries:Math.max(0,Number(rawRecap.discoveries)||0),insight:safe(rawRecap.insight,240)}:null,djProfile=Object.hasOwn(PERSONAS,safe(p.djProfile,20).toLowerCase())?safe(p.djProfile,20).toLowerCase():'josh';if(!safe(p.breakId,120))return{error:'invalid_break_id'};if(!TYPES.has(breakType))return{error:'invalid_break_type'};if(!ENERGIES.has(energy))return{error:'invalid_energy'};if(!Number.isInteger(targetWords)||targetWords<4||targetWords>50)return{error:'invalid_target_words'};if(!ctx||ctx.break.breakType!==breakType)return{error:'invalid_context'};return{breakId:safe(p.breakId,120),breakType,energy,targetWords,context:ctx,specialMode,specialLabel,recap,djProfile,regenerationFeedback:(p.regenerationFeedback||[]).map(x=>safe(typeof x==='string'?x:x?.code,100)).filter(Boolean).slice(0,6)}}
export default async function handler(req,res){
  if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});if(!rateLimit(req,res))return;const key=process.env.GROQ_API_KEY;if(!key)return res.status(503).json({error:'GROQ_API_KEY ontbreekt'});const p=payload(req);if(p.error)return res.status(400).json({error:p.error,promptVersion:MAIR_DJ_PROMPT_VERSION});
  const requestId=safe(req.headers?.['x-mair-break-id']||p.breakId,120),explicit=safe(process.env.GROQ_DJ_MODEL||'',120),models=[...new Set([explicit,...DEFAULT_MODELS].filter(Boolean))].slice(0,2),deadline=Date.now()+11000;res.setHeader('X-MAIR-Request-ID',requestId);
  const system=`${SYSTEM_PROMPT}\n\nDJ-PERSONA: ${PERSONAS[p.djProfile]}`;
  const user=`BREAK TYPE: ${p.breakType}\nENERGY: ${p.energy}\nTARGET WORDS: ${p.targetWords}\nSPECIALE MODE: ${p.specialMode}${p.specialLabel?' · '+p.specialLabel:''}\nMODE-OPDRACHT: ${MODE_INSTRUCTIONS[p.specialMode]}\nRECAP DATA: ${p.recap?JSON.stringify(p.recap):'geen'}\nRECAP-REGEL: ${p.recap?'Gebruik alleen deze cijfers voor één korte persoonlijke recap; voeg geen conclusies of cijfers toe.':'Geen recap gevraagd.'}\nSPECIFIEKE OPDRACHT: ${INSTRUCTIONS[p.breakType]}\nREGENERATION FEEDBACK: ${p.regenerationFeedback.length?p.regenerationFeedback.join(', '):'geen'}\nCONTEXT: ${JSON.stringify(p.context)}\n\nSchrijf precies één radiolink en geef alleen de letterlijk gesproken tekst.`;
  const attempts=[];for(const model of models){try{const remaining=deadline-Date.now();if(remaining<750){attempts.push({model,status:504,error:'Groq total deadline exceeded'});break}const r=await timedFetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json','X-MAIR-Request-ID':requestId},body:JSON.stringify({model,messages:[{role:'system',content:system},{role:'user',content:user}],temperature:.64,max_completion_tokens:420,top_p:.88,reasoning_effort:'low',include_reasoning:false})},Math.min(6000,remaining)),d=await r.json().catch(()=>({}));if(!r.ok){const error=safe(d?.error?.message||`Groq HTTP ${r.status}`,500);attempts.push({model,status:r.status,error});if([401,403,429].includes(r.status))break;continue}const text=safe(d?.choices?.[0]?.message?.content,1200).replace(/^['"“”]+|['"“”]+$/g,'').trim();if(!text){attempts.push({model,status:502,error:'Groq gaf geen DJ-tekst terug'});continue}return res.status(200).json({text,estimatedWords:text.split(/\s+/).filter(Boolean).length,breakType:p.breakType,promptVersion:MAIR_DJ_PROMPT_VERSION,provider:'groq',model,requestId,persona:p.djProfile,usage:d?.usage||null,attempts})}catch(e){attempts.push({model,status:e?.name==='AbortError'?504:500,error:e?.name==='AbortError'?'Groq timeout':safe(e?.message||e,500)})}}
  const last=attempts.at(-1)||{model:models[0],status:502,error:'Groq gaf geen DJ-tekst terug'},status=[401,403,429].includes(last.status)?last.status:last.status===504?504:502;return res.status(status).json({error:last.error,provider:'groq',model:last.model,requestId,promptVersion:MAIR_DJ_PROMPT_VERSION,attempts})
}
