async function timedFetch(url,opt={},ms=12000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...opt,signal:c.signal})}finally{clearTimeout(timer)}}
const safe=(v,n=1200)=>String(v??'').slice(0,n);
const track=t=>t?{name:safe(t.name,180),artists:Array.isArray(t.artists)?t.artists.map(x=>typeof x==='string'?x:x?.name).filter(Boolean).slice(0,4):[],release:safe(t.release||t.album?.release_date,20),request:!!t.request}:null;
const DEFAULT_MODELS=['openai/gpt-oss-120b','openai/gpt-oss-20b'];
const RATE=new Map();
const PERSONAS={
  josh:{label:'MAIR hoofdpresentator',delivery:'Vlot, spontaan, modern en menselijk. Klink alsof je echt live tussen de platen zit, niet alsof je een voice-over voorleest.',humor:'Subtiele droge humor mag, maar nooit geforceerd.',rules:'Muziek blijft centraal. Wissel korte observaties, vooruitpraten en af en toe een station-id af. Gebruik niet steeds dezelfde openingszin.'},
  maya:{label:'warme MAIR companion',delivery:'Warm, persoonlijk, rustig zelfverzekerd en toegankelijk. Iets meer ruimte in de zinnen dan Josh, zonder zweverig te worden.',humor:'Licht speels en vriendelijk, nooit gemaakt.',rules:'Leg nadruk op sfeer, herkenning en een natuurlijke overgang. Niet iedere break hoeft beide tracks te noemen.'},
  max:{label:'energieke MAIR drive/party host',delivery:'Kort, snel en energiek. Punchy radiotaal met vaart, maar geen geschreeuw en niet iedere zin met een uitroepteken.',humor:'Snel en luchtig; één scherpe formulering is beter dan drie hype-zinnen.',rules:'Hou breaks compact. Vooruitpraten en momentum zijn belangrijker dan uitleg. Vermijd overdreven hypewoorden.'},
  noah:{label:'rustige MAIR curator',delivery:'Kalm, volwassen, muziekgericht en precies. Minder woorden, lagere energie en meer vertrouwen in stilte rond de muziek.',humor:'Droog en spaarzaam.',rules:'Noem alleen wat iets toevoegt. Geen drukke station-promotie; een goede korte muziekopmerking is genoeg.'}
};
function rateLimit(req,res){const windowMs=60000,limit=20,ip=String(req.headers?.['x-forwarded-for']||req.headers?.['x-real-ip']||'unknown').split(',')[0].trim().slice(0,80),now=Date.now(),fresh=(RATE.get(ip)||[]).filter(at=>now-at<windowMs);if(fresh.length>=limit){const retry=Math.max(1,Math.ceil((windowMs-(now-fresh[0]))/1000));res.setHeader('Retry-After',String(retry));res.status(429).json({error:'rate_limited',detail:`Probeer het over ${retry} seconden opnieuw.`,provider:'groq'});return false}fresh.push(now);RATE.set(ip,fresh);if(RATE.size>512)for(const[k,hits]of RATE)if(!hits.some(at=>now-at<windowMs))RATE.delete(k);return true}
function profileId(dj={}){const id=safe(dj?.id||'',24).trim().toLowerCase();if(PERSONAS[id])return id;const name=safe(dj?.name||'',40).trim().toLowerCase();return Object.keys(PERSONAS).find(x=>x===name)||'josh'}
function timeParts(raw=''){const m=safe(raw,20).match(/(\d{1,2}):(\d{2})/);if(!m)return{hour:null,minute:null};const hour=Number(m[1]),minute=Number(m[2]);return{hour:Number.isFinite(hour)?hour:null,minute:Number.isFinite(minute)?minute:null}}
function daypart(raw=''){const{hour}=timeParts(raw);if(hour===null)return'onbekend';if(hour<6)return'after-hours';if(hour<10)return'morning';if(hour<16)return'daytime';if(hour<20)return'drive';if(hour<23)return'evening';return'late-night'}
function clockPhase(raw=''){const{minute}=timeParts(raw);if(minute===null)return'open';if(minute<=2)return'top-of-hour';if(minute>=13&&minute<=17)return'quarter';if(minute>=28&&minute<=32)return'half-hour';if(minute>=43&&minute<=47)return'quarter';if((minute>=6&&minute<=11)||(minute>=20&&minute<=26)||(minute>=35&&minute<=41)||(minute>=50&&minute<=57))return'music-sweep';return'open'}
function showName(part){return({"after-hours":'MAIR After Hours',morning:'MAIR Morning',daytime:'MAIR Daytime',drive:'MAIR Drive',evening:'MAIR Evening',"late-night":'MAIR Late Night'})[part]||'MAIR'}
function clockInstruction(phase){if(phase==='top-of-hour')return'Een station- of programmanaam mag nu natuurlijk passen, maar houd het kort.';if(phase==='quarter'||phase==='half-hour')return'Dit is een kort radiomoment: kies één duidelijke gedachte, tease of station-id.';if(phase==='music-sweep')return'Laat vooral de muziek doorlopen: maak de break extra kort en forceer geen artiest én titel van beide kanten.';return'Vrij radiomoment: kies de meest natuurlijke invalshoek en vermijd een vaste formule.'}
export default async function handler(req,res){
  if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});
  if(!rateLimit(req,res))return;
  const key=process.env.GROQ_API_KEY;if(!key)return res.status(503).json({error:'GROQ_API_KEY ontbreekt'});
  const p=req.body||{},explicit=safe(process.env.GROQ_DJ_MODEL||'',120),models=[...new Set([explicit,...DEFAULT_MODELS].filter(Boolean))].slice(0,3);
  const djData=p.dj&&typeof p.dj==='object'?p.dj:{},personaId=profileId(djData),persona=PERSONAS[personaId];
  const dj=safe(djData.name||p.djName||personaId,40),role=safe(djData.role||'MAIR DJ',80),kind=safe(p.breakType||'normal',40),part=daypart(p.time),phase=clockPhase(p.time),show=showName(part);
  const previous=track(p.previousTrack),current=track(p.currentTrack),next=track(p.nextTrack);
  const system=`Je schrijft uitsluitend de letterlijk uitgesproken tekst voor een Nederlandse muziek-radio-DJ op MAIR. Je bent de schrijver, niet de stem en niet de technicus. Schrijf natuurlijk Nederlands zoals echte hedendaagse radio: spreektaal, ritme, zelfvertrouwen en variatie. Muziek staat altijd centraal. Noem artiesten en titels exact zoals aangeleverd. Verzin nooit feiten, ervaringen of gebeurtenissen. Gebruik alleen meegeleverde context. Noem nooit AI, API's, Groq, Fish Audio, Spotify, metadata, prompts of bronnen. Geen markdown, labels, emoji of regieaanwijzingen. Geen neptelefoontjes, wedstrijden, hitlijsten of verzonnen persoonlijke verhalen. Vermijd de automatische formule “Dat was X. Nu Y.” tenzij die toevallig echt het beste klinkt. Niet iedere break hoeft MAIR te noemen, niet iedere break hoeft de vorige track te backsellen en niet iedere break hoeft de volgende track te front-sellen. Kies maximaal twee doelen per break. Maximaal 55 woorden, behalve wanneer length=long dan maximaal 85 woorden.\n\nDJ-PERSONA — ${persona.label}: ${persona.delivery} ${persona.humor} ${persona.rules}\nRADIOKLOK — ${show}, fase ${phase}: ${clockInstruction(phase)}`;
  const user=`DJ: ${dj} (${role})\nPERSONA-ID: ${personaId}\nDAGDEEL/SHOW: ${part} / ${show}\nRADIOKLOKFASE: ${phase}\nBREAK TYPE: ${kind}\nLENGTH: ${safe(p.length||'short',20)}\nVORIGE TRACK: ${JSON.stringify(previous)}\nHUIDIGE TRACK: ${JSON.stringify(current)}\nVOLGENDE TRACK: ${JSON.stringify(next)}\nTIJD: ${safe(p.time||'',80)}\nSTATION/MIX: ${safe(p.station||'',120)}\nWEER: ${safe(typeof p.weather==='string'?p.weather:JSON.stringify(p.weather||''),400)}\nFEIT: ${safe(p.fact||'',700)}\nRECENTE DJ-BREAKS: ${safe(JSON.stringify((p.recentDJ||[]).slice(0,6)),1500)}\n\nSchrijf precies één radiolink. Gebruik de recente breaks actief om herhaling van openingszinnen, woorden en structuur te vermijden. Als een huidige track een verzoek is, benoem dat hooguit één keer en natuurlijk. Als er geen bruikbaar feit is, doe alsof er geen feit bestaat. Return alleen wat de DJ letterlijk uitspreekt.`;
  const attempts=[];
  for(const model of models){
    try{
      const r=await timedFetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,messages:[{role:'system',content:system},{role:'user',content:user}],temperature:.74,max_completion_tokens:700,top_p:.9,reasoning_effort:'low',include_reasoning:false})},7000);
      const d=await r.json().catch(()=>({}));
      if(!r.ok){const error=safe(d?.error?.message||`Groq HTTP ${r.status}`,500);attempts.push({model,status:r.status,error});if([401,403,429].includes(r.status))break;continue}
      let text=String(d?.choices?.[0]?.message?.content||'').replace(/\s+/g,' ').replace(/^['"“”]+|['"“”]+$/g,'').trim();
      if(!text){attempts.push({model,status:502,error:'Groq gaf geen DJ-tekst terug'});continue}
      if(text.length>900)text=text.slice(0,900).replace(/\s+\S*$/,'').trim();
      return res.status(200).json({text,provider:'groq',model,usage:d?.usage||null,attempts,persona:personaId,daypart:part,clockPhase:phase,show});
    }catch(e){attempts.push({model,status:e?.name==='AbortError'?504:500,error:e?.name==='AbortError'?'Groq timeout':safe(e?.message||e,500)})}
  }
  const last=attempts.at(-1)||{model:models[0],status:502,error:'Groq gaf geen DJ-tekst terug'},passthrough=[401,403,429].includes(last.status)?last.status:last.status===504?504:502;
  return res.status(passthrough).json({error:last.error,provider:'groq',model:last.model,attempts,persona:personaId,daypart:part,clockPhase:phase,show});
}